### ISSUE TITLE
I thought selected text in VS code was included in chat conversations

### ISSUE THREAD

**Issue by craftzneko** [microsoft/vscode-copilot-release#1057] opened 2024-03-20 12:41 UTC
![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/40339c98-0222-4edc-991a-0f285c80d862)
- VS Code Version: 1.87.2
- OS Version:10.0.19045.4170
- Logs:

Steps to Reproduce:

1. select a power shell script in main window
2.ask it a question about the code

In my case this is intermittent. But a lot of my interactions with VS code seem to be intermittent

**Comment by craftzneko** [comment] 2024-03-20 12:46
this is just odd, its saying it doesnt have access but then shows me the exact code i have selected?!

![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/b9b6b361-13ea-4611-8041-ffa7402a07d3)

**Comment by dangayle** [comment] 2024-03-20 19:05
I'm having the same issue:

![image](https://github.com/microsoft/vscode-copilot-release/assets/129611/0f76feff-adda-470d-b204-a6e1bab55a6c)

**Comment by digitarald** [comment] 2024-03-21 23:29
Duplicate of #173.

**Closed by digitarald** 2024-03-21 23:29 UTC
