### ISSUE TITLE
Copilot Chat stopped working -  returns "Error from provider: Cannot read properties of undefined (reading 'map')" on submitting

### ISSUE THREAD

**Issue by ElijahLynn** [microsoft/vscode-copilot-release#763] opened 2024-01-20 00:39 UTC
Type: <b>Bug</b>

Open chat, enter question, submit. Returns error:

Error from provider: Cannot read properties of undefined (reading 'map')

Extension version: 0.12.2024011902
VS Code version: Code - Insiders 1.86.0-insider (c973ec767338f7846710cc2ee46e38b4504a044c, 2024-01-10T05:37:32.672Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|64.00GB (37.62GB free)|
|Process Argv|--crash-reporter-id 595b60af-d2a2-494f-b945-1984059e4f87|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:30784851
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772

```

</details>

**Comment by ElijahLynn** [comment] 2024-01-20 00:41
No extension updates are showing fwiw. Sometimes when I have an issue, I just need to update extensions but there are none this time.

**Comment by ElijahLynn** [comment] 2024-01-20 00:42
![image](https://github.com/microsoft/vscode-copilot-release/assets/1504756/73428c63-776c-4d61-9df1-5f6a521c00b8)

**Comment by ElijahLynn** [comment] 2024-01-20 00:43
Interesting, I opened a new chat and it is working now. The old chat still fails, fwiw (it didn't also start working).

**Comment by ElijahLynn** [comment] 2024-01-20 00:44
Oh, the new chat now broke again: 
![image](https://github.com/microsoft/vscode-copilot-release/assets/1504756/d3c9282b-7047-4252-b248-56570439b733)

**Comment by hassni12** [comment] 2024-01-20 09:09
**_- I think they add ? mark in front of map_**

**Comment by Andrehlb** [comment] 2024-01-21 00:21
![image](https://github.com/microsoft/vscode-copilot-release/assets/100593932/4a42ab74-688a-4a31-b9be-8e5505c15a0b)
![image](https://github.com/microsoft/vscode-copilot-release/assets/100593932/815f1473-ef23-4af4-a900-fda2b8641713)
This error ‘Error from provider: Cannot read properties of undefined (reading ‘map’)’ occurs when I open two chatcopilot windows. This error does not occur in just one window is open.

**Comment by fisforfaheem** [comment] 2024-01-21 17:45
use preRelease version

**Comment by mugaber-outlier** [comment] 2024-01-22 02:44
I'm using the `pre-release` version and I'm also facing the same issue.

**Comment by ananishimoto** [comment] 2024-01-22 10:20
In my case, the error was appearing for the `pre-release` one. I changed to the `released` version and it works fine after the reload.

**Comment by ElijahLynn** [comment] 2024-01-22 17:29
Looks like I am on the pre-release version of both the GitHub Copilot and GitHub Copilot Chat extensions. This morning I do see a "reload required" though so 🤞 .

**Comment by mustafakameldev** [comment] 2024-01-22 18:17
I'm facing same issue with VScode insiders too

**Comment by surfbryce** [comment] 2024-01-23 03:58
also getting the exact same issue currently, on insiders VSCode and pre-release CoPilot

**Comment by misaka00251** [comment] 2024-01-23 04:27
I'm getting this error too, both VSCode & Copilot plugin are on insider.

**Comment by elijahw0lf** [comment] 2024-01-23 07:41
Reporting in with the same problem, using VS Code Insiders pre-release. Both Copilot and Copilot Chat.

If you start a new session using the plus icon in the top-right corner, you can ask a question successfully. Any follow-up questions will not work. However, the workaround also works if you just delete all of your previous messages within the same session/conversation (so that your next question is the "first" question of the session).

Given that behaviour along with the error of reading "map", it sounds like there's a bug with follow-up questions. I believe the API works by requiring you to send the latest question plus every previous question (so sending your third question in a session means you're sending questions 3, 2, and 1). Unfortunately, that's the most info I can offer.

Also, I'm obliged to greet all other Elijahs I encounter, so hello @ElijahLynn! 😋 @

**Comment by roblourens** [comment] 2024-01-23 13:52
I can't reproduce this- can anyone check the "Copilot Chat" output channel for a full error stack?

**Comment by Psvensso** [comment] 2024-01-23 14:23
> I can't reproduce this- can anyone check the "Copilot Chat" or "Extension Host" or "Window" output channel for a full error stack?

2024-01-23 15:14:30.299 [info] [editGeneration] (case 2) Replacing selected code
2024-01-23 15:20:25.207 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1251:85)
    at c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1245:5254

**Comment by DennisJamin** [comment] 2024-01-23 17:04
@roblourens 

`2024-01-23 18:03:27.781 [error] TypeError: Cannot read properties of undefined (reading 'map')
    at AS.addHistory (/Users/dennis/.vscode-insiders/extensions/github.copilot-chat-0.12.2024012301/dist/extension.js:899:3415)
    at o.x (/Users/dennis/.vscode-insiders/extensions/github.copilot-chat-0.12.2024012301/dist/extension.js:911:957)
    at o.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:133069)
    at f.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:127470)
    at l.S (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:10846)
    at l.Q (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:10612)
    at l.M (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:9664)
    at l.L (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:8781)
    at f.value (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:7568)
    at r.y (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at n.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14039)
    at f.value (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:8049)
    at r.y (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at n.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14039)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6329)
    at MessagePortMain.emit (node:events:514:28)
    at Object.emit (node:electron/js2c/utility_init:2:2285) {"id":"GitHub.copilot-chat","identifier": ...cut...`

**Comment by knodi** [comment] 2024-01-24 02:38
> If you start a new session using the plus icon in the top-right corner

@elijahw0lf Thanks for saying how to start a new session!  I was confused until I got to your comment.  Problem solved for me now.

**Comment by roblourens** [comment] 2024-01-24 16:01
Thanks @DennisJamin - this is very strange though. I would really like to see the full "GitHub Copilot" output channel from a sessison that breaks like this, and also sharing the conversation eg by right click + Copy All may help as well.

**Comment by roblourens** [comment] 2024-01-24 16:30
Can you all check that you have the latest versions of Insiders? I just noticed that the date in the OP is days older than the extension, and that could be an issue.

**Comment by elijahw0lf** [comment] 2024-01-24 16:55
> Can you all check that you have the latest versions of Insiders? I just noticed that the date in the OP is days older than the extension, and that could be an issue.

I updated VS Code Insiders to v1.86.0-insider (Date 2024-01-24T05:36:35.802Z) and it the problem has resolved itself for me. I use Scoop on Windows so running `scoop update vscode-insiders` took care of it. I started a fresh chat session and asked 3 questions back-to-back with no error 👍

**Note:** I had tried everything I could think of before the update, restarted the app, signed out and back in (with Github), re-installed the extensions, and even reinstalled VS Code Insiders. I'm confident it's the update that resolved it. I hope this helps!

**Comment by roblourens** [comment] 2024-01-24 17:01
Can you tell me how you did the reinstall, that didn't give you the latest version?

We are making breaking changes between the extension and vscode as we iterate, so it's important to try to keep them in sync.

**Comment by fisforfaheem** [comment] 2024-01-24 17:08
I get various issues daily 🤧 kindly someone make it better and fix bugs
instead if writing LONG ARTICLES on GitHub Blog

**Comment by elijahw0lf** [comment] 2024-01-24 17:19
> Can you tell me how you did the reinstall, that didn't give you the latest version?
> 
> We are making breaking changes between the extension and vscode as we iterate, so it's important to try to keep them in sync.

For me, I uninstalled with Scoop (as it was managing the app for me) with the command `scoop uninstall vscode-insiders`. I then downloaded the latest version from [the official website](https://code.visualstudio.com/insiders/). I did that almost 6 days ago exactly from the time of this post. 

Unfortunately I don't have the install file to check what version it was. After confirming the bug was still there, I promptly uninstalled it so I could install it with Scoop again. If there's any other info I can provide that would be of assistance, I would be glad to assist. Just let me know 😊

**Comment by ElijahLynn** [comment] 2024-01-24 17:42
OP here: I've got all the updates now and it is working consistently again for me. At the time of breakage, there were no updates listed, so maybe there was a mismatch but I had no way to get the updates (I think).

**Comment by elijahw0lf** [comment] 2024-01-24 17:48
> OP here: I've got all the updates now and it is working consistently again for me. At the time of breakage, there were no updates listed, so maybe there was a mismatch but I had no way to get the updates (I think).

Same here, I started troubleshooting about a day after noticing the problem. At that time, I'm certain that I installed the latest version of VS Code Insiders but the fault persisted. I can't remember if there was an update available but I got the latest installer from the official website anyway. A strict Google search for the error message turned up just one result which is this GH issue (thank you OP for raising it).

**Comment by roblourens** [comment] 2024-01-24 17:50
Insiders updates every day, and at the time the issue was filed, yours was 9 days old, so if you weren't able to get the update, something was wrong! Maybe watch out for missing updates again and open another issue if that seems to continue.

I'm going to close this issue- I think it is related just to the breaking change I made, and having vscode out of sync with the extension.

**Closed by roblourens** 2024-01-24 17:50 UTC
Labels: bug, panel-chat, important

**Comment by elijahw0lf** [comment] 2024-01-25 02:18
> Insiders updates every day, and at the time the issue was filed, yours was 9 days old, so if you weren't able to get the update, something was wrong! Maybe watch out for missing updates again and open another issue if that seems to continue.
> 
> I'm going to close this issue- I think it is related just to the breaking change I made, and having vscode out of sync with the extension.

Thank you for taking the time to read and assist, it's comforting to know there's support happening in the backend here. Have a great weekend!

**Comment by drikusroor** [comment] 2024-02-02 13:36
Just a FYI for macOS users that might have this issue: I had the exact same issues as OP and realised my VS Code - Insiders has never updated itself automatically. That was because I had been opening the application from my `~/Downloads` folder instead of first dragging it to the `/Applications` folder, thereby making it read-only which causes it to not be able to update itself... 😳

See also this [Stackoverflow topic](https://stackoverflow.com/a/65422671/4496102)

**Comment by Thomas-C258** [comment] 2024-02-05 14:31
Same error here. I'm using codespace, and don't know how to update its web-vscode. Hints anyone?

**Comment by mishra-saksham** [comment] 2024-02-05 21:13
The problem persists and I can guess it's frontend, probably some fault in the electron code as the map problem is common in problem in most large JavaScript frameworks, I saw that it is working perfectly normal in the prod/regular version of Visual Studio Code. 
And I am guessing the A/B testing effect has not faded in my region yet for the updated VSCode Insiders which I understand from a developer point of view. 
I am not using VSCode desktop application rather I am using GitHub Codespace, so that was not much of an inconvenience.
Hope it answered some of the questions you might have.
Thanks,

**Comment by samsmithnz** [comment] 2024-02-10 17:32
Broken for me too. This is not fixed in pre-release or release in GitHub Codespaces.

**Comment by mishra-saksham** [comment] 2024-02-10 17:54
> Broken for me too. This is not fixed in pre-release or release in GitHub Codespaces.

Yes, meanwhile I contacted the team and they said the production environment has yet not been fixed in codespaces VSCode insiders, apart from that you can use the regular version of codespaces VSCode and it is working 😃!!! also the fact that is not up to date. So, If you are using codespaces VSCode insiders the ways to use the copilot chat extension are 1.) switch to regular version or 2.)delete the your prompts If you don't want to switch to insiders 3.) create new chats after every minute , as I said in my earlier message the problem 'map' is very common in JS frameworks which includes electron and VS code is made in electron so that should explain the issue.

**Comment by samsmithnz** [comment] 2024-02-10 18:07
Ahhh - thanks - switching VScode away from insider (and then copilot chat back to release) worked!

**Comment by Ritesh313** [comment] 2024-02-20 16:23
Hi, I'm still facing this issue. I'm using VS code insiders and release versions of Copilot and Copilot chat. I have to create new chat each time to ask a question. Is the recommended solution switching to the normal VS code version?

**Comment by roblourens** [comment] 2024-02-20 18:02
If you are using Insiders, please use the latest pre-release version of the extension

**Comment by Tuman829** [comment] 2024-02-20 20:02
@roblourens  I tried that for a fix, no dice

**Comment by roblourens** [comment] 2024-02-20 20:31
If you're still having issues, please open a new issue (and double-check that you are on the latest of everything. If not, we expect errors like this)

**Comment by Ritesh313** [comment] 2024-02-20 22:10
Switching to pre-release and updating insiders to the latest version (in that order) worked for me.
