### ISSUE TITLE
Context should try harder before saying "Sorry, but I can only assist with programming related questions."

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/vscode-copilot-release#682] opened 2023-12-16 15:10 UTC
- VS Code Version: Latest Stable
- OS Version: Mac latest beta

Steps to Reproduce:

1. Write a chapter in a book titled "AI for IT", Chapter 5 "Reports and Documentation" in Asciidoc (.adoc) format
2. Auto complete a few paragraphs with inline Copilot
3. Ask Copilot Chat "what should i write next? give me an outline and the conclusion paragraph for this section"
4. Copilot Chat says "Sorry I can't help you with that. I can only help with programming"
5. Tell it "But im writing an AI book for IT pros"
6. Watch as it outlines the chapter

Thank you 🙇🏼

**Comment by sergioisidoro** [comment] 2024-01-16 08:13
Just a note that I think the "Sorry, but I can only assist with programming related questions." should be relaxed a bit, since not everything we do in VS code is programming, sometimes it's ui copy, translation resources, etc.

Sometimes I use co-pilot to help me with suggestions for UI copy (eg. when text is too long for a certain UI element, I ask co-pilot to make it shorter, and give it feedback like "can you make it more friendly"). It's super helpful, especially for people who are not native speakers of a language to write good UI copy

I got the "Sorry I can't help you with that. I can only help with programming" for the first time today.

Using this trick works, I just need to say "yeah, but I'm writing a copy for a UI in react native" and it will gladly output the answer, but I would urge the co-pilot team to broaden the restriction to not only programming, but other programming and product building tasks :)

**Comment by potatoqualitee** [comment] 2024-01-30 04:29
@roblourens just saw your off topic label. am I in the wrong repo?

**Comment by roblourens** [comment] 2024-01-30 19:27
No, the issue is about our overactive off-topic filter :)

**Comment by neo-anderson** [comment] 2024-03-14 01:34
Another example:
Q: What are other terms like "tech debt" to describe code that is work in progress, still working on it and needs polish?
A: Sorry, but I can only assist with programming related questions.
Q: tech debt is programming related
A: Sorry, but I can only assist with programming related questions.

**Comment by dpk899** [comment] 2024-05-03 06:45
03 May 2024. This is still and Issue. 

![image](https://github.com/microsoft/vscode-copilot-release/assets/142969958/bd533ec9-5d93-4e9a-bdba-c46bbc0577e8)

**Comment by Faazlaeeq** [comment] 2024-07-01 10:14
Why copilot?
![image](https://github.com/microsoft/vscode-copilot-release/assets/75880165/5e87fcf1-083d-4244-8d56-cc591cee120d)

**Comment by fgaletic** [comment] 2024-07-07 18:04
This happens more and more. Are we supposed to pay more?

**Comment by luismvargasg** [comment] 2024-07-17 17:42
Same here, with code related questions...

**Comment by fgaletic** [comment] 2024-07-17 19:50
> I've been suffering with this more and more too. I ask it to literally generate some code, and I get "Sorry, but I can only assist with programming related questions." back. And then, if I only answer with something like "yes you can" it generates what I asked for. I'm practically having an aneurysm trying to make it be useful. It's rather quick to just . . . not do what it was created for, even if the question or prompt is or isn't programming related. Whether it is or isn't should be up to us, not to an arbitrary ruling or weights in the model. Not when it clearly is not up to the task.

It's crazy how many times I had to say "yes you can" to it and then it does what it's supposed to. Super annoying.

**Comment by potatoqualitee** [comment] 2024-07-18 16:35
This does not solve the problem, but it is a workaround: I created a GitHub Copilot Chat Extension that allows you to use the OpenAI (Azure or openai.com) API within GitHub Copilot Chat.

https://marketplace.visualstudio.com/items?itemName=chrissylemaire.assistants-chat-extension

![image](https://github.com/user-attachments/assets/74d48156-0295-4964-8224-ca46e9c20ff8)

If you don't already have an assistant setup, it'll offer to setup a Beavis and Butthead assistant which demonstrates that there really aren't any restrictions on the chat output.

![image](https://github.com/user-attachments/assets/76961621-e3f2-4894-a5d3-9af0031c342d)

Note that this does cost API tokens.

**Comment by fgaletic** [comment] 2024-07-19 13:36
@potatoqualitee thank you, I got stuck at this step:

"In the search bar, type "Assistants Chat Extension". Couldn't find it.

Anyway, do we know anything about a recent update that made the chat worse? It's incredible how uncooperative and generic it's been lately.

**Comment by potatoqualitee** [comment] 2024-07-19 16:18
@fgaletic ah, ive renamed it since and will update the docs, thank you. You can just skip that step, it'll auto-detect the missing key and prompt you to add either openai or azure openai info.

**Comment by digitarald** [comment] 2024-08-16 16:20
We updated the off-topic filter and see a significant drop in false-positive filtering in experiment results.

Closing as fixed, but please don't hesitate to file new issues in case you still run into this.

**Closed by digitarald** 2024-08-16 16:20 UTC
Labels: off-topic-filter

**Comment by potatoqualitee** [comment] 2024-08-22 07:08
thank you! 🙏🏼
