### ISSUE TITLE
All prompts, no matter the content, return "Sorry, the response matched public code so it was blocked. Please rephrase your prompt. "

### ISSUE THREAD

**Issue by andrew-jkc** [microsoft/vscode-copilot-release#594] opened 2023-11-21 20:30 UTC
- VS Code Version: 1.84.2
- OS Version: Windows 11 Pro
- Logs: 

Steps to Reproduce:

1.  In CoPilot Chats, write any prompt.
2.  Press send.

**Comment by shaneholloman** [comment] 2023-11-21 20:33
same issue

```log
2023-11-21T20:27:28.013Z [INFO] [auth] Logged in as shaneholloman
2023-11-21T20:27:28.688Z [INFO] [chat] copilot token chat_enabled: true
2023-11-21T20:27:28.690Z [INFO] [auth] Got Copilot token for shaneholloman
2023-11-21T20:27:28.710Z [INFO] [auth] Logged in as shaneholloman
2023-11-21T20:27:28.711Z [INFO] [chat] copilot token chat_enabled: true
2023-11-21T20:27:28.711Z [INFO] [auth] Got Copilot token for shaneholloman
2023-11-21T20:28:13.459Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-11-21T20:28:13.460Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-11-21T20:28:13.460Z [INFO] [chat fetch] chat model gpt-4
2023-11-21T20:28:14.655Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1193 ms
2023-11-21T20:28:14.656Z [INFO] [chat fetch] Request ID for failed request: ,b961376d-151f-4c5b-aa69-d4e48e242dc2
2023-11-21T20:28:14.659Z [ERROR] [chat fetch] Unhandled status from server:,400,Bad Request

2023-11-21T20:30:32.888Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-11-21T20:30:32.888Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-11-21T20:30:32.888Z [INFO] [chat fetch] chat model gpt-4
2023-11-21T20:30:34.142Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1252 ms
2023-11-21T20:30:34.144Z [INFO] [chat fetch] Request ID for failed request: ,57877f14-129a-4e6d-9236-f5ae57eb5805
2023-11-21T20:30:34.147Z [ERROR] [chat fetch] Unhandled status from server:,400,Bad Request
```

**Comment by asteriuscz** [comment] 2023-11-21 20:35
Same here

**Comment by diego4lbarracin** [comment] 2023-11-21 20:37
Same here, it looks like a huge bug since I already checked my settings and that option is enabled. ._.

**Comment by JurkoDev** [comment] 2023-11-21 20:37
me too i have it enabled too

**Comment by cgirou** [comment] 2023-11-21 20:40
Same, they obviously just broke it. 

(╯‵□′)╯︵┻━┻

**Comment by jassMarok** [comment] 2023-11-21 20:41
Same issue did a simple test with no files opened for prompt: how do query paramters work.

**Comment by SebastianLazarte** [comment] 2023-11-21 20:43
Same issue

**Comment by K8sKween** [comment] 2023-11-21 20:55
This should be closed as a duplicate of #583

**Comment by andrew-jkc** [comment] 2023-11-21 21:00
@K8sKween Likely, but I feel like mine was less specific to the User Account, and explains that it doesn't matter what the prompt is??  But that could still be a faux pas

**Comment by K8sKween** [comment] 2023-11-21 21:04
@andrew-jkc Feel free to keep it open. Take a look at the newly opened issues on this repo it seems we are all correlated to a bad release/change, you might want to share your logs in that issue where others are looking.

**Comment by lramos15** [comment] 2023-11-22 14:07
There was a service incident yesterday. This should be fixed now.

**Closed by lramos15** 2023-11-22 14:07 UTC
Labels: triage-needed
