### ISSUE TITLE
Copilot Chat not signing in

### ISSUE THREAD

**Issue by AlexanderMckie** [microsoft/vscode-copilot-release#1518] opened 2024-09-03 06:28 UTC
I have trouble signing in with my Github account for the Chat extension. The predictive feature is working while working on my code but the Chat extension keeps asking me to sign in. I use the link and it goes to my Github but never logs in

**Comment by naveenverma1994** [comment] 2024-09-03 07:47
Same issue, any solution for this?

**Comment by lramos15** [comment] 2024-09-03 17:29
I assume you're on the latest version of VS Code + Copilot Chat. Could you please provide some sort of screen recording just to help me gauge what might be happening.

**Comment by AlexanderMckie** [comment] 2024-09-04 06:29
Hi Logan,

How are you, the video will show my Vscode so you can get a better idea of the issue

Thanks


Github Copilot.mp4<https://1drv.ms/v/s!AkIcMYhmgh_YrJBW1_3Gw4YKP-kCeQ?e=SenMtY>

**Comment by TylerLeonhardt** [comment] 2024-09-05 02:52
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2299464817

**Closed by TylerLeonhardt** 2024-09-05 02:52 UTC

**Comment by naveenverma1994** [comment] 2024-09-05 04:40
I had switched back to the older version. It's fine there.
