### ISSUE TITLE
Sorry, your request failed.

### ISSUE THREAD

**Issue by HarleyVader** [microsoft/vscode-copilot-release#3142] opened 2024-12-10 13:07 UTC
Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id a93d1c2a-fef3-49ab-8669-5b24511df8bb and try again

Extension version: 0.23.2024102903
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|29.82GB (9.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment] 2024-12-11 13:52
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/2627
Please comment on that issue, ideally with reproducible steps

**Closed by isidorn** 2024-12-11 13:52 UTC
Labels: triage-needed
