### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by jacobcoro** [microsoft/vscode-copilot-release#805] opened 2024-01-30 02:31 UTC
Latest version of chat: v0.11.1

- VS Code Version: Version: 1.86.0-insider (Universal)
- OS Version: Mac OS 13.4.1 (c) (22F770820d)
- Logs:
<img width="497" alt="Screenshot 2024-01-30 at 10 28 45" src="https://github.com/microsoft/vscode-copilot-release/assets/52448067/f2efcfc9-a33b-4ec9-a852-8fda732f7b07">
Steps to Reproduce:

1. ask it a question
2. ask it a follow up. it shows the 'Cannot read properties of undefined (reading 'split')' error
3. ask it again any number of times even with differewnt followup question. Same error.

**Comment by wagnerone** [comment] 2024-01-31 00:21
Same here - for quite a few days now I've been getting this.

vscode Version: 1.86.0-insider
Commit: 8c08612b658a37f96892f8ed5a9c6e7a6667847d

chat v0.12.2024013003 (pre-release)

**Comment by Songworks** [comment] 2024-01-31 09:56
Interesting.
I had the same error with the release version (v0.11.1).

After switching to the pre-release version (v0.12.2024013003) the chat seems to work fine again.

Switched back to release version as a sanity check and the error is also back.


Version: 1.86.0-insider
Commit: 800e60abdfb1675a59520bac6a9473bc380d49ea
Date: 2024-01-23T06:11:42.114Z
Electron: 27.2.3
ElectronBuildId: 26378995
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.1.0-1028-oem (Ubuntu 22.04.3 LTS)

**Comment by wagnerone** [comment] 2024-01-31 14:51
I had an update of "github copilot" plugin this morning (not the "github copilot chat" plugin and vscode itself.

now I'm at

vscode 1.86.0-insider, Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
copilot v1.156.683 (pre-release)
copilot chat v0.12.2024013003 (pre-release)

After updating that today, chat seems to be fixed, but jury is still out. It failed once with the same error after initially working a few questions, but it continue to answer after that single failure.

**Comment by Koutawars** [comment] 2024-01-31 17:13
i had the same error:

now i'm at:
GitHub Copilot Chat v0.11.1
GitHub Copilot v1.156.0
- vscode
Versión: 1.86.0-insider (user setup)
Commit: 9c5eabb378c9d18a0f712d1f22fe63df3f933ade
Date: 2024-01-30T03:56:13.017Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
SO: Windows_NT x64 10.0.19045

**Comment by LikeDreamwalker** [comment] 2024-02-01 12:43
same issue here and just received today

**Comment by digitarald** [comment] 2024-02-03 17:53
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/796#issuecomment-1925413610

**Closed by digitarald** 2024-02-03 17:53 UTC
Labels: triage-needed
