### ISSUE TITLE
Two empty, unsaved files are created and opened in the editor whenever I use the chat

### ISSUE THREAD

**Issue by fritz-trawa** [microsoft/vscode-copilot-release#2699] opened 2024-11-19 10:43 UTC
- Copilot Chat Extension Version:
1.245.0

- VS Code Version:
Version: 1.96.0-insider
Commit: 841e8b187db105c686aab655d8f966c154e66a7f
Date: 2024-11-14T05:04:02.900Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

- Logs: 
No output

Steps to Reproduce:

1. CTRL-CMD I to start the chat
2. Ask anything about current file (e.g., "add comments to each function"
3. Two empty, unsaved files are created and opened in the editor as soon as I press return in the prompt window

**Comment by jrieken** [comment] 2024-11-19 15:29
> CTRL-CMD I to start the chat

Sorry, but I am not sure if you mean inline chat (`cmd+i` inside the editor) or copilot edits (`cmd+shift+i`)

**Comment by fritz-trawa** [comment] 2024-11-20 14:57
I meant what I wrote, <CMD-CTRL-I>, Keybinding "View: Show Chat" , it opens the copilot chat panel on the side

**Comment by fallerd** [comment] 2024-11-21 19:39
same. 2 files appear as soon as I submit a chat.

**Comment by jrieken** [comment] 2024-11-22 13:51
Ok, someone please help and distill steps. This is what I do

* open a file 
* open panel chat
* ask "add comments to each function"
* get a code reply in the box
* no unsaved/dirty files...

https://github.com/user-attachments/assets/60128906-7fe5-4980-b66e-b1bc99b17883

**Comment by fritz-trawa** [comment] 2024-11-25 09:16
One thing that could be relevant - I am editing a python file, you (@jrieken ) were editing a js one. Maybe it's a clash with the python plugins? Just throwing wild guesses out there

**Comment by jrieken** [comment] 2024-11-25 10:13
Also with a python file on screen, I cannot reproduce. Can you try extension bisect to see if there is another extension involved? These are the instructions:


It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by fritz-trawa** [comment] 2024-12-02 13:52
I finally had some time to do the bisect thing and.... it's not happening any more.

I guess whatever caused was fixed. Closing issue, happy to reopen if other people are still experiencing it.

**Comment by fallerd** [comment] 2024-12-02 16:44
Following up on the closing of this issue; still experiencing the same problem. Any time I send any chat in the copilot chat box, it opens 2 blank unsaved files: Untitled-1 and Untitled-4. I bisected and the conclusion was that is is github copilot chat. Because Fritz said his issue went away, I downloaded the latest vscode update, disabled all other extensions aside from copilot and copilot chat, even tried switching to pre-release version of copilot chat, and the issue remains in all cases I have tested. I have no reason to believe that this is anything but a copilot chat issue at this point.

**Comment by fritz-trawa** [comment] 2024-12-02 17:08
How bizarre. Happy to reopen the issue.

**Comment by jrieken** [comment] 2024-12-02 17:14
> Any time I send any chat in the copilot chat box, it opens 2 blank unsaved files: Untitled-1 and Untitled-4. I bisected and the conclusion was that is is github copilot chat.

I believe you but given very many chat users and our daily self-hosting not showing this, there must be something more complex as "make a request". 

Can you try with an empty profile? Or without settings? Can you share the working in which you are trying this? What prompt do you use?

**Comment by fallerd** [comment] 2024-12-02 18:36
Possibly resolved - TLDR for those who want the problem to go away: delete your workspaceStorage cache to fix.

@jrieken further information below:

> Can you try with an empty profile? 

Tested by creating a new temporary profile and then installing only the copilot extensions in this. If I use this profile in a new blank directory/workspace, it does not create the empty files. However, if I use this temporary profile in my main workspace, it does create the files. So it seems workspace related and not profile related.

I did further testing and noted that, even while using my default profile, the extraneous file creation does not occur in any of my other typical workspaces, meaning it is only related to my primary workspace (the oldest and most used one on my machine). Because of this, I figured I would look at the workspace cache. I looked in `/Users/<Username>/Library/Application Support/Code/User/workspaceStorage` and identified the directory related to my primary workspace. Inside of this was a directory named `GitHub.copilot-chat`, with a single file inside of it named `workspaceEmbeddingsCache-text-embedding-3-small512.json`. I cut/pasted this directory & file out of the workspace storage and re-opened this workspace - now I no longer can recreate the extraneous file spawning.

I attempted to paste this directory back into the workspace folder where it originally was found to see if the problem came back, but it did not. So, not exactly a concrete cause, but it seems like the workspace cache was corrupted in some fashion since removing this dir/file was the only change I made at the time which caused the problem to disappear.

> What prompt do you use?

Well, before I just seem to have fixed it, any prompt at all. For example, a prompt related to a line in an open code file or just nonsensically prompting "test" will cause the files to be created.

**Comment by jrieken** [comment] 2024-12-03 08:13
@mjbvz @TylerLeonhardt does `workspaceEmbeddingsCache-text-embedding-3-small512.json` ring a bell for you?

**Comment by mjbvz** [comment] 2024-12-03 17:23
Yes that's an internal state file for the workspace. I don't know any flow that could cause it to affect the user's opened editors as we only use the fs apis for interacting with it

**Comment by vvolodin** [comment] 2024-12-07 23:48
any timeline for this? this is very annoying...

**Comment by TylerLeonhardt** [comment] 2024-12-18 22:08
@vvolodin can you try the above steps and see if that fixes it for you? https://github.com/microsoft/vscode-copilot-release/issues/2699#issuecomment-2512389272

**Closed** 2024-12-26 15:29 UTC
Labels: info-needed
