### ISSUE TITLE
@workspace doesn't work

### ISSUE THREAD

**Issue by ianbruton** [microsoft/vscode-copilot-release#726] opened 2024-01-08 15:44 UTC
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by digitarald** [comment] 2024-01-23 16:24
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/618#issuecomment-1904843603

**Closed by digitarald** 2024-01-23 16:24 UTC
