### ISSUE TITLE
ERROR: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RightFS** [microsoft/vscode-copilot-release#693] opened 2023-12-20 13:20 UTC
![image](https://github.com/microsoft/vscode-copilot-release/assets/12915306/dda1d980-62b2-457c-9d92-05a0ed7c390e)

- VS Code Version: 1.85.1
- OS Version: windows 10 22H2 19045.3758
- Logs:
```logs
2023-12-20 21:12:44.109 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-20 21:12:44.109 [info] [chat fetch] modelMaxTokenWindow 4096
2023-12-20 21:12:44.109 [info] [chat fetch] chat model gpt-4
2023-12-20 21:12:49.636 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 5526 ms
2023-12-20 21:12:51.523 [info] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-20 21:12:51.523 [info] [streamChoices] request done: requestId: [e52f8d30-566a-4de1-8513-ddd51fb3d6f0] responseId: [45dd68f5-dc2a-4c90-b953-3a9c878a0e80] model deployment ID: [x74a4b0e7ace1]
2023-12-20 21:12:51.531 [info] [extension] RangeError: Maximum call stack size exceeded
    at y7 (c:\Users\xxx\.vscode\extensions\github.copilot-chat-0.11.1\dist\extension.js:508:2409)
    at c:\Users\xxx\.vscode\extensions\github.copilot-chat-0.11.1\dist\extension.js:508:4414
```
Steps to Reproduce:

I don't know how to reproduce, because it hanpend in a normal conversation and it doesn't work at all even I start a new session.

It works good again when I restart VSC.

that's all

**Comment by RightFS** [comment] 2023-12-20 15:02
AMD R9-7950X with 96GB memory, low memory load...

**Comment by bhavyaus** [comment] 2023-12-20 19:24
Closing as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/670.

**Closed by bhavyaus** 2023-12-20 19:24 UTC
Labels: triage-needed
