### ISSUE TITLE
why is copilot chat using gpt3.5 i didnt pay 20 usd to use a free version of gpt while it was promised that it will be build on top of gpt4

### ISSUE THREAD

**Issue by Am0stafa** [microsoft/vscode-copilot-release#473] opened 2023-10-11 13:18 UTC

**Comment by defineprogramming** [comment] 2023-10-15 16:59
yeah the output quality is pretty poor, for the price you pay you expect to get -4

**Comment by digitarald** [comment] 2023-10-16 17:19
Duplicate of #4

We are working on it! Please post examples of GPT-4 provides better answers than 3.5, so we can benchmark them further as part of our continuous model evaluation.

**Closed by digitarald** 2023-10-16 17:19 UTC
Labels: triage-needed
