### ISSUE TITLE
COPILOT chat" Increasingly bad - Very outdated answers and wrong suggestions everywhere

### ISSUE THREAD

**Issue by demiro** [microsoft/vscode-copilot-release#1244] opened 2024-05-25 16:18 UTC
- VS Code Version:  1.89.1

I think you are all aware about this issue, has been pointed out many times. Also no need for me to post logs, as it's always like this... and until you are going to hook live API docs for most of the libraries and languages out there, this will be a problem.

While co-pilot in code is very helpful as it copies your patterns and I love it...
I absolutely hate the chat version... 9 times out of 10 I try to use it, I am disappointed. and the main reason for it is the outdated suggestions.

I don't think it would be to hard on your side, to keep track of all the versions and check installed versions (with package.json or whatever other package manager) and suggest version specific answers and maybe suggest that users is using older version, to maybe update it....

I think this is super important feature and you need to find a way to make it reality... otherwise the feature is not worth paying extra (on top of pro chatGPT and claude)

**Comment by james-berkheimer** [comment] 2024-05-26 17:42
Just to add an anecdote of my own.  I'm currently working on a Flask app and chat kept telling me that that I had to use this one envar to put the app in debug mode.  But it wasn't working at all.  So eventually I get around to looking deeper into it and it turns out that this method was used 2 versions prior to the current Flask version.  Digging further into that, it turns out that the current models training data is from 2021.

It would be nice if the training data could be more up to date, but I don't think that is logistically possible at this point. This honestly should be something that is displayed in bold lettering for users of Copilot as it is extremely relevant.

**Comment by rs38** [comment] 2024-05-30 07:42
this is really annoying as it gives tons of wrong advices... nothing ages faster than dev stacks, so three year old Models are not helpful

Q:Are you aware of asp.net 8?

A: As of my last training data in September 2021, the latest stable release of ASP.NET is ASP.NET Core 5.0, and .NET 6.0 is in preview. ASP.NET 8 does not exist yet.

**Comment by digitarald** [comment] 2024-05-30 16:49
Duplicate of #560

**Closed by digitarald** 2024-05-30 16:49 UTC
Labels: triage-needed

**Comment by TephrosisDEV** [comment] 2024-06-17 12:22
I agree, for the given reasons, the chat version is almost unusable atm. I use it with Typescript and CoPilot keeps encouraging me to manually type everything ... It also keeps solving all my questions with `assertions`. It never suggest inference. As this should be an AI co-developer, it should suggest best-practices. Imagine all new developers using this tool and getting outdated information all the time. As this is a paid subscription, I hope this gets resolved soon.
