### ISSUE TITLE
Implement a feature to automatically generate commit messages based on commitlint.config.js file.

### ISSUE THREAD

**Issue by musuyaba** [microsoft/vscode-copilot-release#720] opened 2024-01-04 04:19 UTC
Regarding the feature, I've already found the existing functionality for conventional commit messages (covered in issue #526) to be quite beneficial. However, I suggest enhancing the process by incorporating a feature that reads commitlint.config or any rule-containing file to generate commit messages directly, eliminating the need for a pre-prompt step.

For more information, you can visit: https://commitlint.js.org/

Thank you.

**Comment by lszomoru** [comment] 2024-12-10 10:28
Closing as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/526. See [this comment](https://github.com/microsoft/vscode-copilot-release/issues/526#issuecomment-2509017787) on how to specify custom instructions for commit message generation.

**Closed by lszomoru** 2024-12-10 10:28 UTC
Labels: feature-request, scm-commit
