### ISSUE TITLE
would it be possible for Copilot Chat to reference the currently open file?

### ISSUE THREAD

**Issue by NightmareZero** [microsoft/vscode-copilot-release#340] opened 2023-07-27 10:25 UTC
would it be possible for Copilot Chat to reference the currently open file?
for example

Could you please assist me in creating a DelUser function, with reference to the adduser.go and getuser.go files

**Comment by ulugbekna** [comment] 2023-08-17 19:22
duplicate of #14

**Closed by ulugbekna** 2023-08-17 19:22 UTC
Labels: triage-needed
