### ISSUE TITLE
github copilot doesn't work with "Language model unavailable" after upgrading the vscode version

### ISSUE THREAD

**Issue by ReycoLi** [microsoft/vscode-copilot-release#2323] opened 2024-11-06 01:26 UTC
- Copilot Chat Extension Version: v1.243.0
- VS Code Version: 1.95.1 (Universal)
- OS Version: mac 14.4.1

After I upgrade the vscode version, my whole github copilot doesn't work. It shows "Language model unavailable" and there is no chat model window on the bottom of chatbox (see screenshot)
I saw the release log that there was some new features supported for  github copilot so that's why I decided to install the new version.
Please help since I am relying on it every day work.

![Image](https://github.com/user-attachments/assets/03f70dbd-a069-44d1-8749-eab4e72860e4)

**Comment by SumitNandi-eaton** [comment] 2024-11-06 06:49
duplicate of #2116

**Comment by lramos15** [comment] 2024-11-06 13:45
Please read the duplicate issue it contains a lot of helpful fixes.

**Closed by lramos15** 2024-11-06 13:45 UTC
Labels: triage-needed
