### ISSUE TITLE
why  new Chat icon not appears in the activity panel?

### ISSUE THREAD

**Issue by swapnmohite** [microsoft/vscode-copilot-release#102] opened 2023-05-24 07:37 UTC

**Comment by icantrank** [comment] 2023-05-24 09:22
install extension 'github copilot chat' from insiders, after installing 'github copilot nightly'.

wasted an hour on this this morning 😅 glhf

**Comment by swapnmohite** [comment] 2023-05-24 09:32
Still not showing the chat icon

**Comment by RogerBarreto** [comment] 2023-05-24 12:14
The Icon don't show when the chat is attached to the sidebar, check if your Chat is attached to the sidebar (left or right)

![CopilotMovingChats](https://github.com/microsoft/vscode-copilot-release/assets/19890735/7e8eb28d-51f3-4fa9-8e56-2486997bc4f9)

**Comment by Lbyn96** [comment] 2023-05-24 12:25
You need to install Visual Studio Code - Insiders and use Visual Studio Code - Insiders in order to see it.

**Comment by StefanoBisio** [comment] 2023-05-25 01:01
Same here.
On M1 MacOS Monterey

1. fresh installation of Visual Studio Code Insiders (Mac Universal) (also tried silicon version, same result)
2. install Copilot Nightly 
3. Get prompted to log into github
4. Logs in successfully
5. Go into Extensions to install Copilot Chat
6. Copilot Chat is already installed alongside Copilot Nightly.
7. No chat icon appears on the side

Also unable to uninstall Copilot Chat, as it just spawns right back.

**Comment by digitarald** [comment] 2023-06-03 02:13
If this still happens please post the VS Code _Output_ logs for `GitHub Copilot Chat` and `GitHub Copilot`.

**Comment by nsteblay** [comment] 2023-06-11 15:10
I'm having the same issue.  Is there a specific configuration that should be used?

**Comment by chinchillajared** [comment] 2023-06-12 03:52
How can we get logs? I don't see any option to get the log files and there are no instructions.

**Comment by chinchillajared** [comment] 2023-06-12 04:33
Well, I think I just found one way to fix it.

Uploading lesson8 - Visual Studio Code - Insiders 2023-06-11 22-23-25.mp4…

**Comment by chinchillajared** [comment] 2023-06-12 04:57
I just found a workaround to fix it, here is a video: https://youtu.be/rF-Y0DuvE2o

**Comment by philippjbauer** [comment] 2023-06-12 14:43
> I just found a workaround to fix it, here is a video: https://youtu.be/rF-Y0DuvE2o

This has helped me, thank you! My chat window disappeared into a totally unrelated extension window. No wonder I couldn't find it.

**Comment by digitarald** [comment] 2023-06-12 15:43
In case others loose the UI or forgot where the panel went, the view can also be triggered via a command:

**`> Chat: Focus on GitHub Copilot View`**:

<img width="745" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/aa422cb1-e34d-458a-9d40-f2e14a7554ce">

If Chat is in the right sidebar, make sure to enable Layout Controls by right-clicking the title bar:

<img width="332" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/5aea00b1-c42c-4fd3-b608-03c2a651ebf8">

**Comment by digitarald** [comment] 2023-09-29 03:18
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/316#issuecomment-1739722874

**Closed** 2023-09-29 16:11 UTC
Labels: panel-chat, info-needed
