### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by egzon-baruti** [microsoft/vscode-copilot-release#829] opened 2024-02-02 18:21 UTC
It stopped working and throws error: Cannot read properties of undefined (reading 'split')

- VS Code Version:1.86.0
- OS Version:Mac
- Logs:

Steps to Reproduce:

1.
2.

**Comment by Krankenkasse** [comment] 2024-02-02 19:45
Getting same error on the secound question in every session. `Cannot read properties of undefined (reading 'split')`

VS Code Version 
> Version: 1.86.0 (user setup)
> Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
> Date: 2024-01-31T10:28:19.990Z
> Electron: 27.2.3
> ElectronBuildId: 26495564
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Windows_NT x64 10.0.19045

Copilot Chat Version 0.12.0
Copilot Version v1.156.0

logs:
`2024-02-02 20:41:51.752 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (/root/.vscode-server/extensions/github.copilot-chat-0.11.1/dist/extension.js:1251:85)
    at /root/.vscode-server/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5254
    at Array.map (<anonymous>)
    at t.logMessages (/root/.vscode-server/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5183)
    at n1._provideResponseWithProgress (/root/.vscode-server/extensions/github.copilot-chat-0.11.1/dist/extension.js:1256:1173)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at n1.provideResponseWithProgress (/root/.vscode-server/extensions/github.copilot-chat-0.11.1/dist/extension.js:1254:2086)
    at i.y (/root/.vscode-server/extensions/github.copilot-chat-0.11.1/dist/extension.js:1266:1022)
    at o.$invokeAgent (/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/out/vs/workbench/api/node/extensionHostProcess.js:150:40137)`

**Comment by kristjem** [comment] 2024-02-03 08:09
Can confirm that restarting VS Code solved the issue for me. 

```
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by mahboud** [comment] 2024-02-03 10:36
Restarting VSCode is a temporary solution. I invariably get into the same state where I get: 
`Cannot read properties of undefined (reading 'split')`
After the first successful message, and as a reponse to the second message, in the chat.

**Comment by digitarald** [comment] 2024-02-03 17:29
For explanation, the logs show the old version is still running while the new version was waiting for a restart:

![image](https://github.com/microsoft/vscode-copilot-release/assets/8599/9b7b9b04-5aa0-4ff9-a489-0de822c3aeab)

Double-check you have **VS Code 1.86** and Copilot Chat **0.12** and there are no blue notification dots for _Restart to update_!

**Comment by digitarald** [comment] 2024-02-03 17:55
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/796#issuecomment-1925413610

**Closed by digitarald** 2024-02-03 17:55 UTC
Labels: triage-needed
