### ISSUE TITLE
Github Copilot Chat

### ISSUE THREAD

**Issue by sdaly-designer** [microsoft/vscode-copilot-release#388] opened 2023-09-05 16:13 UTC
Type: <b>Bug</b>

Hello,
The github copilot Chat does not work on my computer for some reason, can you make an suggestions?

Thank you!

SD

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (1.33GB free)|
|Process Argv|--crash-reporter-id fb85bb54-e806-498a-9c80-7393a2ef4046|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.9.5
engine-builder|bou|0.0.7
phpserver|bra|3.0.2
gitlens|eam|14.2.1
prettier-vscode|esb|10.1.0
codespaces|Git|1.15.0
copilot|Git|1.108.384
copilot-chat|Git|0.7.2023081101
copilot-labs|Git|0.15.1019
remotehub|Git|0.60.0
vscode-pull-request-github|Git|0.70.0
live-sass|gle|6.1.1
rainbow-csv|mec|3.7.0
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.26.0
black-formatter|ms-|2023.4.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.50
jupyter|ms-|2023.7.1002162226
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
azure-repos|ms-|0.36.0
live-server|ms-|0.4.9
remote-repositories|ms-|0.38.1
vetur|oct|0.37.3
format-html-in-php|rif|1.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
vscode-scss-formatter|sib|3.0.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.33.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by rahulballer** [comment] 2023-09-07 17:10
hey! i'm having the same issue as well: Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (4 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

I just signed up for copilot, and i can't see the icon anywhere (even though i activated in my settings on github.com)

**Comment by wangduoyuuu** [comment] 2023-09-17 11:36
Same issue for can not see the Github Copilot Chat icon.
Tried to install and uninstall many times. Issue still existing here. Thanks.

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.5.0

**Comment by wweevv-johndpope** [comment] 2023-09-28 02:05
https://github.com/orgs/community/discussions/68463

**Comment by digitarald** [comment] 2023-09-29 03:19
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/316#issuecomment-1739722874

**Closed by digitarald** 2023-09-29 03:19 UTC
Labels: triage-needed
