### ISSUE TITLE
Reached limit

### ISSUE THREAD

**Issue by spatialvlad** [microsoft/vscode-copilot-release#2764] opened 2024-11-21 13:23 UTC
Type: <b>Bug</b>

Unfortunately I frequently reach limit of code generatino when doing refactoring, especially multi-file ones.
It would be great if the limit was 2-3 times bigger. 
But as a temporary solution it might be good not to automatically discard the proposed generations. E.g. My request might require changes in 5 files. First 4 are generated correctly, and then I get the limit on 5th and lose all progress. It would be helpful to retain the ones that have been finished, so that I could save the progress and move on the file that fails.

Extension version: 0.23.2024102903
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id c3386d12-2f4b-40cc-9071-3bf4bd05e3f9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joyceerhl** [comment] 2024-11-21 15:11
> automatically discard the proposed generations

We've fixed this in Insiders (https://code.visualstudio.com/insiders). It'll come to the next Stable in early December

**Comment by joyceerhl** [comment] 2024-12-09 18:34
Closing the limit increase request aspect of this issue as a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/2769

**Closed by joyceerhl** 2024-12-09 18:34 UTC
Labels: triage-needed
