### ISSUE TITLE
no responding

### ISSUE THREAD

**Issue by Pinkish-Warrior** [microsoft/vscode-copilot-release#1738] opened 2024-10-06 15:39 UTC
Type: <b>Bug</b>

when it does the answer disapear before finishing it

Extension version: 0.22.2024100401
VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 23, 19|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 70e2fc83-bd2c-4547-b205-1208d6c718c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
cc771715:31146322

```

</details>

**Comment by ReedGraff** [comment] 2024-10-06 17:04
Duplicate: https://github.com/microsoft/vscode-copilot-release/issues/1723#issue-2568313295

**Comment by andreamah** [comment] 2024-10-07 15:45
/duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1723#issue-2568313295

**Closed by andreamah** 2024-10-07 15:45 UTC
Labels: triage-needed
