### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-copilot-release#1494] opened 2024-08-23 12:51 UTC
> I am already logged in to Github copilot, still its not showing me the chat section and asking that I should sign in and when I am trying to that the sign in button is not working
> 
> ![github copilot issue](https://github.com/user-attachments/assets/c507a3f3-99a4-44f2-a405-54681fc5ff9c)
> 
> 
> 
> 
> 
>   

 _Originally posted by @Khan-Kaleem in [#1439](https://github.com/microsoft/vscode-copilot-release/issues/1439#issuecomment-2307004768)_

**Comment by TylerLeonhardt** [comment] 2024-08-23 17:00
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2278793021

**Closed by TylerLeonhardt** 2024-08-23 17:00 UTC
