### ISSUE TITLE
Sign in with GitHub to use Copilot, your AI pair programmer keeps showing. 

### ISSUE THREAD

**Issue by infinityiz** [microsoft/vscode-copilot-release#1478] opened 2024-08-15 05:20 UTC
- Copilot Chat Extension Version: v0.18.2
- VS Code Version: 1.92.1
- OS Version: Windows 
- Logs:

Steps to Reproduce:

1. Sign in with GitHub to use Copilot, your AI pair programmer 
2. Extension wants to sign in pop up showing. 
3. Allow clicked and edge opens and then closes and returns to vs code. 
4. I restart vs code and see the chat window. 
5. I cannot click on send.

**Comment by transverberator** [comment] 2024-08-15 17:00
I'm also facing this issue. I've tried all standard troubleshooting including restarting, sign out/in, revoking and re-authorizing in GitHub, reinstalling extension, rolling back to 0.18.1 (chat had worked for me in that version previously), but none of these resolve the issue. My work computer (separate account) does not face this problem. 
It seems like the text completion co-pilot works, and the account shows as singed-in in the accounts list; however, copilot chat will only ever prompt to "Sign In" and does not function. The Ctrl+I keyboard shortcut for inline prompt also does not work.

**Comment by TylerLeonhardt** [comment] 2024-08-16 05:45
Hi, can you follow these steps and let me know how it goes?
https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2278793021

**Comment by ramseyfeng** [comment] 2024-08-19 07:17
run into to the same issue on vscode, sign in on github does not work.

**Comment by transverberator** [comment] 2024-08-23 04:17
This fixed it for me, thank you. Looking at the comment listed, in relevant part: 
> What's odd here is that preferredAccount shouldn't ever be an email address, but instead your username (or empty).
Mine had my email address, changing it to my GH username fixed the issue.

**Comment by TylerLeonhardt** [comment] 2024-08-23 17:03
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2278793021

**Closed by TylerLeonhardt** 2024-08-23 17:03 UTC
Labels: info-needed
