### ISSUE TITLE
Copilot Chat icon does not show.

### ISSUE THREAD

**Issue by sanda16** [microsoft/vscode-copilot-release#382] opened 2023-08-27 10:34 UTC
Hey my copilot chat icon does not show, i have tried to all three steps from the email and it still doesn't show the icon, what could possibly be wrong?

**Comment by razanalharith** [comment] 2023-09-04 05:40
same thing here

**Comment by vdidhisingam** [comment] 2023-09-13 21:19
same thing here

**Comment by wweevv-johndpope** [comment] 2023-09-28 02:05
https://github.com/orgs/community/discussions/68463

**Comment by digitarald** [comment] 2023-09-29 17:32
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/436

**Closed by digitarald** 2023-09-29 17:32 UTC
Labels: triage-needed
