### ISSUE TITLE
Cannot read properties of undefined (reading 'matchAll')

### ISSUE THREAD

**Issue by JTran-IDM** [microsoft/vscode-copilot-release#2726] opened 2024-11-20 01:00 UTC
Type: <b>Bug</b>

Issues with using @workspace in VSCode Insiders and pre-release Copilot Chat

Extension version: 0.23.2024111902
VS Code version: Code - Insiders 1.96.0-insider (91bf2f3b96a337c05fdd30dbfe609ae780b74706, 2024-11-19T05:04:26.087Z)
OS version: Darwin arm64 24.1.0
Modes:
Remote OS version: Linux x64 6.5.0-1025-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 6, 6|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: opulent space robot|
|OS|Linux x64 6.5.0-1025-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (4 x 0)|
|Memory (System)|15.61GB (6.87GB free)|
|VM|0%|
</details>

**Comment by mjbvz** [comment] 2024-11-20 19:54
Duplicate of #2204

However please share the full error stack so we can investigate this further. The latest insiders builds of chat catch and suppress the error but I want to track down the root cause

**Closed by mjbvz** 2024-11-20 19:54 UTC
Labels: info-needed
