### ISSUE TITLE
PHP tags included with paste 

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#1104] opened 2024-04-05 16:22 UTC
Recently when I copy code or use paste inline the <?php and close tags are included in my paste. This is a very nit picky bug report, but it slows down development and is new behavior. 

- VS Code Version: 1.88.0-insider (Universal)
- OS Version: Soma 14.4.1 (23E224)

Steps to Reproduce:

1. copy code from chat window using either the copy button or the copy-inline button
 Expected results would be that the code is copied without including the PHP tags. 
 Actual results are that the tags are included in the paste. 
 
 Note: when copying large full solutions sometimes those tags are necessary but most of the time they need to be removed

**Comment by binaryfire** [comment] 2024-04-06 08:22
Has there been a recent update that tries to address this? I agree it's a good idea, but PHP code highlighting is now broken: https://github.com/microsoft/vscode-copilot-release/issues/1107

**Comment by roblourens** [comment] 2024-04-09 03:50
Can you explain a little more? I don't follow

**Comment by binaryfire** [comment] 2024-04-10 02:41
@roblourens Posting this here, since my other issue was closed without any further discussion. So frustrating!

![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/805a56ef-2a58-4176-b887-b3866f8b0946)

**Comment by Bartosh-s** [comment] 2024-05-02 16:46
+1

**Comment by msolla-ligno** [comment] 2024-05-13 08:04
Same here.
the hilighting in chat is broken:
![imagen](https://github.com/microsoft/vscode-copilot-release/assets/126880127/4f2a3720-7640-4152-ade0-bd7a30d566ba)

and then, when using copy or insert at cursor buttons adds innecesary <?php ?> tags that broke the code:
![imagen](https://github.com/microsoft/vscode-copilot-release/assets/126880127/bc5bdaec-dbaf-44f6-863d-4abc4b1a3cac)

That bug appeared some weeks ago

**Comment by binaryfire** [comment] 2024-05-13 08:07
Hi @msolla-ligno. There's a separate issue open for PHP highlighting in chat. Could you post your highlighting example there?

https://github.com/microsoft/vscode-copilot-release/issues/1107

**Comment by msolla-ligno** [comment] 2024-05-13 08:09
@binaryfire ok, I will post this there, but I posted it for more context. The main problem for me is the tags that brokes the code.

**Comment by klejvi33** [comment] 2024-05-15 06:47
Same problem. Has there been any workaround yet? 

It always inserts a <?php
![image](https://github.com/microsoft/vscode-copilot-release/assets/121438708/55db2963-4ec7-4c56-8b10-26e76fc5d529)

This happens only when using "Copy" and "Insert at Cursor":
![image](https://github.com/microsoft/vscode-copilot-release/assets/121438708/ec2015a8-9f6c-4bdc-a465-cdca964f0038)
 
But it doesn't happen if you copy paste manually

**Comment by isidorn** [comment] 2024-12-10 18:50
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If yes, can you provide reproducible steps. Until then I will go ahead and close this issue.
Thank you for your understanding

**Closed by isidorn** 2024-12-10 18:50 UTC
Labels: panel-chat, feature-request
