### ISSUE TITLE
Clarifying AI Assistant Capabilities: Limited Code Access

### ISSUE THREAD

**Issue by Grillogato** [microsoft/vscode-copilot-release#1246] opened 2024-05-25 19:29 UTC
I would like to request an enhancement to the AI assistant's code access functionality. Currently, the assistant indicates that it does not have full access to the code, which can cause confusion and limit the assistance provided.

**Comment by fisforfaheem** [comment] 2024-05-28 22:11
Agree which is frustating

**Comment by digitarald** [comment] 2024-06-25 00:25
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1083

**Closed by digitarald** 2024-06-25 00:25 UTC
Labels: triage-needed
