### ISSUE TITLE
Blank response after requesting @workspace /explain command in Codespace for nodejs/node

### ISSUE THREAD

**Issue by github-is-fun-to-use** [microsoft/vscode-copilot-release#1825] opened 2024-10-11 14:13 UTC
ADD ISSUE DESCRIPTION HERE

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

Extension version: 0.21.1

![Image](https://github.com/user-attachments/assets/cb2388eb-66e8-4926-aaab-3dc21b45b2a6)

**Comment by mjbvz** [comment] 2024-10-22 23:43
I believe this is a duplicate of #1723 which should have already been fixed. Let me know if you're still seeing this on the latest versions

**Closed by mjbvz** 2024-10-22 23:43 UTC
Labels: triage-needed
