### ISSUE TITLE
Copilot Chat Icon not appearing in activity bar

### ISSUE THREAD

**Issue by kaianuar** [microsoft/vscode-copilot-release#449] opened 2023-10-04 11:33 UTC
- VS Code Version: 1.82.3
- OS Version: Linux Mint 21.2

Steps to Reproduce:

1. Install both Copilot and Copilot Chat extensions
2. Chat Icon not appearing in activity bar

Output of Github Authentication

```
2023-10-04 19:23:57.347 [info] Reading sessions from keychain...
2023-10-04 19:23:57.347 [info] Getting sessions for all scopes...
2023-10-04 19:23:57.370 [info] Getting sessions for read:user,repo,user:email,workflow...
2023-10-04 19:23:57.403 [info] Getting sessions for all scopes...
2023-10-04 19:23:57.771 [trace] Token acquired from secret storage.
2023-10-04 19:23:57.771 [info] Got stored sessions!
2023-10-04 19:23:57.771 [trace] Read the following session from the keychain with the following scopes: user:email
2023-10-04 19:23:57.771 [info] Got 1 verified sessions.
2023-10-04 19:23:57.771 [info] Got 1 sessions for ...
2023-10-04 19:23:57.772 [info] Got 0 sessions for read:user,repo,user:email,workflow...
2023-10-04 19:23:57.772 [info] Got 1 sessions for ...
2023-10-04 19:23:57.977 [info] Getting sessions for all scopes...
2023-10-04 19:23:57.977 [info] Got 1 sessions for ...
2023-10-04 19:23:58.122 [info] Getting sessions for user:email...
2023-10-04 19:23:58.122 [info] Got 1 sessions for user:email...
2023-10-04 19:23:58.199 [info] Getting sessions for all scopes...
2023-10-04 19:23:58.199 [info] Got 1 sessions for ...
2023-10-04 19:24:03.539 [info] Getting sessions for all scopes...
2023-10-04 19:24:03.539 [info] Got 1 sessions for ...
2023-10-04 19:24:03.547 [info] Getting sessions for read:user...
2023-10-04 19:24:03.547 [info] Got 0 sessions for read:user...
2023-10-04 19:24:03.584 [info] Getting sessions for user:email...
2023-10-04 19:24:03.584 [info] Got 1 sessions for user:email...
2023-10-04 19:24:03.589 [info] Getting sessions for user:email...
2023-10-04 19:24:03.589 [info] Got 1 sessions for user:email...
2023-10-04 19:24:03.769 [info] Getting sessions for read:user,repo,user:email...
2023-10-04 19:24:03.769 [info] Got 0 sessions for read:user,repo,user:email...
2023-10-04 19:24:04.223 [info] Getting sessions for user:email...
2023-10-04 19:24:04.223 [info] Got 1 sessions for user:email...
```

Output of Gitub Copilot Chat
```
2023-10-04T11:24:03.588Z [INFO] [auth] Logged in as kaianuar
2023-10-04T11:24:04.200Z [INFO] [chat] copilot token chat_enabled: false
2023-10-04T11:24:04.200Z [INFO] [auth] Got Copilot token for kaianuar
```

**Comment by ulugbekna** [comment] 2023-10-04 13:46
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/436

**Closed by ulugbekna** 2023-10-04 13:46 UTC
Labels: triage-needed
