### ISSUE TITLE
"Fix this" code action is streaming responses and incorrectly fixing issues.

### ISSUE THREAD

**Issue by shism2** [microsoft/vscode-copilot-release#499] opened 2023-10-21 00:14 UTC
- VS Code Version: 1.84
- OS Version:Edition Windows 11 Home
Version	23H2
Installed on	‎9/‎11/‎2023.
OS build	22635.2486
Experience	Windows Feature Experience Pack 1000.22678.1000.0

Issue:

"Fix This" code action is streaming the changes to the code editor and incorrectly solving or fixing anything. It does not fix any issue or code any longer. I'm sure other people are seeing this. This seems like a super critical issue...

Steps to reproduce:

1. right click on any underlined issue in vscode ide for example a python file.

When I select an issue in the code editor such as: 

"Cannot access member "stop_words" for type "PDFConverter"
  Member "stop_words" is unknownPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
[Codeium: Explain Problem](vscode-file://vscode-app/d:/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

(function) stop_words: Unknown".

2. Select "Fix This"

**Comment by aiday-mar** [comment] 2023-10-21 07:34
Hey @jrieken I wonder if there is a setting to turn off streaming of responses from inline chat?

@shism2 thank you for filing the issue. Since Copilot results are non deterministic (random), could you include here a copy paste or a GIF of the code before, the issue and the incorrect code after? We will look into why the fix fails.

**Comment by jrieken** [comment] 2023-10-23 07:46
@aiday-mar Streaming is not enabled for /fix. I guess this iterative fixing or a misinterpretation

**Comment by aiday-mar** [comment] 2023-10-26 10:37
Hi @shism2 the gif is very blurry. Could you add one with higher resolution? If you update to the latests copilot chat release do you still see this?

**Comment by aiday-mar** [comment] 2023-10-26 13:26
According to what @jrieken mentioned, the response should not be streamed for /fix. Are you on the the latest copilot-chat extension? If you do see streaming, could you let us know by posting a gif with a higher resolution? Thank you.

**Comment by aiday-mar** [comment] 2023-12-04 15:31
Hi could you please post the output you see under `Github Copilot Chat` in the output view, as well as what you would expect as a result?

**Comment by aiday-mar** [comment] 2023-12-05 07:53
Hi @shism2 thank you for letting us know. If the problem is fixed, then I will close this issue.

**Closed by aiday-mar** 2023-12-05 07:53 UTC
Labels: info-needed, /fix
