### ISSUE TITLE
Outdated Copilot for Go code suggestions

### ISSUE THREAD

**Issue by Perusae** [microsoft/vscode-copilot-release#993] opened 2024-03-04 00:02 UTC
Request information to use Go slices.contains function (go 1.21). Keeps suggestion outdated code. Push copilot a bit and we get:

> I apologize for the confusion. As of my last update, the latest stable version of Go is 1.17, and it does not include a `slices` package in the standard library. If Go 1.21 has introduced a `slices` package with a `Contains` function, I'm currently not updated to provide information or examples on it. I recommend referring to the official Go documentation or other reliable resources for the most accurate and up-to-date information.

Go **1.17 is from Aug 16, 2021**  ... Go **1.22 (latest) is from Feb 6, 2024**

There is a 3 year gap in information, resulting in outdated suggestions and checks.

**Comment by digitarald** [comment] 2024-03-08 01:46
Duplicate of #560, needs a newer model with more recent knowledge cutoff.

**Closed by digitarald** 2024-03-08 01:46 UTC
