### ISSUE TITLE
ENOENT: no such file or directory - commandEmbeddings.json

### ISSUE THREAD

**Issue by ahosker** [microsoft/vscode-copilot-release#30] opened 2023-05-18 12:28 UTC
- VS Code Version: 1.79.0-insider
- OS Version: win 11
- Logs:

Steps to Reproduce:
![image](https://github.com/microsoft/vscode-copilot-release/assets/346166/2d3ef58e-f33b-4f49-92ac-88d771b75ea1)

**Comment by sergeyk** [comment] 2023-05-19 05:20
Same here

![CleanShot 2023-05-18 at 22 19 27@2x](https://github.com/microsoft/vscode-copilot-release/assets/4881/27b304c0-a652-4864-8c2d-17a51122be79)

**Comment by JustScriptin** [comment] 2023-05-20 03:06
![Screenshot 2023-05-19 224641](https://github.com/microsoft/vscode-copilot-release/assets/73454652/4248b636-a577-474f-993d-6cf51bfa2732)

Same thing here. I see people saying they made the file. However, if you clean install you will notice that the file is never actually missing. It's always there. I'm guessing it's an issue with parsing the path and in some instances finding the correct path, because when I see everyone else's error messages, it seems that they are unconventional paths or Windows. This is not the only extension that has issues parsing Windows paths I fixed an issue with copilot-cli by using double backslash syntax for windows paths.

**Comment by JustScriptin** [comment] 2023-05-20 03:08
> 

Yea it seems that you can clean install but the chat history is not stored locally. so it appears like its not uninstalling fully

**Comment by JustScriptin** [comment] 2023-05-20 03:08
@jamespacileo Yea it seems that you can clean install but the chat history is not stored locally. so it appears like its not uninstalling fully

**Comment by jpenalbae** [comment] 2023-05-20 17:36
Same problem here. These two also seem related #59 and #51

**Comment by wojtodzio** [comment] 2023-05-20 18:26
Same here on macOS, though the message for me starts with "Unable to delete nonexistent file 'vscode-userdata:"

**Comment by adriencaccia** [comment] 2023-05-23 08:21
I managed to work around this error by doing the following, on macOS:

1. Run the following commands to create the missing files:
```shell
touch ~/Library/Application\ Support/Code\ -\ Insiders/User/globalStorage/github.copilot-chat/commandEmbeddings.json
touch ~/Library/Application\ Support/Code\ -\ Insiders/User/globalStorage/github.copilot-chat/settingEmbeddings.json
```

2. Reload VS Code Insiders
3. `/vscode ...` should now work

**Comment by jpenalbae** [comment] 2023-05-23 09:29
This fixed works. Thanks @adriencaccia

**Comment by AlainDevs** [comment] 2023-05-23 19:13
Thanks @adriencaccia , it works on Windows 10 too, just need to create two files commandEmbeddings.json and settingEmbeddings.json under C:\Users\user\AppData\Roaming\Code - Insiders\User\globalStorage\github.copilot-chat

**Comment by vbrozik** [comment] 2023-05-24 09:57
I have the same problem. The issues #51 and #59 seem to be the same problem just with slightly different error messages because of differences between platforms. Can you please mark them as duplicates?

All seem to be caused by missing files `commandEmbeddings.json` or `settingEmbeddings.json` inside a directory `Code - Insiders/User/globalStorage/github.copilot-chat` inside an user's application data directory.

In my case (VS Code on Windows 10, GitHub remote repository) the message after asking "/vscode anything" is:

> Unable to delete nonexistent file 'vscode-userdata:/c:/Users/vaclav.brozik/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/commandEmbeddings.json'

Is the first part of the "path" `vscode-userdata:/` something that should work in VS Code or is this a bug? Also is `c:` in a Unix-style path (slashes, not backslashes) correct too?

```
Version: 1.79.0-insider (user setup)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:18:53.811Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

Name: GitHub Copilot Nightly
Id: GitHub.copilot-nightly
Description: Your AI pair programmer
Version: 1.86.114
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-nightly

Name: GitHub Copilot Chat
Id: GitHub.copilot-chat
Description: AI chat features powered by Copilot
Version: 0.1.2023052205
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat
```

**Comment by ansh-les** [comment] 2023-05-25 02:14
+1 Same issue

**Comment by BaoziCDR** [comment] 2023-05-25 06:29
> I managed to work around this error by doing the following, on macOS:
> 
> 1. Run the following commands to create the missing files:
> 
> ```shell
> touch ~/Library/Application\ Support/Code\ -\ Insiders/User/globalStorage/github.copilot-chat/commandEmbeddings.json
> touch ~/Library/Application\ Support/Code\ -\ Insiders/User/globalStorage/github.copilot-chat/settingEmbeddings.json
> ```
> 
> 2. Reload VS Code Insiders
> 3. `/vscode ...` should now work

That is greate work.My Vscode will not have this error anymore.
But **a new problem** arises: 
- I'm stuck on `Indexing, this should only happen once...` and it never goes away even after half an hour.
<img width="249" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/44897251/f295ac12-7f4a-402d-8557-8609faee4211">

**Comment by digitarald** [comment] 2023-06-01 15:02
Dupe of #59 and fixed.

**Closed by digitarald** 2023-06-01 15:02 UTC
Labels: bug, chat-context
