### ISSUE TITLE
Using @workspace results in `(intermediate value)(intermediate value)(intermediate value)?.map is not a function`

### ISSUE THREAD

**Issue by LiChiaTing** [microsoft/vscode-copilot-release#2493] opened 2024-11-11 19:27 UTC
Type: <b>Bug</b>

(intermediate value)(intermediate value)(intermediate value)?.map is not a function

Extension version: 0.22.2
VS Code version: Code - Insiders 1.96.0-insider (9b365cafae763d229e999f353831458761aff1cd, 2024-11-11T05:05:11.976Z)
OS version: Darwin arm64 24.1.0
Modes:
Remote OS version: Linux x64 6.5.0-1025-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id f736c1c6-efb9-4ad3-ad35-0b854e6a0d89|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: orange cod|
|OS|Linux x64 6.5.0-1025-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (4 x 0)|
|Memory (System)|15.61GB (7.30GB free)|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment] 2024-11-12 04:01
@LiChiaTing where do you see this?

Can you open the Output pane (ctrl+shift+u) and click the drop down on the right and try selecting:
* Window
* Extension Host
* GitHub Copilot
* GitHub Copilot Chat
and see if you see the error with more info in there

**Comment by mengld** [comment] 2024-11-13 12:26
@TylerLeonhardt I encountered the same problem
These are my copilot chat outputs：
```
2024-11-13 20:25:47.301 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
    at F0.z (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:48522)
    at F0.findFiles2 (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:109:48394)
    at Object.findFiles2 (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:51072)
    at Xk.findFiles (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1109:20945)
    at Xk._findFilesWithDefaultExcludesAndExcludes (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:408:11503)
    at Xk.findFilesWithDefaultExcludes (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:408:11199)
    at eR.addWorkspace (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1111:10272)
    at /Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1111:9877
    at eR.init (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1111:9894)
    at /Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1817:4566
    at n.invokeFunction (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:276:941)
    at QHe (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1817:4537)
    at qPt (/Users/mengld/.vscode-insiders/extensions/github.copilot-chat-0.22.2/dist/extension.js:1817:3867)
    at Function.kb (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:15216)
    at Function.jb (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14923)
    at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:13081
    at z0.n (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4450)
    at z0.m (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4413)
    at z0.l (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:3869)
```

**Comment by Sylicium** [comment] 2024-11-13 21:05
I encouter the same problem, perhaps it is linked with **VSCode Insider** version ?
However i don't see where i can find the error stack, i only have this error: 
```js
(intermediate value)(intermediate value)(intermediate value)?.map is not a function
```

**Comment by TylerLeonhardt** [comment] 2024-11-13 22:44
@mjbvz giving this to you to see if this is maybe a codesearch bug, but I have a feeling this is a search bug...

**Comment by lukemurraynz** [comment] 2024-11-21 04:24
I have the same issue as well, within a Codespace, and using @workspace.

**Comment by jishida0620** [comment] 2024-11-29 08:13
I found the same error when using copilot on VSC insider
As a makeshift solution, I downloaded VSC stable version and solved this error.

**Comment by omerson-cruz** [comment] 2024-12-04 16:06
Also using VS Code insiders and the same issue happens to me. But when using VS code stable it is working

**Comment by Eldrick19** [comment] 2024-12-09 21:18
Same here: 

![Image](https://github.com/user-attachments/assets/0d5637dc-b56d-428c-9f07-71a1574f4c3c)

Logs:

````
[error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
	at V0.z (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
	at V0.findFiles2 (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
	at Object.findFiles2 (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
	at Xk.findFiles (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1109:20945)
	at Xk._findFilesWithDefaultExcludesAndExcludes (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:408:11503)
	at Xk.findFilesWithDefaultExcludes (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:408:11199)
	at eR.addWorkspace (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1111:10272)
	at /home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1111:9877
	at eR.init (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1111:9894)
	at /home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1817:4566
	at n.invokeFunction (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:276:941)
	at QHe (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1817:4537)
	at qPt (/home/vscode/.vscode-remote/extensions/github.copilot-chat-0.22.4/dist/extension.js:1817:3867)
	at Pw.kb (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
	at Pw.jb (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
	at file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
	at async K0.n (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (file:///vscode/bin/linux-x64/b18e7a700033b39ed2c3975759b6327c8205f958-insider/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
````

**Comment by UncleBats** [comment] 2024-12-12 08:41
Had the same experience while giving the Copilot training. 

The interesting part is that prior to this happening the agent became unresponsive, not gathering context and not output to github. I restarted VSCODE and resume the webinar. When explain chain of thought reasoning 

Asked question
```
			Create a single DevOps pipeline comprising three stages: Build, Infrastructure as Code (IaC), and Quality Assurance (QA).

			- **Task 1: Build Stage**
			- Describe the application and its architecture.
			- List the programming languages and frameworks used.
			- Outline the steps needed to compile and build the application.

			- **Task 2: IaC (Infrastructure as Code) Stage**
			- Explain what Bicep is and why it's chosen for this project.
			- Specify the Azure resources required for the application (e.g., App Service, Azure SQL Database).
			- Request the creation of Bicep templates for these resources, highlighting any dependencies between them.

			- **Task 3: QA (Quality Assurance) Stage**
			- Describe the deployment environment in Azure.
			- List the tests that need to be performed (e.g., unit tests, integration tests, UI tests).
			- Detail the steps for deploying the application to Azure for QA purposes.

			Please create a comprehensive plan for each stage, ensuring that all steps are clearly defined and logically sequenced for efficient execution.

			Let's think step by step.
```

It gave back proper results then continuing in the same context with 
```
can you generate me the yaml pipeline
```
it resulted in the error described here. This always worked in pervious sessions without any issues. Thing I noticed while grabbing the versions is that during my session the Copilot chat extension actually updated.
![Image](https://github.com/user-attachments/assets/3cdca4d2-1e56-4212-b5c1-63f021a39b6d)


Stacktrace below
```
2024-12-12 09:03:59.824 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
	at V0.z (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
	at V0.findFiles2 (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
	at Object.findFiles2 (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
	at Xk.findFiles (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1109:20945)
	at Xk._findFilesWithDefaultExcludesAndExcludes (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:408:11503)
	at Xk.findFilesWithDefaultExcludes (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:408:11199)
	at eR.addWorkspace (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1111:10272)
	at c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1111:9877
	at eR.init (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1111:9894)
	at c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1817:4566
	at n.invokeFunction (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:276:941)
	at QHe (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1817:4537)
	at qPt (c:\Users\zware\.vscode\extensions\github.copilot-chat-0.22.4\dist\extension.js:1817:3867)
	at Pw.kb (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
	at Pw.jb (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
	at file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
	at async K0.n (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (file:///c:/Users/zware/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
```

**Comment by gerardo-navarro** [comment] 2024-12-13 15:11
I am experiencing the same error since a couple of days.

Here is the log output of my GitHub Copilot Chat:
```console
2024-12-13 16:06:03.545 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
    at V0.z (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
    at V0.findFiles2 (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
    at Object.findFiles2 (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
    at ES.findFiles (/Users/user/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1109:20945)
    at ES.findFiles (/Users/user/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1759:2948)
    at Xye (/Users/user/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:408:3927)
```

**Comment by mjbvz** [comment] 2024-12-13 16:51
I added some extra logging for this in [#235692](https://github.com/microsoft/vscode/pull/235692). Could you please try  to reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) (1.97)? There may still be an error but the error message should better explain to us what is going wrong

**Comment by pamelafox** [comment] 2024-12-13 17:36
It seems to be working for me in this build, I haven't replicated an error yet.

**Comment by lukemurraynz** [comment] 2024-12-13 21:02
I can confirm, in a GitHub Codespace using Version: 1.97.0-insider - @workspace seemed to work, I attempted its use a few times!

**Comment by Xain3** [comment] 2024-12-14 18:32
I have the same issue when generating inline testings.

**CONFIG:**
Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-50-generic

**LOG**:
2024-12-14 19:23:40.355 [info] Using the Electron fetcher.
2024-12-14 19:23:40.355 [info] Initializing Git extension service.
2024-12-14 19:23:40.355 [info] Successfully activated the vscode.git extension.
2024-12-14 19:23:40.355 [info] Enablement state of the vscode.git extension: true.
2024-12-14 19:23:40.355 [info] Successfully registered Git commit message provider.
2024-12-14 19:23:53.840 [info] Using the Electron fetcher.
2024-12-14 19:23:53.840 [info] Initializing Git extension service.
2024-12-14 19:23:55.189 [info] Successfully activated the vscode.git extension.
2024-12-14 19:23:55.189 [info] Enablement state of the vscode.git extension: true.
2024-12-14 19:23:55.189 [info] Successfully registered Git commit message provider.
2024-12-14 19:23:57.026 [info] Logged in as Xain3
2024-12-14 19:23:59.716 [info] Got Copilot token for Xain3
2024-12-14 19:24:08.488 [info] Fetched model metadata in 8713ms 6eeb984c-1977-4e2b-b87d-91edf46a11de
2024-12-14 19:24:09.476 [info] activationBlocker from 'languageModelAccess' took for 14835ms
2024-12-14 19:24:12.675 [info] copilot token chat_enabled: true, sku: monthly_subscriber
2024-12-14 19:24:12.681 [info] Registering default platform agent...
2024-12-14 19:24:14.750 [info] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-12-14 19:24:14.750 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-12-14 19:24:14.750 [info] Successfully registered GitHub PR title and description provider.
2024-12-14 19:24:14.750 [info] Successfully registered GitHub PR reviewer comments provider.
2024-12-14 19:24:31.806 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
    at V0.z (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
    at V0.findFiles2 (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
    at Object.findFiles2 (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
    at PS.findFiles (/home/xain/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1118:21172)
    at PS.findFiles (/home/xain/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1768:2948)
    at d0e (/home/xain/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:348:3928)

**Comment by xwxb** [comment] 2024-12-15 06:44
The same problem, occurring frequently.

```
2024-12-15 14:43:15.031 [info] message 0 returned. finish reason: [stop]
2024-12-15 14:43:15.033 [info] request done: requestId: [52bdb572-9fa6-44bd-a9fa-f3f119771630] model deployment ID: []
2024-12-15 14:43:15.044 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
	at V0.z (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
	at V0.findFiles2 (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
	at Object.findFiles2 (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
	at Xk.findFiles (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1109:20945)
	at Xk._findFilesWithDefaultExcludesAndExcludes (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:408:11503)
	at Xk.findFilesWithDefaultExcludes (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:408:11199)
	at eR.addWorkspace (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1111:10272)
	at /Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1111:9877
	at eR.init (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1111:9894)
	at /Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1817:4566
	at n.invokeFunction (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:276:941)
	at QHe (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1817:4537)
	at qPt (/Users/mac/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1817:3867)
	at Pw.kb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
	at Pw.jb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
	at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
	at async K0.n (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
```

**Comment by ginasixt** [comment] 2024-12-16 12:41
Solved it buy restarting GitHub Copilot in Extension after an update

**Comment by nextmarte** [comment] 2024-12-16 17:15
I solved this by uninstalling GitHub Copilot and Chat, then reinstalling them.  I reloaded the workspace, closed and reopened VS Code, and now it's working fine.

**Comment by mjbvz** [comment] 2024-12-16 18:53
Anyone seeing this on insiders (1.97)? I may have already fixed this in the vscode repo but need to confirm this. If the fix did work I'll back port it to a 1.96.x release too

**Comment by eioo** [comment] 2024-12-17 07:27
Experiencing this on 1.96.0 stable, both inline chat and the regular one when trying to generate tests (`/tests`). Seems to only happen when referencing files.

![Image](https://github.com/user-attachments/assets/5646a604-aebf-4c4d-83b6-2176de8a0081)

```
Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-49-generic
```

```
2024-12-17 09:21:25.326 [info] message 0 returned. finish reason: [stop]
2024-12-17 09:21:25.326 [info] request done: requestId: [1b9c0311-fae4-49f5-a305-22f6fa4c5725] model deployment ID: []
2024-12-17 09:21:25.331 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
    at V0.z (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
    at V0.findFiles2 (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
    at Object.findFiles2 (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
    at ES.findFiles (/home/<snip>/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1109:20945)
    at ES.findFiles (/home/<snip>/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:1759:2948)
    at Xye (/home/<snip>/.vscode/extensions/github.copilot-chat-0.22.4/dist/extension.js:408:3927)
2024-12-17 09:21:25.706 [info] message 0 returned. finish reason: [stop]
2024-12-17 09:21:25.707 [info] request done: requestId: [0b0ee5fe-7c66-425b-8916-3e316a1794a4] model deployment ID: []
```

**Comment by mark-mybaggage** [comment] 2024-12-17 10:44
I'm experience the same issue when referencing a file - as mentioned by @eioo

Copilot (1.7)
Copilot Chat (0.23)

**Comment by IndefiniteBen** [comment] 2024-12-17 14:43
I encountered this on VScode stable. 
![Image](https://github.com/user-attachments/assets/af1b3157-9b3d-4bd8-a16c-622c3308391a)
For me I only get the error when it's trying to use the workspace, but **file reference is fine**. I clicked `(rerun without)`  next to Workspace and it still processed the files I input.
![Image](https://github.com/user-attachments/assets/0e4f644c-108b-4202-a202-06b55a3ac78b)

My versions:
#### Copilot
- Version: 1.252.1267
- Build: nightly
- Editor: vscode/1.96.0

**Comment by joyceerhl** [comment] 2024-12-17 18:05
Can someone please confirm that this is fixed in VS Code Insider ^1.97.0? We're porting the fix to a recovery build.

**Closed** 2024-12-17 18:04 UTC
Labels: bug, candidate

**Comment by lukemurray-datacom** [comment] 2024-12-17 18:21
> Can someone please confirm that this is fixed in VS Code Insider ^1.97.0? We're porting the fix to a recovery build.

So far, I personally haven't had the issue in 1.97.0. Used it a few times yesterday with no issue. I will retest it today and let you know if this changes (i.e., I have an issue); if I don't add another comment, assume it went well.

**Comment by lukemurraynz** [comment] 2024-12-17 18:23
> Can someone please confirm that this is fixed in VS Code Insider ^1.97.0? We're porting the fix to a recovery build.

So far, I personally haven't had the issue in 1.97.0. Used it a few times yesterday with no issue. I will retest it today and let you know if this changes (i.e., I have an issue); if I don't add another comment, assume it went well.

**Comment by j-rstange** [comment] 2024-12-18 10:33
Hi, I faced the issue for the first time today aswell using the "@workspace" command.
Went back to the stable version for Copilot extension (did not solve the problem) and Copliot chat extension (solved the problem).

```2024-12-18 11:26:57.719 [error] TypeError: (intermediate value)(intermediate value)(intermediate value)?.map is not a function
    at V0.z (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48810)
    at V0.findFiles2 (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:110:48682)
    at Object.findFiles2 (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:51419)
    at KR.findFiles (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1118:21172)
    at KR._findFilesWithDefaultExcludesAndExcludes (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:348:11504)
    at KR.findFilesWithDefaultExcludes (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:348:11200)
    at XR.addWorkspace (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1120:10272)
    at /Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1120:9877
    at XR.init (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1120:9894)
    at /Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1824:4566
    at n.invokeFunction (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:276:941)
    at ZVe (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1824:4537)
    at jPt (/Users/stangej/.vscode/extensions/github.copilot-chat-0.23.2024102903/dist/extension.js:1824:3867)
    at Function.kb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:15214)
    at Function.jb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:14921)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13079
    at K0.n (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
    at K0.m (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
    at K0.l (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)```

**Comment by charliew33** [comment] 2024-12-18 15:48
Switching the Github Copilot Chat extension to Release Version (from the Pre-Release Version) fixed this for me. I'm on Release Versions now of Copilot (1.252.0) and Copilot Chat (0.23.2024102903), working fine (VS Code v1.96.0).

**Comment by william2ai** [comment] 2024-12-18 18:38
Same error message. Restart the extension work for me. I use pre-release version as well.

**Comment by Xain3** [comment] 2024-12-19 00:26
Same
