### ISSUE TITLE
No response when asking to check a js file on cdn

### ISSUE THREAD

**Issue by mweickum** [microsoft/vscode-copilot-release#122] opened 2023-05-25 08:28 UTC
- VS Code Version: Version: 1.79.0-insider (user setup)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:18:53.811Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Win 10
- Logs:
`[INFO] [default] [2023-05-25T08:24:51.041Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-25T08:24:57.677Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 6636 ms
[ERROR] [streamChoices] [2023-05-25T08:25:51.381Z] Error parsing JSON stream data,data: {"id":"chatcmpl-7K0Z975adTtzbqd0a2oF427M0ZaMY","object":"chat.completion.chunk","created":1685003091,"model":"copilot-chat","choices":[{"index":0,"finish_reason":null,"delta":{"content<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
[ERROR] [streamChoices] [2023-05-25T08:25:51.382Z] Error parsing JSON stream data,<html>
[ERROR] [streamChoices] [2023-05-25T08:25:51.383Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.384Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.385Z] Error parsing JSON stream data,<head>
[ERROR] [streamChoices] [2023-05-25T08:25:51.385Z] Error parsing JSON stream data,  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
[ERROR] [streamChoices] [2023-05-25T08:25:51.386Z] Error parsing JSON stream data,  <title>Web Gateway</title>
[ERROR] [streamChoices] [2023-05-25T08:25:51.386Z] Error parsing JSON stream data,  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
[ERROR] [streamChoices] [2023-05-25T08:25:51.387Z] Error parsing JSON stream data,  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
[ERROR] [streamChoices] [2023-05-25T08:25:51.387Z] Error parsing JSON stream data,</head>
[ERROR] [streamChoices] [2023-05-25T08:25:51.388Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.391Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.392Z] Error parsing JSON stream data,<body onload="swOnLoad();">
[ERROR] [streamChoices] [2023-05-25T08:25:51.392Z] Error parsing JSON stream data,<div class="centered">
[ERROR] [streamChoices] [2023-05-25T08:25:51.393Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.394Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.394Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.395Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.397Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.399Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.400Z] Error parsing JSON stream data,<div class="h1back">
[ERROR] [streamChoices] [2023-05-25T08:25:51.400Z] Error parsing JSON stream data,      Bad Response
[ERROR] [streamChoices] [2023-05-25T08:25:51.401Z] Error parsing JSON stream data,</div>
[ERROR] [streamChoices] [2023-05-25T08:25:51.402Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.402Z] Error parsing JSON stream data,<br>
[ERROR] [streamChoices] [2023-05-25T08:25:51.403Z] Error parsing JSON stream data,<div class="text">
[ERROR] [streamChoices] [2023-05-25T08:25:51.404Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.404Z] Error parsing JSON stream data,    The proxy did not receive a valid response in time.
[ERROR] [streamChoices] [2023-05-25T08:25:51.405Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.406Z] Error parsing JSON stream data,<br><br>
[ERROR] [streamChoices] [2023-05-25T08:25:51.408Z] Error parsing JSON stream data,<span class="bold">Technical information: </span><br>
[ERROR] [streamChoices] [2023-05-25T08:25:51.408Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.409Z] Error parsing JSON stream data,<div class="info">
[ERROR] [streamChoices] [2023-05-25T08:25:51.410Z] Error parsing JSON stream data,      <span class="bold">URL: </span><script type="text/javascript">break_line("https://copilot-proxy.githubusercontent.com/v1/chat/completions");</script><br />
[ERROR] [streamChoices] [2023-05-25T08:25:51.410Z] Error parsing JSON stream data,</div>
[ERROR] [streamChoices] [2023-05-25T08:25:51.411Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.411Z] Error parsing JSON stream data,</div>
[ERROR] [streamChoices] [2023-05-25T08:25:51.412Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.413Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.413Z] Error parsing JSON stream data,<div class="teaser">
[ERROR] [streamChoices] [2023-05-25T08:25:51.414Z] Error parsing JSON stream data,Generated at <span id="time">2023-05-25 08:25:51</span> from <span class="bold">sdea-mwg-p09</span>
[ERROR] [streamChoices] [2023-05-25T08:25:51.415Z] Error parsing JSON stream data,<br />
[ERROR] [streamChoices] [2023-05-25T08:25:51.415Z] Error parsing JSON stream data, 
[ERROR] [streamChoices] [2023-05-25T08:25:51.416Z] Error parsing JSON stream data,</div>
[ERROR] [streamChoices] [2023-05-25T08:25:51.417Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.417Z] Error parsing JSON stream data,</div>
[ERROR] [streamChoices] [2023-05-25T08:25:51.418Z] Error parsing JSON stream data,</body>
[ERROR] [streamChoices] [2023-05-25T08:25:51.419Z] Error parsing JSON stream data,
[ERROR] [streamChoices] [2023-05-25T08:25:51.419Z] Error parsing JSON stream data,</html>
[INFO] [streamMessages] [2023-05-25T08:25:51.428Z] message 0 returned. finish reason: [Iteration Done]
[INFO] [streamChoices] [2023-05-25T08:25:51.428Z] request done: headerRequestId: [a62a8db1-e9af-4213-b339-5d090f93c641] model deployment ID: [xa68ad36c6722]
`

Steps to Reproduce:

1. Ask: "please create a list of all methods in this js file https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/additional-methods.js"
2. Return after long time: Oops, no response has returned.

**Comment by digitarald** [comment] 2023-09-29 05:01
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/295

**Closed by digitarald** 2023-09-29 05:01 UTC
