### ISSUE TITLE
Chat extension doesn't work + no Icon in Activity Bar

### ISSUE THREAD

**Issue by bashmentarium** [microsoft/vscode-copilot-release#316] opened 2023-07-11 07:26 UTC
- VS Code Version: 
![Screenshot 2023-07-11 at 10 16 11](https://github.com/microsoft/vscode-copilot-release/assets/56018612/e2ecf94a-6192-4c54-b041-544cf4807a07)

- OS Version: 
<img width="281" alt="version" src="https://github.com/microsoft/vscode-copilot-release/assets/56018612/5370cadb-ff08-431f-9715-095e39c8c02d">

Steps to Reproduce:
1. Make sure you have an M2 MacBook Pro with a silicon chip
2. Download the latest insiders version of VSCode
3. Install & Open it
4. Press Cmd+Shift+X to go to the Extensions panel
5. Search & install 2 extensions:
     a. GitHub Copilot
     b. GitHub Copilot Chat
6. Restart the VSCode application.
7. Take a look at the Activity Bar that is on the left.
8. Observe:
![Screenshot 2023-07-11 at 10 16 46](https://github.com/microsoft/vscode-copilot-release/assets/56018612/fc980626-171d-4bf9-a4bb-b2a20dc4603a)

**Comment by bashmentarium** [comment] 2023-07-11 07:44
QUICK UPDATE:

I have anticipated the generic support team's next move, came forward, and update my MacOS to the latest - 13.4.1

<img width="281" alt="Screenshot 2023-07-11 at 10 43 15" src="https://github.com/microsoft/vscode-copilot-release/assets/56018612/a4e04785-fe4a-44d1-ac50-99940a1f395d">

**Comment by wencomsainty** [comment] 2023-07-13 00:04
Exact same setup, exact same issue.
![image](https://github.com/microsoft/vscode-copilot-release/assets/134982013/69a8f2ba-8252-4add-93a1-02f54103ee3d)

Version: 1.81.0-insider (Universal)
Commit: ad791ef3d26b99963da31636af697afd86575435
Date: 2023-07-07T19:50:58.701Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

![image](https://github.com/microsoft/vscode-copilot-release/assets/134982013/fa17d8f1-2f12-4919-b317-d73562cbdd91)
![image](https://github.com/microsoft/vscode-copilot-release/assets/134982013/16ec254b-c184-47b5-91c3-87664bc43fcf)

**Comment by ulugbekna** [comment] 2023-07-14 10:12
Can you still reproduce?

**Comment by bashmentarium** [comment] 2023-07-14 11:17
> Can you still reproduce?

Not anymore. It seems that you first need to become a part of the private Copilot Chat beta group by submitting a request to join here => https://github.com/github-copilot/chat_waitlist_signup/join

P.S. It was NOT intuitively clear that this step is crucial in order for the chat extension to work out of the box.

**Comment by wencomsainty** [comment] 2023-07-17 23:53
When I go here https://github.com/github-copilot/chat_waitlist_signup/join, I am already in 
![image](https://github.com/microsoft/vscode-copilot-release/assets/134982013/59336bca-7fad-4b1f-82f1-58fd4fc30d16)
But I still don't get the extension icon.

**Comment by wencomsainty** [comment] 2023-07-17 23:55
> When I go here https://github.com/github-copilot/chat_waitlist_signup/join, I am already in ![image](https://user-images.githubusercontent.com/134982013/254098179-59336bca-7fad-4b1f-82f1-58fd4fc30d16.png) But I still don't get the extension icon.

Solved it by signing out of github in vscode then signing back in.

**Comment by digitarald** [comment] 2023-07-18 17:27
@TylerLeonhardt could this be an auth scope issue?

**Comment by TylerLeonhardt** [comment] 2023-07-18 17:55
Hard to tell without the GitHub Authentication logs or Copilot logs from the Output channel (cmd+shift+u). Do you still have the window open when you had the problem @bashmentarium? Otherwise there's not much we can learn at this point.

**Comment by davemulder** [comment] 2023-07-21 22:41
I was having the same general issue and the problem turned out to be with organizational settings — Copilot Chat was blocked.

<img width="1200" alt="Screenshot 2023-07-21 at 6 21 26 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/231264/a5e06fa0-5f2d-499f-8a27-9c31f343fb30">

**Comment by ramaID** [comment] 2023-07-23 08:42
even I'm using Visual Studio Code - Insiders still have no chat icon.

Any suggestion how to debug, this?

<img width="1680" alt="Screenshot 2023-07-23 at 15 41 45" src="https://github.com/microsoft/vscode-copilot-release/assets/34129273/f7724d6c-02b7-4e56-8f15-8948b501a207">

**Comment by TylerLeonhardt** [comment] 2023-07-23 19:48
Please provide the GitHub Authentication logs or Copilot logs from the Output channel (ctrl/cmd+shift+u)

**Comment by gsuzuki983** [comment] 2023-07-24 16:51
I am a Windows user and am experiencing the same problem.
I have completed the necessary setup and procedures to use GitHub Copilot Chat, but when I install Extenstions in VSCode, the icon does not appear on the left side of the screen.
https://docs.github.com/ja/copilot/github-copilot-chat/using-github-copilot-chat

![image](https://github.com/microsoft/vscode-copilot-release/assets/48849186/a4214de6-a217-4576-a146-5ab8f59d5bbf)

Output: Github Copilot / Github Copilot Chat
```
(Blank)
```
Output: Github Authentication
```
2023-07-25 01:47:15.567 [info] Logging in for the following scopes: user:email
2023-07-25 01:47:15.573 [info] Trying without local server... (user:email)
2023-07-25 01:47:25.933 [info] Exchanging code for token...
2023-07-25 01:47:26.686 [info] Token exchange success!
2023-07-25 01:47:26.691 [info] Getting user info...
2023-07-25 01:47:26.977 [info] Got account info!
2023-07-25 01:47:26.978 [info] Storing 1 sessions...
2023-07-25 01:47:26.986 [info] Reading sessions from keychain...
2023-07-25 01:47:26.988 [info] Stored 1 sessions!
2023-07-25 01:47:26.989 [info] Login success!
2023-07-25 01:47:27.011 [info] Getting sessions for user:email...
2023-07-25 01:47:27.013 [info] Getting sessions for user:email...
2023-07-25 01:47:27.014 [info] Got stored sessions!
2023-07-25 01:47:27.014 [info] Got 1 verified sessions.
2023-07-25 01:47:27.014 [info] Reading sessions from keychain...
2023-07-25 01:47:27.014 [info] Got 1 sessions for user:email...
2023-07-25 01:47:27.015 [info] Got 1 sessions for user:email...
2023-07-25 01:47:27.019 [info] Getting sessions for user:email...
2023-07-25 01:47:27.019 [info] Getting sessions for user:email...
2023-07-25 01:47:27.019 [info] Got stored sessions!
2023-07-25 01:47:27.020 [info] Got 1 verified sessions.
2023-07-25 01:47:27.020 [info] Got 1 sessions for user:email...
2023-07-25 01:47:27.020 [info] Got 1 sessions for user:email...
2023-07-25 01:47:27.032 [info] Getting sessions for user:email...
2023-07-25 01:47:27.032 [info] Got 1 sessions for user:email...
2023-07-25 01:47:27.033 [info] Getting sessions for read:user...
2023-07-25 01:47:27.033 [info] Got 0 sessions for read:user...
2023-07-25 01:47:27.038 [info] Getting sessions for user:email...
2023-07-25 01:47:27.038 [info] Got 1 sessions for user:email...
```

**Comment by ramaID** [comment] 2023-07-31 13:31
> I'm facing the same issue. Any suggestion how to debug, this?
> 
> <img width="1680" alt="Screenshot 2023-07-23 at 15 41 45" src="https://github.com/microsoft/vscode-copilot-release/assets/34129273/f7724d6c-02b7-4e56-8f15-8948b501a207">

Literally I'm doing nothing, my chat bar in now showing.

**Comment by wweevv-johndpope** [comment] 2023-09-28 01:05
![Screenshot from 2023-09-28 11-03-07](https://github.com/microsoft/vscode-copilot-release/assets/109928647/bc397993-4c54-413f-afbb-3cfca949e9b7)


![Screenshot from 2023-09-28 11-04-59](https://github.com/microsoft/vscode-copilot-release/assets/109928647/bacdfe39-3776-4fca-929b-7a1d6654369b)

**Comment by TylerLeonhardt** [comment] 2023-09-28 17:16
Coming back to this issue... quite a bit has changed. Half of the folks in this thread have gotten it working. @ramaID @gsuzuki983 are you still having this issue? If so, can you:

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Trace`, click the double check mark button. ✔️ ✔️ (enables trace logging as the default)
* restart vscode
* Open the Output pane (ctrl/cmd+shift+u)
* drop in this issue he contents of the following:
  * `Github Authentication` Output channel
  * `GitHub Copilot` Output channel
  * `GitHub Copilot Chat` Output channel

When you wanna turn trace logging off you can:
* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Info`, click the double check mark button. ✔️ ✔️

**Comment by digitarald** [comment] 2023-09-29 17:38
I pulled all details into https://github.com/microsoft/vscode-copilot-release/issues/436, check for detailed debugging steps and how to pull logs in case the issue persists. I will close this as a duplicate to have issues on latest versions filed with logs attached for better diagnosis.

Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/436

**Closed by digitarald** 2023-09-29 17:38 UTC
Labels: info-needed
