### ISSUE TITLE
Copilot Chat filters chat related to states/provinces

### ISSUE THREAD

**Issue by adriand** [microsoft/vscode-copilot-release#175] opened 2023-05-30 14:04 UTC
Chat seems to have an issue with states/provinces, as though it is somehow encountering objectionable content when dealing with this.

There are multiple ways to reproduce this problem, here's one:

```
this is an array of states and provinces, please expand it to include all us states, canadian provinces, and mexican states:

export const StatesAndProvinces = [ { value: "AL", label: "Alabama" }, ]
```

Chat starts to work on this and halfway through the list of US states, reports:

```
Oops, your response got filtered. Vote down if you think this shouldn't have happened.
```

Depending on phrasing, Chat may also refuse to answer the question at all. For example:

```
please define a full set of US states, canadian provinces, and mexican states, expanding on this:

export const StatesAndProvinces = [ { value: "AL", label: "Alabama" }, ]
```

Response:

```
Sorry, but I can only assist with programming related questions.
```

**Comment by Jenverse** [comment] 2023-06-07 03:28
Thanks @adriand for reporting the issue. We are working on improving our off-topic filter quality.

**Comment by digitarald** [comment] 2023-09-29 05:01
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/295

**Closed by digitarald** 2023-09-29 05:01 UTC
Labels: github-team, off-topic-filter
