### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by nic-obert** [microsoft/vscode-copilot-release#772] opened 2024-01-22 20:33 UTC
When asking Copilot to explain a compiler error, the Copilot Chat throws an error.

![copilot_chat](https://github.com/microsoft/vscode-copilot-release/assets/64301833/00574dc8-5598-42e6-9489-17409b4ba0dc)

- VS Code Version: 1.86.0-insider
- OS Version: Linux 6.7.0-arch3-1
- Logs:
```
024-01-20 09:46:18.169 [info] [gitExtensionService] Initializing Git extension service.
2024-01-20 09:46:18.169 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-01-20 09:46:18.169 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-01-20 09:46:18.169 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-01-20 09:46:18.805 [info] [auth] Logged in as nic-obert
2024-01-20 09:46:19.842 [info] [chat] copilot token chat_enabled: true
2024-01-20 09:46:19.842 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-01-20 09:46:19.842 [info] [auth] Got Copilot token for nic-obert
2024-01-20 09:46:19.846 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-01-20 09:46:19.846 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-01-20 09:46:20.002 [info] [auth] Logged in as nic-obert
2024-01-20 09:46:20.005 [info] [chat] copilot token chat_enabled: true
2024-01-20 09:46:20.005 [info] [auth] Got Copilot token for nic-obert
2024-01-20 09:51:55.436 [info] [gitExtensionService] Initializing Git extension service.
2024-01-20 09:51:55.436 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-01-20 09:51:55.436 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-01-20 09:51:55.436 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-01-20 09:51:55.844 [info] [auth] Logged in as nic-obert
2024-01-20 09:51:56.871 [info] [chat] copilot token chat_enabled: true
2024-01-20 09:51:56.871 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-01-20 09:51:56.871 [info] [auth] Got Copilot token for nic-obert
2024-01-20 09:51:56.875 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-01-20 09:51:56.875 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-01-20 09:51:56.888 [info] [auth] Logged in as nic-obert
2024-01-20 09:51:56.891 [info] [chat] copilot token chat_enabled: true
2024-01-20 09:51:56.891 [info] [auth] Got Copilot token for nic-obert
2024-01-20 10:16:56.880 [info] [auth] Logged in as nic-obert
2024-01-20 10:16:57.384 [info] [chat] copilot token chat_enabled: true
2024-01-20 10:16:57.384 [info] [auth] Got Copilot token for nic-obert
2024-01-20 10:41:57.392 [info] [auth] Logged in as nic-obert
2024-01-20 10:41:57.822 [info] [chat] copilot token chat_enabled: true
2024-01-20 10:41:57.822 [info] [auth] Got Copilot token for nic-obert
2024-01-20 13:11:21.810 [info] [auth] Logged in as nic-obert
2024-01-21 15:25:09.817 [info] [auth] Logged in as nic-obert
2024-01-22 20:14:32.656 [info] [auth] Logged in as nic-obert
2024-01-22 20:14:33.089 [info] [chat] copilot token chat_enabled: true
2024-01-22 20:14:33.089 [info] [auth] Got Copilot token for nic-obert
2024-01-22 20:39:33.104 [info] [auth] Logged in as nic-obert
2024-01-22 20:39:33.551 [info] [chat] copilot token chat_enabled: true
2024-01-22 20:39:33.552 [info] [auth] Got Copilot token for nic-obert
2024-01-22 21:19:42.281 [info] [auth] Logged in as nic-obert
2024-01-22 21:19:42.628 [info] [chat] copilot token chat_enabled: true
2024-01-22 21:19:42.628 [info] [auth] Got Copilot token for nic-obert
2024-01-22 21:19:52.969 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-22 21:19:52.970 [info] [chat fetch] modelMaxTokenWindow 8192
2024-01-22 21:19:52.970 [info] [chat fetch] chat model gpt-3.5-turbo
2024-01-22 21:19:55.037 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2065 ms
2024-01-22 21:21:26.019 [info] [streamChoices] request done: requestId: [89d1a485-dd3b-418f-8b5c-c55ad1e01416] responseId: [89d1a485-dd3b-418f-8b5c-c55ad1e01416] model deployment ID: [x338b9c029b38]
2024-01-22 21:21:36.724 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-22 21:21:36.724 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-22 21:21:36.724 [info] [chat fetch] chat model gpt-4
2024-01-22 21:21:38.389 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1663 ms
2024-01-22 21:21:43.067 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-22 21:21:43.072 [info] [streamChoices] request done: requestId: [0bb1d835-9f01-4c2d-9c41-40e09d7ca7e5] responseId: [0bb1d835-9f01-4c2d-9c41-40e09d7ca7e5] model deployment ID: [xa51b78e920cd]
2024-01-22 21:22:15.351 [info] [WorkspaceChunkSearch] Failed to search chunk embeddings index: ,{}
2024-01-22 21:22:15.372 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (/home/nic/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1251:85)
    at /home/nic/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5254
    at Array.map (<anonymous>)
    at t.logMessages (/home/nic/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5183)
    at n1._provideResponseWithProgress (/home/nic/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1256:1173)
    at n1.provideResponseWithProgress (/home/nic/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1254:2086)
    at i.y (/home/nic/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1266:1022)
    at o.$invokeAgent (/var/lib/snapd/snap/code-insiders/1520/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:40137)
2024-01-22 21:22:46.883 [info] [auth] Logged in as nic-obert
2024-01-22 21:22:47.204 [info] [chat] copilot token chat_enabled: true
2024-01-22 21:22:47.204 [info] [auth] Got Copilot token for nic-obert

```

**Comment by surfbryce** [comment] 2024-01-23 03:13
Just to add on I get the same error but instead I get "map" rather than "split"

**Comment by wktk** [comment] 2024-01-23 03:28
This error seems to be the same as #761. If so, the pre-release version of the extension will work fine.

**Comment by surfbryce** [comment] 2024-01-23 03:31
@wktk Doesn't seem to be the case, on Insiders VSCode with Pre-release Copilot and still experiencing the issue, just not "split" rather "map"

**Comment by wktk** [comment] 2024-01-23 03:56
@surfbryce I don't see the "map" one, there may be a separate error like #763 maybe?

**Comment by surfbryce** [comment] 2024-01-23 03:57
@wktk yep I'll post on that one, thanks!

**Comment by Psvensso** [comment] 2024-01-23 14:32
Confirming that it works on /newChat
But it fails on "Collecting workspace info" after using /workspace

...
2024-01-23 15:26:44.443 [info] [chat] copilot token chat_enabled: true
2024-01-23 15:26:44.443 [info] [auth] Got Copilot token for me
2024-01-23 15:27:00.650 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1251:85)
    at c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1245:5254
    at Array.map (<anonymous>)
    at t.logMessages (c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1245:5183)
    at n1._provideResponseWithProgress (c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1256:1173)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at n1.provideResponseWithProgress (c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1254:2086)
    at i.y (c:\Users\me\.vscode-insiders\extensions\github.copilot-chat-0.11.1\dist\extension.js:1266:1022)
    at o.$invokeAgent (c:\Users\me\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:40137)

**Comment by mjbvz** [comment] 2024-01-24 00:53
Duplicate of #761

**Closed by mjbvz** 2024-01-24 00:53 UTC
Labels: @workspace
