### ISSUE TITLE
Bug when sending large prompt

### ISSUE THREAD

**Issue by nicolas-goyon** [microsoft/vscode-copilot-release#72] opened 2023-05-22 07:07 UTC
- VS Code Version: VSCode insiders latest
- OS Version: windows (remote to linux server)
- Logs:

Steps to Reproduce:

1. Copy paste a large file to the chat area
2. unhandled status from server: 400 Bad request: bad request: role must be "user", got "system"

**Comment by jclarkdev** [comment] 2023-05-22 07:16
> unhandled status from server: 400 Bad request: bad request: role must be "user", got "assistant"

**Comment by IvanVeridian** [comment] 2023-05-23 00:13
I also got this error when pasting a large error message into the chat. 
GitHub Copilot: 
unhandled status from server: 400 Bad request: bad request: role must be "user", got "assistant"

**Comment by digitarald** [comment] 2023-06-03 02:10
Dupe of #20

**Closed by digitarald** 2023-06-03 02:10 UTC
