### ISSUE TITLE
GitHub Copilot chat is outputting [object Object] instead of all code snippets

### ISSUE THREAD

**Issue by DeepBhat** [microsoft/vscode-copilot-release#568] opened 2023-11-14 07:41 UTC
Type: <b>Bug</b>

Ask GitHub Copilot Chat any questioin for which it will generate a code snippet. All code snippets are replaced by [object Object] instead.

Extension version: 0.11.2023111302
VS Code version: Code - Insiders 1.85.0-insider (94959e85502687ec77e23eb0d4d4b1a827b919af, 2023-11-14T05:34:30.773Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.16GB free)|
|Process Argv|--crash-reporter-id 8743c335-2dfb-4cd1-b65d-a60f83338239|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes516:30244333
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
synctok:30869157
dsvsc013:30777762
dsvsc014:30777825
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

<details>
<summary>Build info</summary>
Version: 1.85.0-insider (user setup)
Commit: 94959e85502687ec77e23eb0d4d4b1a827b919af
Date: 2023-11-14T05:34:30.773Z
Electron: 25.9.4
ElectronBuildId: 25127168
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19043
</details>

**Comment by aeschli** [comment] 2023-11-14 08:24
In the panel chat or the inline chat? Can you add a screenshot and provide the prompt that shows that?

**Comment by DeepBhat** [comment] 2023-11-14 08:31
Only in the panel chat. Inline chat is working fine. Here is a screenshot:
![image](https://github.com/microsoft/vscode-copilot-release/assets/33815709/13f4ec7a-023c-42ab-9f73-42d05458e764)

I will get an output like this for any answer that has code in it, no matter what the prompt is.

**Comment by 1835625** [comment] 2023-11-14 09:14
Yes, the same problem happened to mine, too.
<img width="205" alt="github copilot chat问题反馈" src="https://github.com/microsoft/vscode-copilot-release/assets/121747948/571034cb-1c92-45b9-b0d0-8ccc6f7b4842">

**Comment by LikeDreamwalker** [comment] 2023-11-14 09:15
Same issue here, and it just happened today, almost around 1500 in Beijing.
![image](https://github.com/microsoft/vscode-copilot-release/assets/45194556/95cfe0e0-234b-46e9-a26a-7287cd70928f)
Please fix it. Is this caused by a hot-fix and changed the data structure of the response?

**Comment by ebigtm** [comment] 2023-11-14 09:41
same under chat in vscode insider after updated today, no code can be present

**Comment by maxilirator** [comment] 2023-11-14 10:00
Yep me too, tried different versions, doesn't help. Good way to understand how much i have started to rely on Copilot.

**Comment by bgrootButler** [comment] 2023-11-14 11:25
Same here

**Comment by TonyBlur** [comment] 2023-11-14 12:33
I have the exact same issue (insider version)

**Comment by docimin** [comment] 2023-11-14 13:39
Same here, insiders :)

**Comment by aeschli** [comment] 2023-11-14 14:22
Will be fixed by https://github.com/microsoft/vscode/pull/198198

**Comment by Taraman12** [comment] 2023-11-14 14:22
Just got an update which fixes the bug. 
Thanks @aeschli 👍

**Comment by aeschli** [comment] 2023-11-14 14:23
Yes, you need to update VS Code Insiders.

**Comment by aeschli** [comment] 2023-11-14 14:25
Closing as fixed

**Closed** 2023-11-14 14:24 UTC
Labels: info-needed
