### ISSUE TITLE
[ ↓ ] [ ↑ ] keys are CLEARING the chat input when editing the prompt

### ISSUE THREAD

**Issue by lucklo** [microsoft/vscode-copilot-release#701] opened 2023-12-23 12:59 UTC
- VS Code Version: v0.11.1
- OS Version: macOS 14.2.1 (23C71)
- Logs: n/a

Steps to Reproduce:

1. Open chat
2. start typing multi line prompt with 2 lines of text(Shift+Enter)
3. Move text cursor at first line
4. Hit arrow down (you will be at 2nd line)
5. Hit arrow down again
6. You will notice that the whole input has been replaced with previous prompt
7. The previous prompt is not recoverable

**Expected behavior:**
When the prompt input has any text (is not empty) [ ↓ ] or [ ↑ ] should NOT replace the content

If that wasn't intentional then all is fine - just fix it.
If that was a intentional decision - that genius should think about his life choices.

**Additional Note:** Arrow UP and Arrow DOWN keys does behave in exactly the same destructive way.

**Comment by daniel-fahl** [comment] 2023-12-23 13:38
Duplicate of #661 and #662

**Comment by vfonic** [comment] 2024-01-31 16:15
In #661 it says that this has been fixed/merged two weeks ago. When will this be available?

I have the latest stable VS Code and Copilot.

**Comment by ianbruton** [comment] 2024-02-05 12:18
I am on the prerelease of copilot and copilot chat and this is still broken.

To be honest, I do not want this feature at all.

If I ever need text from an old prompt for anything, it's never to send the exact same prompt again. I usually only need a small part from it, but rarely, if ever, the entire thing. So for me at least it is actually easier to just highlight the part I need with my mouse, since it's right there in the chatlog anyway.

Also, when I do copy some text to the chat textbox, I am 99 times out of 100 going to need to move about that text to make edits or add context/modifications, and if in doing so I accidentally press up or down one to many times while at at the top or bottom of the textbox, boom, all my work is gone.

This has happened to me on a pretty much daily basis*, and when it does, I stop using the chat in my editor and go back to chatGPT, simply because the text box functions how I expect it to, and I don't need to remember to craft my prompt in a blank editor tab in my IDE before copying it to the copilot chat box. 

I have been burned too many times, and each time it's a loss of a substantial amount of time, but also the thought process to creating the prompt, and now I need to mentally step through the issue again. For lack of a better description, it is INFURIATING. 

Please just let me turn it off in the settings of my IDE, because even when it is working as intended, I don't want it. 

* I think the reason that it frequently happens to me is because I, like I am sure many others also do, will just hold the up and down arrow to get to the top and bottom of a textbox. Because that is how they have basically always worked. This feature, while super useful if you are used to it, is very jarring is you are not used to it. So again, please just add the option to turn it off.

**Comment by lramos15** [comment] 2024-03-28 17:56
This has been fixed / is a duplicate of #661

**Closed by lramos15** 2024-03-28 17:56 UTC
Labels: triage-needed
