### ISSUE TITLE
Received "Sorry, but I can only assist with programming related questions." as the response when discussing HTML "data-*" attribute conventions

### ISSUE THREAD

**Issue by KalleV** [microsoft/vscode-copilot-release#292] opened 2023-06-30 15:49 UTC
- VS Code Version: 1.80.0-insider
- OS Version: Darwin x64 22.4.0
- Logs: N/A

Steps to Reproduce:

1. Open Copilot Chat
2. Ask: What are some common "data" attribute conventions for identifying unique elements on the page?
3. Wait for response
4. Ask: Expand on the "data-*" attribute conventions?
5. Wait for response.
6. Is there a "data-*" attribute convention that will work across Cypress, Fullstory, Playwright, and Datadog RUM?
7. Response: `Sorry, but I can only assist with programming related questions.`

Note:
When I amended the question to: "Is there an **HTML** "data-*" attribute convention that will work across Cypress, Fullstory, Playwright, and Datadog RUM?" then it works.

**Comment by kseuro** [comment] 2023-07-10 19:41
I got the same response when asking about labelling the whiskers in a boxplot I'd just made within a Jupyter notebook.
![image](https://github.com/microsoft/vscode-copilot-release/assets/18079465/e86b0c61-70a5-4416-831e-0c8d02959764)

Version: 1.80.0-insider (user setup)
Commit: 7406a9bdfca18f82a3977ba5eac908d41df7ccac
Date: 2023-06-30T05:33:00.101Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by jchase** [comment] 2023-07-13 00:05
Same issue.
Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z (1 wk ago)
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Selected a portion of code and prompted:

"Adjust this to accommodate the following logic: 1) If it's just one speaker, leave as is, but 2) if it's more than one speaker, I need to remove the word "founder" and then also list their job title after their name."

Response was: "Sorry, but I can only assist with programming related questions."

Adjusted my prompt by adding the word "code":

"Adjust this _code_ to accommodate the following logic: 1) If it's just one speaker, leave as is, but 2) if it's more than one speaker, I need to remove the word "founder" and then also list their job title after their name."

Response: (the correct code suggestion)

**Comment by mianowill** [comment] 2023-07-13 14:49
Hopping on this thread to avoid polluting the issues; I'm an embedded developer and any time I write 'ESP32' it triggers the "Sorry, but I can only assist with programming related questions" response. Writing 'ESP 32' or 'ESP-32' or 'EPS32' or anything else works around this.

**Comment by KalleV** [comment] 2023-07-16 14:25
I came across another example that seems straightforward to reproduce: "What is GDPR?"
![what_is_gdpr](https://github.com/microsoft/vscode-copilot-release/assets/5942028/91e94fae-d133-41bc-a9e0-ccb39d31a1dc)

**Comment by alexander-stolz** [comment] 2023-08-07 12:26
This happens a lot, when I ask follow up questions. In this example, I only asked for examples, where  the `as` keyword is used and the results were not great:

![grafik](https://github.com/microsoft/vscode-copilot-release/assets/4092790/39bc8ddd-0eee-4f9a-a884-583f714b6478)

**Comment by KalleV** [comment] 2023-08-08 11:33
I was trying to ask it to show me an object after applying a transform on JS Object and got filtered:
![copilot_array_flat_1](https://github.com/microsoft/vscode-copilot-release/assets/5942028/acb04eaa-caed-4e84-9989-c97b5ed1d1fd)
![copilot_array_flat_2](https://github.com/microsoft/vscode-copilot-release/assets/5942028/d48213f4-dc17-4bc8-9d2c-7b2a6fc02996)

When I asked `What would the shape of the ARRAY be after flattening?`, it gave the correct answer.

**Comment by KalleV** [comment] 2023-08-10 19:14
I was content-filtered today when trying to ask how [koalas](https://www.npmjs.com/package/koalas) works. The chat was activated via the "/explain" shortcut and the VSCode inline-shortcut on this line of code in the Datadog dd-trace library: `const coalesce = require('koalas')`.

<img width="484" alt="Screenshot 2023-08-10 at 3 11 11 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/5942028/9fae7053-a065-43f9-9f92-2f3187ceeb79">

**Comment by joshhunt** [comment] 2023-10-23 15:14
Similarly, I found it often blocks questions related to cypress

> how to cypress assert should be multiple matching elements?

Was blocked, while

> Using the e2e browser testing framework Cypress, how do you assert that multiple items match a selector?

Succeeded

![image](https://github.com/microsoft/vscode-copilot-release/assets/46142/64331751-79b8-4089-924a-2721461eec79)

**Comment by sharonlo** [comment] 2023-11-09 19:30
@KalleV , @mianowill , @alexander-stolz , @joshhunt  -- thanks for your patience. We've deployed an update that addresses this. Please let us know if you're still hitting these issues!

@kseuro , @jchase, we're still investigating how to address your examples. We've shipped significant improvements, however accurate off-topic detection in follow-ups is something we're still working on.

**Comment by digitarald** [comment] 2023-11-15 03:40
Closing for now, as those questions work. Please file new issues for follow-up reports.

**Closed by digitarald** 2023-11-15 03:40 UTC
Labels: bug, github-team, off-topic-filter

**Comment by sdr0x07b6** [comment] 2023-11-16 10:35
Nothing has been resolved. When I started VSCode today, there was an update to the Copilot chat extension, so I updated it and it got worse." The rate of "Sorry, but I can only assist with programming related questions." has increased.

I don't think it's a good idea to unilaterally close the thread without hearing everyone's feedback, or at least the feedback of the participants in this thread.

**Comment by sdr0x07b6** [comment] 2023-11-16 11:03
I don't think the issue should be how to improve the ability to decline questions in such a way, but whether the feature is necessary in the first place. We could consider deactivating it, at least until it is completely improved.

We should be aware of the fact that user productivity has been significantly reduced because the feature continues to make bad decisions.

What is the purpose of that feature? Because if you start talking to Copilot about non-programming chats, you'll get a huge number of requests? Because Copilot will learn something other than programming?
Conscious engineers who are even charging for Copilot are not that stupid.
If they want to make small talk, they use openai's ChatGPT; they should be rather literate in how to deal with AI.
Trust us engineers more.

Why don't you try deactivating the feature and in case you get a lot of unintended requests, then you can bring it back again.

**Comment by Mujtaba-Abbasi** [comment] 2023-12-31 02:48
this has happened with me so many times. Especially when I ask a follow up question. It's really frusting sometimes.

**Comment by sdr0x07b6** [comment] 2024-01-19 19:44
@sharonlo Why is it CLOSED? There has been not the slightest improvement. In fact, it has gotten significantly worse. There are frequent days when no matter what I ask, all I get is "Sorry, but I can only assist with programming related questions.
It's not a service.
Please explain in detail.

**Comment by Perusae** [comment] 2024-03-03 23:10
We noticed copilot getting more restrictive over time.

While some questions are not "pure" related to a programming issue, they fall in the programming scope. Silly things like asking for better (English) naming of functions, gets these type of frustrating response  "Sorry, but I can only assist with programming related questions.".  We need to "trick" copilot into answering (in other words, it has no issue doing it, but its being artificially restricted). 

The current Copilot behavior is NOT what we paid for.

**Comment by TheWonderfulTartiflette** [comment] 2024-03-19 09:57
@digitarald Sorry, but I'm not sure that by giving it a Python code line, and asking it “Explain this line”, it's considered “working” if it tells me Sorry, but I can only assist with programming related questions

**Comment by sdr0x07b6** [comment] 2024-05-29 05:12
@sharonlo Are you not willing to fix it anymore? Or can't you? Let me and everyone else know what the situation is.
Do we need to determine strictly whether the story is about programming in the first place? People are getting frustrated.
The question should not be how to determine if it is about programming, but rather the lack of need itself.

I paid for a one year subscription and have not been able to use it nearly as much as I could. I am considering giving up using it.
It's not an issue like whether the quality of the AI's answers are good or bad, but rather the dimension that they don't answer the questions in the first place.
Is there a refund policy against minimum quality assurance?

**Comment by digitarald** [comment] 2024-05-29 22:57
@sdr0x07b6 in which cases do you hit the issue? If you could provide the type of context and the questions we can include it in our tests. Please file a new issue that we can track.

**Comment by sdr0x07b6** [comment] 2024-05-29 23:00
Sorry, but I can only assist with this Issue related questions.

**Comment by alvarovegaromero** [comment] 2024-06-01 11:26
Still experiencing it when trying to get an explanation of a function in Python provided by him

**Comment by howar31** [comment] 2024-07-11 04:08
constantly got response "Sorry, but I can only assist with programming related questions." recently.  very annoying and unusable

**Comment by duwejeferson** [comment] 2024-07-26 14:47
The annoying answer persist on distinguishable programming questions.
![image](https://github.com/user-attachments/assets/7e4523b0-dd80-47ab-924e-5a0ccf5fa42f)
Just for context, the first question was "Any suggestions on how to simplify these methods? Maybe unifying them on one."
Then after arguing about the question being about programming, I receive the answer correctly.

Maybe we should remind you guys that the intent of the AI is to assists us and help in being more productive. Needing to argue with if it, it's just the opposite.

**Comment by benjiro29** [comment] 2024-07-26 14:55
Yea, whenever it bitches about non-programming question, say "its a programming question". Or if you get the "Because of ethical ...", check your question and there is literally some word in your question, that "may be" taken in a totally different context as non-ethical. 

Take it out or change it, and its bypassed. Very often because of the AI can not differ context vs words, you get blocked. Its a lot less fun when your blocked as non-native English speaker only to find out that a word may have a different meaning, under a different context.

Its extremely frustrating as it drags you out of your programming and needed to deal with AI. There has been a big uptick in this and I think its related that people are trying to use copilot as a cheap AI alternative for general usage, what results in MS going ham on the restrictions, what in turn frustrates the actual programmers.

I have my doubts about lengthening my year subscription with the increased restrictions. Its a paid product, what do you guys care if I ask it pure programming question, or questions related to marketing or text from the website.

**Comment by sdr0x07b6** [comment] 2024-07-26 15:12
You guys are absolutely right, Microsoft should recognize that there are frequent times when user productivity is severely compromised.

If you ask the exact same question to ChatGTP, which has no context, than to Github Copilot, which is integrated with VSCode and is in an environment where you can directly read multiple source codes and get context, ChatGTP always gives a better answer.

Just as Google is not good at social services and Apple is not good at cloud computing, I must say that Microsoft is not good at AI.
Bing and Windows AI also seem to have a bad reputation.
What they all have in common is the strong impression that all AIs are over-tuned to match their services.
That seasoning is having the opposite effect; I think Microsoft should have more faith in its users and simply provide an environment.

I too have strong reservations about continuing to use it as a paid product.
When I asked about the refund policy, they seem to want me to reproduce the funny conversations I had with the AI.
Is Microsoft using this AI themselves?
