### ISSUE TITLE
Error from provider: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by lucasbasquerotto** [microsoft/vscode-copilot-release#901] opened 2024-02-15 19:41 UTC
- VS Code Version: 1.87.0-insider
- OS Version: Windows 11 Home
- Logs:

```
[chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: newSymbolNamesProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatProvider, chatAgents2, chatAgents2Additions, defaultChatAgent, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu but NOT newSymbolNamesProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat (at console.<anonymous> (c:\Users\Asus\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:59091))
```

Steps to Reproduce:

Click with the right mouse button in a file, and in Copilot, choose `Explain this`.

It's giving me the error `Error from provider: Right-hand side of 'instanceof' is not an object`.

If I start a new chat, it works the 1st time, but then it will always return this error.

I can start an inline chat and it answers without errors.

The copilot autocomplete is working correctly, only the chat is giving errors (but inline chat works).

It started giving this error today (altough I haven't used it in the last 2 days).

This error happened using a python file, but I reproduced it with a txt file too (it always gives errors; if I start a new chat it works only the 1st time).

**Comment by andreamah** [comment] 2024-02-15 19:43
I believe this is a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/889

**Closed by andreamah** 2024-02-15 19:43 UTC
Labels: triage-needed
