### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by Jexceed** [microsoft/vscode-copilot-release#89] opened 2023-05-23 01:38 UTC
- VS Code Version:1.79.0-insider (Universal)
- OS Version: MacOS13.2.1 (22D68)
- Logs: Oops, your response got filtered. Vote down if you think this shouldn't have happened.

Steps to Reproduce:

1. in long code generation. for example, "/simplify", "/complete KMP Algorithm"
2. the code in response is filtered, and it says "Oops, your response got filtered. Vote down if you think this shouldn't have happened."

**Comment by rtiwari001** [comment] 2023-05-23 08:21
Same error occurred for me where I asked to help me with the code.
<img width="426" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/110724551/ba262fe8-bdde-4f3c-b57a-384aff4c0d0f">

**Comment by AndyOR-R** [comment] 2023-05-23 11:36
I get this every time I try to get it to print out the code in my repo with the updates that it recommends. I can see the first 30 - 40 lines of code before it fades to dark and gives that error: "Oops, your response got filtered. Vote down if you think this shouldn't have happened."

**Comment by ghkimwoo** [comment] 2023-05-24 02:07
The same error occurred when the Copilot bot was directly optimized for about 100 lines of Arduino code. In the Copilot output, it was forcibly stopped with content_filter, not with stop.
![image](https://github.com/microsoft/vscode-copilot-release/assets/45334270/e4695306-6c8e-4340-b69a-7a1c6a268307)

**Comment by asimovezh** [comment] 2023-05-24 03:49
Same issue
When copilotx answer exceeds some specify line number,it occure
For example:generate a model define code of GAN in pytorch

**Comment by hiahiahia0213** [comment] 2023-05-27 04:09
same issue.

**Comment by mbianchidev** [comment] 2023-05-27 16:59
- VS Code Version: VSCode Insiders
- OS Version: WIndows 10 Enterprise (latest)
- Logs: N/A

Steps to Reproduce:

1. Select a piece of code, regardless of the language
2. Ask for suggestions and get your suggestion flagged/filtered during its generation

![image](https://github.com/microsoft/vscode-copilot-release/assets/37507190/b36b1c72-b494-4d55-a8ea-ba72561041c2)

Asking for clarification you get an unsatisfying answer that loops if you keep asking the reason why your request might have generated that kind of filtering.

![image](https://github.com/microsoft/vscode-copilot-release/assets/37507190/07306a7b-cd1f-44fa-826b-8b9e59902a6f)

Voting down doesn't change much, it keeps filter the response.
In my case it was Go Kubernetes-related code.



Same issue here: 
https://github.com/microsoft/vscode-copilot-release/issues/106
https://github.com/microsoft/vscode-copilot-release/issues/127

Seems like the chat is currently pretty broken: https://github.com/orgs/community/discussions/56134

**Comment by LikeDreamwalker** [comment] 2023-06-18 13:44
Same issue, and I think it's not related to the network.
So I am wondering if this is the same with [#](https://github.com/microsoft/vscode/issues/182359).
The request is right, but the response is too long after working, so vscode decides to shut down the request.

**Comment by MarsonShine** [comment] 2023-07-03 16:10
some issue

**Comment by nczsl** [comment] 2023-07-08 01:10
same issue.
----------------
win10
vscode 1.80.0

**Comment by odygrd** [comment] 2023-07-17 12:53
same issue here, every time I copy and paste some existing code (e.g. a class in c++) and ask for suggestions

**Comment by DylanBruzenak** [comment] 2023-07-26 17:02
I just got access to chat and this is happening for every typescript / react question I ask. Unusable. How is this still a bug almost 3 months later ? We should be able to opt out or set the filtering level if this is going to be so draconian. I've gone back to using gpt-4 directly, it answers the same questions with pretty much the same examples just fine.

**Comment by SergioHPassos** [comment] 2023-08-04 01:13
I've been using the chat feature for a few weeks already and I just started getting this issue. Whenever the text is generating a long response it flags it as a content filter. All the code is custom and nothing would be harmful or even proprietary. Who ever implemented this system should double check their test cases

**Comment by olawalejuwonm** [comment] 2023-09-11 10:26
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

Also getting this, any solution please?

**Comment by CavenRE** [comment] 2023-09-27 01:11
Look, the problem with code is that you are going to end up somehow or another using someone elses functions name, filters, ideas, etc. I get you may not want to just copy paste copyrighted code, but if you get to that solution through a hefty chat prompt and back and fourth solving issues.
I dont think this applied anymore. 
I started using this again and it is really good.

BUT, this will cause me to me un-sub. ChatGPT will give me better answers without this "filter", so no point wasting my money here. This best get fixed quick. Having the chat window in VSCOde is nothing more than a novelty. The moment it becomes a nuisance, it will quickly lose traction.

**Comment by digitarald** [comment] 2023-09-29 04:38
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/295

**Closed by digitarald** 2023-09-29 04:38 UTC
Labels: github-team, RAI-filter

**Comment by ahwelp** [comment] 2024-01-25 13:09
I also got this problem, but in a very specific case.

I was creating a Json with information about a TV show called The Oblongs. I copied and paste a table with all episodes from Wikipedia, highlighted the text and asked this prompt: "Convert to a Json array. First line is the keys, the following line after the numeric should be description. On new line, add a new entry on the json" .

On episode 10, Copilot stopped to generate the Json, probably for inappropriate language. I tried to generate this episode by itself, but it also failed.

**Comment by TheCenterforUnity** [comment] 2024-02-07 10:28
I get this response for everything I type in copilot. Anyone knows how to solve this?

**Comment by digitarald** [comment] 2024-02-07 21:20
@TheCenterforUnity please provide the logs from VS Code's output panel for "GitHub Copilot Chat"

**Comment by Yangbodi** [comment] 2024-02-22 02:07
我这里不管问什么问题都说Oops, your response got filtered. Vote down if you think this shouldn't have happened.

**Comment by min13s** [comment] 2024-03-04 05:27
whatever the problem i ask, the answer is  Oops, your response got filtered. Vote down if you think this shouldn't have happened.

**Comment by shubham-raj7129** [comment] 2024-03-14 08:38
I keep getting **Oops, your response got filtered. Vote down if you think this shouldn't have happened.** everytime I try to use copilot. Does anyone have any solution to this?

**Comment by min13s** [comment] 2024-03-14 12:10
I update the vscode to latest version, then it works



---Original---
From: "SHUBHAM ***@***.***&gt;
Date: Thu, Mar 14, 2024 16:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/vscode-copilot-release] Oops, your response gotfiltered. Vote down if you think this shouldn't have happened. (Issue #89)




 
I keep getting Oops, your response got filtered. Vote down if you think this shouldn't have happened. everytime I try to use copilot. Does anyone have any solution to this?
