### ISSUE TITLE
missing a accept/discard option

### ISSUE THREAD

**Issue by bugslayer01** [microsoft/vscode-copilot-release#1627] opened 2024-09-24 08:31 UTC
Type: <b>Bug</b>

i typed some gibrish co-piolet and it gfenerated some randome code which i am unable to accept or decline

Extension version: 0.20.3
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.87GB free)|
|Process Argv|--crash-reporter-id 30f510f6-ed6d-436e-86f8-e90535c48a7d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563
iacca1:31138162

```

</details>

**Comment by bugslayer01** [comment] 2024-09-24 08:33
![image](https://github.com/user-attachments/assets/1926b6b1-0771-4329-8b72-2d3c5b79e772)

**Comment by jrieken** [comment] 2024-12-09 14:18
/duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1625

**Closed** 2024-12-09 15:30 UTC
Labels: inline-chat
