### ISSUE TITLE
Visual indication of Copilot's code context

### ISSUE THREAD

**Issue by jonathanfischer97** [microsoft/vscode-copilot-release#144] opened 2023-05-26 21:25 UTC
## As a user, I have no idea which parts of my code Copilot is able to see
I think Copilot could really use some type of **highlighting** or other **visual** to tell the user what code it's "seeing" when you query it, as well as what code it's referencing to inform its answer. Seems quite opaque right now. 

Sometimes, it seems to only know about my current codeblock, and other times it seems to see the entire file. This opacity gets compounded with multiple queries about different blocks or files within the same thread.

## Some ideas/feature request to help with this:
- Allow users to manually set the code context that's referenced from; something like a checklist of files/dirs in your workspace. This allowed retrieval space should be clearly indicated within the Chat UI
- With longer conversation threads, maybe add a color gradient to the highlighting of previously referenced code that scales as the "weight" of that reference increases or decreases in the preprompt. Basically just visual feedback for the recency bias in chat, as a rough approximation of how much Copilot remembers from earlier in the conversation. 
- Use what ever system Bing uses to cite sources, in this case files or even linenumbers

### I think some sort of visual feedback would help with a problem that I, and presumably others, have had with IDE integrations of LLMs: 
I very rarely use the "edit in-place" functionality on a codeblock because I don't know if I can trust that the model is informed about the rest of my code! At least with ChatGPT, I know which parts of my codebase it's able to reference because I explicitly inserted those parts into its context via copy-paste during the course of the conversation.

**Comment by digitarald** [comment] 2023-10-04 02:32
Definitely on our radar! Duplicate of #188

**Closed by digitarald** 2023-10-04 02:32 UTC
Labels: context-bug
