### ISSUE TITLE
Render markdown for generated results

### ISSUE THREAD

**Issue by shivam-tripathi** [microsoft/vscode-copilot-release#1336] opened 2024-06-24 19:19 UTC
Rendered markdown is unreadable at the moment. I suspect ensuring results have `$$` before and after generated markdown will work, but I do see in some cases it is not that straightforward.

<img width="834" alt="Screenshot 2024-06-25 at 12 48 58 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/9463078/a2a57bce-b017-46c4-982e-da1ac1166433">

**Comment by shivam-tripathi** [comment] 2024-06-24 19:20
Also: new lines submitted in the prompt also disappear post hitting submit.

**Comment by mjbvz** [comment] 2024-06-25 19:25
> Also: new lines submitted in the prompt also disappear post hitting submit.

What did you originally write in the prompt?

**Comment by mjbvz** [comment] 2024-06-25 19:26
Seems like a duplicate of #978

**Closed by mjbvz** 2024-06-25 19:26 UTC
Labels: triage-needed

**Comment by shivam-tripathi** [comment] 2024-06-28 07:04
@mjbvz The prompt is in the screenshot, it was a pretty straightforward prompt. It can be reproduced with any prompt that might produce mathematical equations - which are come out in the latex output.
