### ISSUE TITLE
Sign In button sometimes doesn't work

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-copilot-release#1644] opened 2024-09-25 16:41 UTC
Type: <b>Bug</b>

A few users have reported seeing the sign in button when opening the chat tab, when they are already signed in. Clicking it has no effect. They have to sign out of their GitHub account and sign back in to get access to chat. Screenshot of the button below.

![Image](https://github.com/user-attachments/assets/31bf996c-88ec-4621-a0e9-750722542bd7)

Extension version: 0.21.2024092501
VS Code version: Code - Insiders 1.94.0-insider (be2747e47e127ec674148b78dd9556c6317d18bd, 2024-09-25T05:04:31.141Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by TylerLeonhardt** [comment] 2024-09-25 21:46
Were these VS Code Insiders users or is that just what you were using?

**Comment by bwateratmsft** [comment] 2024-09-26 13:22
These were all Insiders users

**Comment by TylerLeonhardt** [comment] 2024-09-26 18:49
I can't repro this sadly, can you get me the GitHub Copilot Chat & GitHub Authentication output channels?

**Comment by Santosh-Baliarsingh** [comment] 2024-09-26 18:54
> These were all Insiders users

For reference, I’m using the stable version of VS Code, not the Insiders edition.

**Comment by bwateratmsft** [comment] 2024-09-26 19:02
@TylerLeonhardt I think you can just resolve this as no repro. Only a couple of users complained about it during our bug bash and I think what was happening was activation of the extension was just taking a while, so clicking the button had the appearance of no effect. By the time they signed out and back in, activation was complete.

**Comment by TylerLeonhardt** [comment] 2024-09-26 19:04
I'll keep this open for a bit as I duped a few issues to it. But yeah I'll close it later if I don't get any confirmation that this is happening in Insiders.

**Comment by youfeng1024** [comment] 2024-09-26 20:11
@TylerLeonhardt Just yesterday, I accidentally discovered the reason for the issue I was experiencing. My problem is exactly the same as the one described by the person in this link: [a issue in extension cnb](https://github.com/cnblogs/vscode-cnb/issues/303). 

It was caused by a conflict between the extension with the ID cnblogs.vscode-cnb and Copilot. This extension helps Chinese programmers write blogs on a platform called “博客园” (cnblog) and has a login feature. (As shown in the first image of https://github.com/microsoft/vscode-copilot-release/issues/1570). Yesterday, I tried disabling this extension and reopening VSCode, and Copilot Chat started working correctly again. Considering that cnblog is a popular site in China, I believe many Chinese users experiencing this issue likely have this extension installed. 
 I just tried updating Copilot Chat and Copilot to the preview version, but unfortunately, there was no effect. 

I hope this information is helpful to you.

**Comment by naivelogic** [comment] 2024-09-27 05:56
im on insiders and have the same "Singin with Github to use Copilot, your AI pair programmer" but doesnnt let me signin, but this only happens in a devcontainer. outside of the devcontainer on the same vscode insiders-1.94.0 copilot chat works just fine. just in the dev containner.

**Comment by TylerLeonhardt** [comment] 2024-10-04 17:11
@youfeng1024 follow along here, I think they will fix: https://github.com/cnblogs/vscode-cnb/issues/303

**Comment by TylerLeonhardt** [comment] 2024-10-04 17:12
@naivelogic we just released 1.94 of VS Code & 0.21 of Copilot Chat. Can you try with these and if you're still having issues, open a new one so we don't bother the folks who's issues are different here.

**Closed** 2024-10-04 17:12 UTC
Labels: info-needed
