### ISSUE TITLE
Sorry, your request was rate-limited. Please wait 90 minutes before trying again.

### ISSUE THREAD

**Issue by dungfv** [microsoft/vscode-copilot-release#1829] opened 2024-10-11 16:31 UTC
Type: <b>Bug</b>

Sorry, your request was rate-limited. Please wait 90 minutes before trying again.
????

Extension version: 0.21.1
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id ee24372e-5021-40ad-ad0d-2e8b2d19d88c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by dungfv** [comment] 2024-10-11 16:46
@lramos15 I just had this problem with Copilot chat.
I'm using the paid version of Copilot. It's terrible that I have to wait 1h30m

**Comment by digitarald** [comment] 2024-10-11 20:52
Duplicate of #1610

**Closed by digitarald** 2024-10-11 20:52 UTC
Labels: triage-needed

**Comment by dungfv** [comment] 2024-10-12 09:00
@digitarald I would like you to say that the issue has been resolved, or a clearer explanation of the limits that will be placed on my account.
Not a vague message like that.

**Comment by digitarald** [comment] 2024-10-15 23:03
To clarify, the duplicate comment means work is happening to improve the rate-limiting and we'll post updates to https://github.com/microsoft/vscode-copilot-release/issues/1610.
