### ISSUE TITLE
Reply with the following answer for any content:“Oops, your response got filtered. Vote down if you think this shouldn't have happened.”

### ISSUE THREAD

**Issue by lieft** [microsoft/vscode-copilot-release#867] opened 2024-02-08 18:55 UTC
![屏幕截图 2024-02-09 025147](https://github.com/microsoft/vscode-copilot-release/assets/50590686/22597be5-4ec4-4951-bf15-b574ca28c955)

I am using the latest version, and any inquiries now show as filtered. It has been going on for half a month now, and I always thought it would be fixed, but it didn't happen

**Comment by FistFullofCookies** [comment] 2024-02-08 21:16
I have same issue when using version 0.8.0 and recieve this error. 

2024-02-08T19:22:09.565Z [ERROR] [chat fetch] Unhandled status from server:,410,{"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":**"copilot-chat/0.8.0"**,"editor-version":"vscode/1.83.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}

I do not have newer versions available to me and the blog mentioned in the details of the error state 0.8.0 already utilizes the new API.

GitHub Copilot: Collect Diagnostics shows 

## Copilot

- Version: 1.159.0
- Build: prod
- Editor: vscode/1.83.1

## Reachability

- github.com: HTTP 200 - OK
- copilot-proxy.githubusercontent.com: HTTP 200 - OK
- api.githubcopilot.com: HTTP 200 - OK
- default.exp-tas.com: HTTP 200 - OK

**Comment by digitarald** [comment] 2024-02-08 22:06
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/826 . Please update Copilot Chat.

**Closed by digitarald** 2024-02-08 22:06 UTC

**Comment by lieft** [comment] 2024-02-09 05:49
The latest version in vscode cannot be updated anymore
