### ISSUE TITLE
Cached files coming from Github Copilot Chat are flagged as "Problems" in VS Code

### ISSUE THREAD

**Issue by amsoedal** [microsoft/vscode-copilot-release#997] opened 2024-03-04 16:26 UTC
- VS Code Version: 1.87.0
- OS Version: Windows 11 Enterprise 22631.3155
- Logs: 

Steps to Reproduce:

1. Use Copilot chat to generate some piece of code
2. Try to debug project. `npm run build --watch` exits with errors
4. VS Code is trying to validate cached files. I can't find where these files are stored or delete them.

<img width="1201" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/13313748/4f2e3fab-0e5f-468b-96e1-490b8519c00a">

**Comment by fokusuma** [comment] 2024-03-05 07:49
I also have this issue 
<img width="1094" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/47457477/e112c76a-cafe-40d7-9afc-69499e6dcc41">

**Comment by Hi99s** [comment] 2024-03-07 06:08
me too

**Comment by frederik-wolf** [comment] 2024-03-07 08:05
I tried installing versions up until 0.10.0 and also the pre-release version. All of them didn't resolve the issue. However, in older versions the chat couldn't load but yet still the validation (TypeScript for me) showed findings in the problems tab.

Also happy to provide any further information required to resolve this issue.

**Comment by mjbvz** [comment] 2024-03-07 17:29
Duplicate of https://github.com/microsoft/vscode/issues/206644. Fixed in the latest VS Code insiders build

**Closed by mjbvz** 2024-03-07 17:29 UTC
Labels: triage-needed
