### ISSUE TITLE
Internal server error occured

### ISSUE THREAD

**Issue by sdg9670** [microsoft/vscode-copilot-release#1400] opened 2024-07-16 00:54 UTC
- Copilot Chat Extension Version: v0.17.1
- VS Code Version: 1.91.1
- OS Version: mac 14.5
- Logs:
```
2024-07-16 09:51:07.261 [info] [FetcherService] Using the Helix fetcher.
2024-07-16 09:51:07.261 [info] [gitExtensionService] Initializing Git extension service.
2024-07-16 09:51:07.261 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-07-16 09:51:07.261 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-07-16 09:51:07.261 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-07-16 09:51:07.261 [info] [auth] Logged in as sdg9670
2024-07-16 09:51:07.261 [info] [auth] Logged in as sdg9670
2024-07-16 09:51:07.632 [info] [chat] copilot token chat_enabled: true
2024-07-16 09:51:07.632 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-07-16 09:51:07.645 [info] [auth] Got Copilot token for sdg9670
2024-07-16 09:51:07.676 [info] [chat] copilot token chat_enabled: true
2024-07-16 09:51:07.676 [info] [auth] Got Copilot token for sdg9670
2024-07-16 09:51:07.680 [info] [auth] Logged in as sdg9670
2024-07-16 09:51:07.680 [info] [chat] copilot token chat_enabled: true
2024-07-16 09:51:07.681 [info] [auth] Got Copilot token for sdg9670
2024-07-16 09:51:53.003 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 13314 ms
2024-07-16 09:51:53.005 [info] [chat fetch] Request ID for failed request: , 94bc968d-4ae5-4838-9337-448222083035
2024-07-16 09:52:02.422 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2970 ms
2024-07-16 09:52:02.423 [info] [chat fetch] Request ID for failed request: , 29692b77-772d-4920-ab0f-01056ba52597
```
<img width="255" alt="image" src="https://github.com/user-attachments/assets/4c12beb3-cdda-4f8a-a8af-3a4d14d82e2d">

All requests have failed.

**Comment by Rizumu85** [comment] 2024-07-16 01:00
![image](https://github.com/user-attachments/assets/0dcb83a9-1fff-4b50-9022-eb552f214d67)
same

**Comment by rantillon** [comment] 2024-07-16 01:02
![image](https://github.com/user-attachments/assets/b2482dd2-7397-4277-a5b0-3543497c08d7)

It started like 15 minutes ago.

**Comment by emouawad** [comment] 2024-07-16 01:04
Duplicate of issue  #1384

**Comment by Steveorevo** [comment] 2024-07-16 01:18
Ditto. Simply broken. 
```
2024-07-15 18:14:56.157 [info] [auth] Logged in as Steveorevo
2024-07-15 18:14:56.160 [info] [chat] copilot token chat_enabled: true
2024-07-15 18:14:56.160 [info] [auth] Got Copilot token for Steveorevo
2024-07-15 18:14:56.431 [info] [chat] copilot token chat_enabled: true
2024-07-15 18:14:56.431 [info] [auth] Got Copilot token for Steveorevo
2024-07-15 18:16:01.907 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 22789 ms
2024-07-15 18:16:01.908 [info] [chat fetch] Request ID for failed request: , 18300b9c-7c3a-411e-8857-50e11a065b31
2024-07-15 18:16:07.900 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 5762 ms
2024-07-15 18:16:07.900 [info] [chat fetch] Request ID for failed request: , 36b456b2-086f-46b9-99f2-48c759cec470
```

**Comment by VishalKuruganti** [comment] 2024-07-16 01:20
ditto. 👎

**Comment by satanupup** [comment] 2024-07-16 01:22
500 Internal Server Error

**Comment by dazuiba** [comment] 2024-07-16 01:24
same for me

**Comment by ImmortalCi** [comment] 2024-07-16 01:27
The same problem.

**Comment by weinaike** [comment] 2024-07-16 01:29
the same for me

**Comment by daanishnasir** [comment] 2024-07-16 01:31
server must be down

**Comment by zhiyuanpeng** [comment] 2024-07-16 01:31
same on my side

**Comment by nhokmoon** [comment] 2024-07-16 01:33
It has been happening very frequently recently

**Comment by dream2333** [comment] 2024-07-16 01:36
Same issue，it makes me sad. I don't even know how to work without it

**Comment by m930406** [comment] 2024-07-16 01:47
![截圖 2024-07-16 上午9 46 46](https://github.com/user-attachments/assets/5bd36681-31d7-480a-b02e-1a2657205c45)

500 Internal Server Error

**Comment by kurobaradev** [comment] 2024-07-16 01:51
same issue

**Comment by markopetrovic239** [comment] 2024-07-16 01:54
🔥 🔥 🔥 HELP🔥 🔥 🔥

**Comment by locnp13** [comment] 2024-07-16 01:59
It is same for me. Gitcopilot was unstable around one week ago

**Comment by knito** [comment] 2024-07-16 02:03
I am facing same issue
<img width="257" alt="image" src="https://github.com/user-attachments/assets/ba2a7e39-55b8-487c-a8cc-2129560315b3">

**Comment by dong-personal** [comment] 2024-07-16 02:44
it can work now for me

**Comment by Kenny-Korea** [comment] 2024-07-16 02:51
now it works for me

**Comment by ulugbekna** [comment] 2024-07-16 12:40
Same as https://github.com/microsoft/vscode-copilot-release/issues/1402

**Closed by ulugbekna** 2024-07-16 12:40 UTC
Labels: triage-needed
