### ISSUE TITLE
@workspace not working properly

### ISSUE THREAD

**Issue by navidrigi** [microsoft/vscode-copilot-release#687] opened 2023-12-19 14:08 UTC
- VS Code Version: 1.85.1
- OS Version: macOS 10.15.7 (19H2026)
- Logs: Encountered an error while deciding what workspace information to collect: failed

Starting from today, it only throws this error, all the time.
No matter whether it is a simple question or a complex log, only errors are happened.

**Comment by sbatten** [comment] 2023-12-21 01:59
@mjbvz what error logs can we collect currently for this?

**Comment by MikeT2424** [comment] 2024-01-13 00:36
I am also seeing this error for every question I ask with @workspace.

**Comment by digitarald** [comment] 2024-01-23 16:23
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/618#issuecomment-1904843603

**Closed by digitarald** 2024-01-23 16:23 UTC
