### ISSUE TITLE
Can't get response when first question is not "Hi"?

### ISSUE THREAD

**Issue by luokebi** [microsoft/vscode-copilot-release#230] opened 2023-06-10 02:17 UTC
- VS Code Version: 1.79.0
- OS Version: MacOS 13.4
- Logs:

Steps to Reproduce:

Open a new chat and ask, "javascript array unique" It keeps thinking and doesn't provide an answer. However, if I start with a simple greeting like "Hi" in the first question of the chat, it works fine, and the following questions work fine as well even if I ask "javascript array unique"

**Comment by davecheney** [comment] 2023-06-10 05:02
![Screenshot 2023-06-10 at 15 02 09](https://github.com/microsoft/vscode-copilot-release/assets/7171/4fe3931f-fcab-471b-aba5-b6acfbe29131)
@luokebi works for me

**Comment by luokebi** [comment] 2023-06-10 05:10
@davecheney In my situation, it works in the insider version but not in the stable version. Or it is much longer than "Hi" and the following questions after "Hi"

**Comment by FunJoo** [comment] 2023-06-10 09:59
I have the same problem .....
OS Version: Windows 11

**Comment by FunJoo** [comment] 2023-06-10 10:12
It happened at a few days before, I tried to use proxy and fixed it. 
But today proxy doesn't work.
但是看了下我跟楼主的属性，这应该是中国特色网络问题吧。。。

**Comment by gprethesh** [comment] 2023-06-12 07:16
yes if you select a code and ask for issues it keeps thinking.. without any response. if you start with hello or hi it will respond and from next attempt it will provide answers.

**Comment by ulugbekna** [comment] 2023-06-13 09:06
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/205

**Closed by ulugbekna** 2023-06-13 09:06 UTC
Labels: triage-needed
