### ISSUE TITLE
The "Apply in Editor" fails with spaces in path

### ISSUE THREAD

**Issue by VKrishna04** [microsoft/vscode-copilot-release#3318] opened 2024-12-17 10:30 UTC
Type: <b>Bug</b>

1. Please take an file with path where the parent directories have 2 or more words seperated by whitespace. eg "V:\Code\My Python Life\Python - Practice\idle_shutdown.py"
2. Now work in that file normally and in chat ask for "Apply in Editor" and it will start applying in a new file with the name till the whitespace "V:\Code\My" 

So, i request all the paths be placed in as a single string so those paths with whitespaces so that "Apply in Editor" can be used again.

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (10.09GB free)|
|Process Argv|V:\\Code\\.vscode\\.vscode\\Coding.code-workspace --crash-reporter-id 5fb29788-0a73-4b17-856e-b75016cbd977|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by aeschli** [comment] 2024-12-19 15:38
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/3211

**Closed by aeschli** 2024-12-19 15:38 UTC
Labels: bug, chat-apply-changes
