### ISSUE TITLE
`/fix` yields: "Unrecognized language: r", despite generating suggestions

### ISSUE THREAD

**Issue by ryandward** [microsoft/vscode-copilot-release#469] opened 2023-10-10 14:19 UTC
## Description
When using the `/fix` command in Copilot within a file written in R, the message "Unrecognized language: r" appears. This is inconsistent with the fact that Copilot can generate suggestions for the R language.

## VS Code Version Details:

- **Version**: 1.84.0-insider
- **Commit**: 55d1cfea45b665bb54e46d11bd3ccddf9e66108b
- **Date**: 2023-10-09T06:11:32.070Z
- **Electron**: 25.8.4
- **ElectronBuildId**: 24154031
- **Chromium**: 114.0.5735.289
- **Node.js**: 18.15.0
- **V8**: 11.4.183.29-electron.0
- **OS**: Linux x64 6.5.5-arch1-1

## Steps to Reproduce:

1. Open an R script file within VS Code.
2. Begin typing a standard R command.
3. Notice that Copilot generates suggestions as expected.
4. Use the `/fix` command.
5. Observe the "Unrecognized language: r" message.
6. Attempt to run a command with the editor path in terminal.
7. Encounter error: "Command 'R: Run Command With Editor Path in Terminal' resulted in an error: Cannot read properties of undefined (reading 'replace')".

## Expected Behavior
The `/fix` command should recognize R as a valid language, especially when suggestions for R are being generated without issues.

## Actual Behavior
The `/fix` command results in an "Unrecognized language: r" message, even though suggestions for R code are provided.

## Additional Context

- Copilot seems to understand and suggest R code.
- The error only appears when using the `/fix` command.
- No logs seem to be generated in Copilot output or Copilot chat output.

**Comment by vox-koracz** [comment] 2023-10-10 18:03
I'm also having this error with PHP.

**Comment by Poldus87** [comment] 2023-10-10 19:36
Same problem with PHP and HTML.

**Comment by AshLeece** [comment] 2023-10-10 20:40
And Dart, feeling there is a common theme...

**Comment by YoraiLevi** [comment] 2023-10-11 01:11
Unrecognized language powershell, despite working amazingly the entire last month.

**Comment by cardei** [comment] 2023-10-11 07:44
Hi there, also PHP is not working for me :( 
Any idea of what is happening or how can be fixed ?
Thanks!

**Comment by junniest** [comment] 2023-10-11 08:58
Just got the same issue with Rust ):

**Comment by klejvi33** [comment] 2023-10-11 09:48
same issue with php

**Comment by markusa380** [comment] 2023-10-11 15:20
Same with rust.

**Comment by YoraiLevi** [comment] 2023-10-11 17:24
Seem to work again? at least for powershell

**Comment by caibimiaokong** [comment] 2023-10-12 06:37
![image](https://github.com/microsoft/vscode-copilot-release/assets/90626136/ab8cd919-3399-4532-b016-5b070eb5f839)
same with dart

**Comment by Maitre999** [comment] 2023-10-12 09:28
Not working anymore for Astro Framework, "Unrecognized language: astro"

**Comment by DanielBruz** [comment] 2023-10-12 12:27
same issue with php

**Comment by TimotheFCN** [comment] 2023-10-12 12:29
Can confirm that it stopped working with svelte since a few days

**Comment by arenaaz** [comment] 2023-10-13 02:04
same issue with php

**Comment by zayman2045** [comment] 2023-10-13 04:43
bump Rust

**Comment by philhoyt** [comment] 2023-10-13 13:13
Same issue with PHP

**Comment by ulugbekna** [comment] 2023-10-13 13:21
cc @aiday-mar

**Comment by Tfc538** [comment] 2023-10-13 15:01
I got the same issue for lua (CfxLUA) and markdown

**Comment by lyk-antrop** [comment] 2023-10-13 21:51
The same with me (PHP) just now. Not only `/fix`, but a general code chat too. Commands `/explain` and `/doc` seem fine.

**Comment by tmtiwari** [comment] 2023-10-15 02:42
Not working in dart and golang too. looks like it's broken globally?

**Comment by FirmamentWu** [comment] 2023-10-16 02:38
same with c 
<img width="720" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/63577034/9fd96486-eaec-4e0e-b561-1c8f60d7f8ac">

**Comment by henke443** [comment] 2023-10-16 09:08
Same with Rust and SQL

**Comment by aiday-mar** [comment] 2023-10-16 09:48
Hi thank you all for commenting on this issue and apologies for the bug. This issue should be fixed with the PR https://github.com/microsoft/vscode-copilot/pull/1643. For those who are on Insiders, the bug should be fixed if you switch to the latest pre-release extension. For those on stable, it appears that a new pre-release has not been made yet that contains the fix. The pre-release/release should be available soon.

**Comment by ZombieHarvester** [comment] 2023-10-18 14:57
Hi @aiday-mar 
I'm still facing this issue 

![image](https://github.com/microsoft/vscode-copilot-release/assets/923510/02537a4c-bbb5-4b7c-ae93-32c219dd3069)

Version: 1.84.0-insider (Universal)
Commit: 58bdf2c7c40be6f4494ae35a09528708832cf357
Date: 2023-10-18T05:50:51.391Z
Electron: 25.9.1
ElectronBuildId: 24472542
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

Copilot v1.127.498 pre-release Last updated 2023-10-18, 15:40:31

**Comment by klejvi33** [comment] 2023-10-18 15:03
Fixed for php

**Comment by mdnyeemakhtar** [comment] 2023-10-18 23:33
Same for shellscript
<img width="658" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/67909307/4809a504-1a42-46f3-8c3b-4dc4c05356f8">

**Comment by ZombieHarvester** [comment] 2023-10-19 09:00
@aiday-mar 

Copilot v1.127.500
Copilot chat v0.9.2023101802

**Comment by carlosmorales125** [comment] 2023-10-20 15:07
same:
![Screenshot 2023-10-20 at 11 07 02 AM](https://github.com/microsoft/vscode-copilot-release/assets/6589514/ae075b40-03ac-4354-ba56-f0c3b5240743)

**Comment by klejvi33** [comment] 2023-10-20 15:18
only javascript seems to work from the ones ive tested so far

**Comment by EdilCamil** [comment] 2023-10-20 21:25
I have the same issue here with html and css. Any solution for that?

**Comment by EdilCamil** [comment] 2023-10-20 21:33
Fixed. The problem is with the latest version of copilot. Download the previous and it should work.

**Comment by aiday-mar** [comment] 2023-10-21 07:27
Hey all, little update, for the users on stable, the latest version of copilot has not come out yet because it will come after vscode stable itself is updated (for API compatibility reasons).

**Comment by rbuckland** [comment] 2023-10-22 06:35
As alluded by many above - it does not work for all / any language. 
rust

![image](https://github.com/microsoft/vscode-copilot-release/assets/1148383/e027a8d7-e8b0-4ce5-967d-b116118983f9)
Thanks @EdilCamil  and @aiday-mar  

The version 
![image](https://github.com/microsoft/vscode-copilot-release/assets/1148383/f49f2de3-1ad2-42d9-9e22-a9757dc91ba3)
Co-pilot 1.128.0 does not work. 

I have randomly picked 1.123.0 and 1.115.430 - and it does not work.
* v1.123.0 - 2 weeks old
* v1.115.430 - 2 months old

**Comment by rbuckland** [comment] 2023-10-22 06:41
Installing v0.7.1 (2 months old) of copilot chat, resolves the issue.

**Comment by tomdps** [comment] 2023-10-24 10:01
Same with LaTex

**Comment by Kaloszer** [comment] 2023-10-25 08:06
Same with powershell

**Comment by alvaro17f** [comment] 2023-10-25 09:17
same with rust

**Comment by ryandward** [comment] 2023-10-26 02:40
Sadly, even with the newest version `v0.9.2023102501` I am still having the same problems with R.

**Comment by mdnyeemakhtar** [comment] 2023-10-26 19:41
> Hi @ZombieHarvester what is your version of the copilot-chat extension? It is this one that contains the fix.
> 
> Hi @mdnyeemakhtar, the fix should be in version [v0.9.2023100401](https://github.com/microsoft/vscode-copilot/releases/tag/v0.9.2023100401) and above. Currently it looks like stable can only install up to version v.0.8.2 maximum.

Hi @aiday-mar I tried below versions on VSCode in insider version and it still doesn't work.

VS Code Version: 1.84.0-insider
GitHub Copilot - v1.130.515
GitHub Copilot Chat - v0.9.2023102601

**Comment by Nimakai** [comment] 2023-10-27 23:17
Same with rust

**Comment by movy** [comment] 2023-10-28 13:44
Same with vue and jsonc

**Comment by Tfc538** [comment] 2023-10-28 19:43
Still got the issue with LUA, even on VS Code insiders

**Comment by movy** [comment] 2023-10-30 04:44
So I guess the real danger of AI is when so many people rely on it and it suddenly stops working :) 3 days of this and we're back to caves.

**Comment by aiday-mar** [comment] 2023-10-31 16:47
Hey all, my apologies for this bug. I though it was fixed and we just found out the likely root cause of this issue. I have a PR ready: https://github.com/microsoft/vscode-copilot/pull/2554

**Comment by scottspiller** [comment] 2023-11-01 19:33
same with vue.  I got the new update (v1.133.0) on insiders (1.84).
![image](https://github.com/microsoft/vscode-copilot-release/assets/8961748/8ab12407-44a6-4854-82c5-6365e6f1d71e)

**Comment by krflol** [comment] 2023-11-01 20:20
Im still getting this issue with rust

**Comment by aiday-mar** [comment] 2023-11-02 08:33
Hey all, the fix was merged yesterday (with a delay of one day) so it probably was not available in yesterday's version. If you continue seeing this issue, can you please paste here a minimally reproducible example of code which causes this error? I will be debugging.

**Comment by alvaro17f** [comment] 2023-11-02 10:25
@aiday-mar It's not working with rust in Linux:
![image](https://github.com/microsoft/vscode-copilot-release/assets/89421445/d0e7eb06-f85a-44a3-b420-30ba47c2724f)

Github Copilot Chat terminal output:
![image](https://github.com/microsoft/vscode-copilot-release/assets/89421445/ca7fb38e-b7d2-4c92-b710-c6c3b2981e14)

**Comment by aiday-mar** [comment] 2023-11-02 10:53
Hi @alvaro17f can you please paste here a minimally reproducible example of the code that is generating this error? I will debug it.

**Comment by aiday-mar** [comment] 2023-11-02 13:53
Hi @SudoCerb, thank you for letting me know. Could you please include a minimally reproducible example of the code generating your error? To debug I need to reproduce the exact error.

**Comment by ZombieHarvester** [comment] 2023-11-02 17:24
Hi @aiday-mar 

here is how to reproduce. 

I'm on 
VSCode: 1.85.0-insider (Universal) Commit: a9d8fbca9ec9a7914f2077a83ca66a08c7e10f83
Copilot v1.133.529
Copilot Chat v0.11.2023110201

1. Create new tab, set language to Elixir
2. Paste `"\ud83d"`
3. run `/fix invalid or reserved Unicode code point`
4. Get `unrecognized language: Elixir`

![image](https://github.com/microsoft/vscode-copilot-release/assets/923510/3203b3f3-9083-43ff-8031-eea76f2e33b8)

**Comment by krflol** [comment] 2023-11-02 17:44
Rust example

```
fn main(){
    println!("Hello, world!);
}

```
<img width="331" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/23039693/52532e4a-aeee-4137-a8ec-6ef076e1a00d">

**Comment by ptepper** [comment] 2023-11-02 22:00
I'm seeing the same error for dart in Github Copilot plugin versions 1.133.0 (release) and 1.133.530 (pre-release). In general, to reproduce:

1. Write some code with a syntax error (squiggly red underline)
2. Click the lightbulb -> Select Fix with Copilot. 

You should see "Unrecognized language: dart", and apparently other languages as well from previous comments.

**Comment by aiday-mar** [comment] 2023-11-03 08:43
Hi @ulugbekna, looking at the result above

```
2023-11-02T17:26:29.716Z [ERROR] [asyncCompute] Failed to compute async parser based result: (Error) Unrecognized language: elixir
2023-11-02T17:26:29.717Z [ERROR] [asyncCompute] Failed to compute async parser based result: (Error) Unrecognized language: elixir
```

It looks a bit like the other error that was assigned to you, I will investigate.

**Comment by aiday-mar** [comment] 2023-11-03 09:00
Hi for the examples you gave: @alvaro17f , @ZombieHarvester , @krflol, @ptepper, could you please post here the output from the view `Github Copilot Chat`. 

As well as this, could you open the developer tools with `Developer : Toggle Developer Tools` from the command palette and copy paste here the error you see in the console?

I am currently not able to reproduce the errors you posted and am lacking information to track the error down. Thank you all.

**Comment by aiday-mar** [comment] 2023-11-03 10:15
Hey all, after some digging, I was finally able to reproduce the error on my machine. I had some settings enabled which appear to affect the copilot chat errors, which I was not seeing correctly. I have a fix here (https://github.com/microsoft/vscode-copilot/pull/2606). Hopefully it is the last one.

**Comment by SudoCerb** [comment] 2023-11-03 10:18
> Hey all, after some digging, I was finally able to reproduce the error on my machine. I had some settings enabled which appear to affect the copilot chat errors, which I was not seeing correctly. I have a fix here (https://github.com/microsoft/vscode-copilot/pull/2606). Hopefully it is the last one.

Thank you!

**Comment by alvaro17f** [comment] 2023-11-03 11:08
Thank you @aiday-mar

**Comment by ptepper** [comment] 2023-11-05 02:56
> Hey all, after some digging, I was finally able to reproduce the error on my machine. I had some settings enabled which appears to have affected the copilot chat errors, which I was not seeing correctly. I have a fix. Hopefully it is the last one.

Hey @aiday-mar - sorry just saw this, let me know if you need anything else. This was not occuring in Github Co-pilot Chat, it's the Github Co-pilot plugin, and it only shows up in the VSCode UI (not chat), which others have pasted screenshots of - what I saw looks just like what has been posted. I just updated to Github Copilot plugin Pre-Release v1.133.531 and it's still there. If you end up pushing a fix, it would be great if you can post a note about it here. Thank you so much for efforts on this and fast responses!

**Comment by koncio18** [comment] 2023-11-08 16:37
Same issue here and in /fix function
v1.135.0 installed today
in many places in my prestashop code




--------
 protected function shouldEnableAddToCartButton(array $product)
    {
        if (($product['customizable'] == 2 || !empty($product['customization_required']))) {
            $shouldShowButton = false;

            if (isset($product['customizations'])) {
                $shouldShowButton = true;
                foreach ($product['customizations']['fields'] as $field) {
                    if ($field['required'] && !$field['is_customized']) {
                        $shouldShowButton = false;
                    }
                }
            }
        } else {
            $shouldShowButton = true;
        }

        $shouldShowButton = $shouldShowButton && $this->shouldShowAddToCartButton($product);

        if ($product['quantity'] <= 0 && !$product['allow_oosp']) {
            $shouldShowButton = false;
        }

        return $shouldShowButton;
    }

**Comment by a-nldisr** [comment] 2023-11-09 20:18
Got the error today with jsonnet

**Comment by aiday-mar** [comment] 2023-11-10 13:52
Hi @koncio18 thank you for filing the issue. What version of copilot-chat extension you are running? I just verified if the fix is in stable VS Code and it appears to be the case on my machine. If you are not running the latest Insiders/Stable/Copilot-Chat extension, can you update all these software and let me know if you continue seeing the error? Also I wanted to verify that the code snippet you posted is JavaScript code?

Hi @ptepper thank you for the detailed comment. The inline chat (VS Code UI chat I think you are referring to) as well as the panel chat are both developed inside of the copilot-chat extension. It is this extension that should contain the fix. Could you update the editor as well as the extension and let me know if you continue seeing the error. In case you do, could you paste a snippet of the code with reproduces the error as well as a mention of the language you are running?

Hi @a-nldisr, thanks for commenting. As I wrote above, could you upgrade the editor and the extension copilot-chat to the latest versions, then if you continue seeing the error paste here an example of the code reproducing the error as well as a mention of the language?

**Comment by ZombieHarvester** [comment] 2023-11-11 19:12
@aiday-mar I can confirm that it is fixed for Elixir

Copilot Chat v0.11.2023111001

**Closed** 2023-12-04 01:03 UTC
Labels: /fix, candidate
