### ISSUE TITLE
No History being written, ever (no victor?)

### ISSUE THREAD

**Issue by NidusUmbra** [microsoft/vscode-copilot-release#291] opened 2023-06-30 12:00 UTC
I always make sure to update both the Insiders build I'm working in, as well as both Copilot extensions. I've never had any chat history stored so far, unfortunately, if the textbox that pops up when pressing "Show History" is any indication. Alls I can do is keep one conversation going for each workspace and/or destructively close it when I feel it contained no valuable insights. There is no accessible history within nor between workspaces. I am not running VS Code Insiders with elevated privilege. I have a regular VS code installation on the same machine and drive. I have a fully activated subscription of Copilot (i.e. not in Trial mode).

- VS Code Version / - OS Version / + more :
Version: 1.80.0-insider (user setup)
Commit: 7406a9bdfca18f82a3977ba5eac908d41df7ccac
Date: 2023-06-30T05:33:00.101Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
- Logs:
[logs.zip](https://github.com/microsoft/vscode-copilot-release/files/11915972/logs.zip)

Steps to Reproduce:
1. Start a chat
2. Chat away
3. Close chat 
4. Press the "Show History" button.

**Comment by NidusUmbra** [comment] 2023-07-19 12:17
> Could you run F1 > "Set Log Level" > "Trace", start a chat, reload the window, then share the log from the "Window" output channel?
> 
> Also, if you have a chat and reload the window, is the chat restored?

I think that's your job?

**Comment by roblourens** [comment] 2023-07-24 21:38
I haven't seen this myself, and I haven't seen any other reports of an issue like this. If you have the time, it would be helpful to check for for errors or help me try to narrow down the issue. If not, that's ok, but I probably won't be able to do anything about the issue on my own.

**Comment by alefragnani** [comment] 2023-09-27 01:01
Hi @roblourens ,

I just noticed my sessions are not being restored also. I'm not exactly when it stopped working, because recently I was using playing a bit more with the editor experience.

I'm not sure which parts from the log are more relevant, but it seems the extension recognizes the previous session right after the reload, but for some reason, it is not being loaded.

Added a piece of the log around the _reload_ command, which was called right after asking Copilot Chat to `/explain` some piece of code

```log
2023-09-26 21:30:27.005 [trace] CommandService#executeCommand _setContext
2023-09-26 21:30:27.006 [error] [Extension Host] 2023-09-27T00:30:26.999Z [ERROR] [chat fetch] Unhandled status from server: 400 error serving request: failed to check intent: bad request: role must be "user", got "assistant"
2023-09-26 21:30:27.006 [trace] ChatModel#acceptNewSessionState
2023-09-26 21:30:28.532 [trace] KeybindingService#dispatch / [ No matching keybinding ]
2023-09-26 21:30:28.648 [trace] KeybindingService#dispatch E [ No matching keybinding ]
2023-09-26 21:30:28.817 [trace] KeybindingService#dispatch X [ No matching keybinding ]
2023-09-26 21:30:28.903 [trace] KeybindingService#dispatch P [ No matching keybinding ]
2023-09-26 21:30:29.098 [trace] KeybindingService#dispatch L [ No matching keybinding ]
2023-09-26 21:30:29.252 [trace] KeybindingService#dispatch A [ No matching keybinding ]
2023-09-26 21:30:29.337 [trace] KeybindingService#dispatch I [ No matching keybinding ]
2023-09-26 21:30:29.402 [trace] KeybindingService#dispatch N [ No matching keybinding ]
2023-09-26 21:30:29.705 [trace] KeybindingService#dispatch Tab [ Will dispatch command acceptSelectedSuggestion ]
2023-09-26 21:30:29.706 [trace] CommandService#executeCommand acceptSelectedSuggestion
2023-09-26 21:30:29.915 [trace] KeybindingService#dispatch Enter [ Will dispatch command chat.action.acceptInput ]
2023-09-26 21:30:29.916 [trace] CommandService#executeCommand chat.action.acceptInput
2023-09-26 21:30:29.916 [trace] ChatService#sendRequest: sessionId: 087c1a9e-cd69-477c-a144-37074d389637, message: /explain }
2023-09-26 21:30:29.931 [trace] ChatListDelegate#getHeight: response, height=417
2023-09-26 21:30:29.931 [trace] ChatListDelegate#getHeight: request, height=200
2023-09-26 21:30:29.932 [trace] ChatListDelegate#getHeight: response, height=200
2023-09-26 21:30:29.932 [trace] ChatListItemRenderer#renderElement: response, index=4
2023-09-26 21:30:29.938 [trace] ChatListItemRenderer#renderElement: request, index=5
2023-09-26 21:30:29.941 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:29.943 [trace] ChatListItemRenderer#renderElement: request, index=1
2023-09-26 21:30:29.944 [trace] ChatListItemRenderer#renderElement: response, index=2
2023-09-26 21:30:29.960 [error] [Extension Host] 2023-09-27T00:30:29.951Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-09-26 21:30:29.961 [error] [Extension Host] 2023-09-27T00:30:29.953Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-09-26 21:30:29.961 [error] [Extension Host] 2023-09-27T00:30:29.955Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-09-26 21:30:29.997 [error] [Extension Host] 2023-09-27T00:30:29.993Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-09-26 21:30:29.999 [error] [Extension Host] 2023-09-27T00:30:29.994Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-09-26 21:30:30.002 [trace] ChatService#sendRequest: Provider returned id for session 087c1a9e-cd69-477c-a144-37074d389637, 70d2e0a1-43f5-4af8-bfcf-ff3ba1aa6f46
2023-09-26 21:30:31.403 [trace] ChatService#sendRequest: Provider returned progress for session 087c1a9e-cd69-477c-a144-37074d389637, 268 chars
2023-09-26 21:30:31.403 [trace] ChatResponseViewModel#onDidChange: Update- got 46 words over 1473ms = 31.228784792939578 words/s. undefined words are rendered.
2023-09-26 21:30:31.404 [trace] ChatListDelegate#getHeight: response, height=83
2023-09-26 21:30:31.404 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:31.406 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:32.328 [trace] ChatService#sendRequest: Provider returned progress for session 087c1a9e-cd69-477c-a144-37074d389637, 288 chars
2023-09-26 21:30:32.328 [trace] ChatResponseViewModel#onDidChange: Update- got 94 words over 2398ms = 39.199332777314424 words/s. 37 words are rendered.
2023-09-26 21:30:32.328 [trace] ChatListDelegate#getHeight: response, height=147
2023-09-26 21:30:32.329 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:32.329 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:33.349 [trace] ChatService#sendRequest: Provider returned progress for session 087c1a9e-cd69-477c-a144-37074d389637, 301 chars
2023-09-26 21:30:33.350 [trace] ChatResponseViewModel#onDidChange: Update- got 146 words over 3419ms = 42.70254460368529 words/s. 81 words are rendered.
2023-09-26 21:30:33.350 [trace] ChatListDelegate#getHeight: response, height=272
2023-09-26 21:30:33.351 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:33.352 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:34.066 [trace] ChatService#sendRequest: Provider returned progress for session 087c1a9e-cd69-477c-a144-37074d389637, 208 chars
2023-09-26 21:30:34.067 [trace] ChatResponseViewModel#onDidChange: Update- got 182 words over 4136ms = 44.003868471953574 words/s. 119 words are rendered.
2023-09-26 21:30:34.067 [trace] ChatListDelegate#getHeight: response, height=372
2023-09-26 21:30:34.068 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:34.068 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:34.678 [trace] ChatService#sendRequest: Provider returned progress for session 087c1a9e-cd69-477c-a144-37074d389637, 381 chars
2023-09-26 21:30:34.679 [trace] ChatResponseViewModel#onDidChange: Update- got 249 words over 4748ms = 52.44313395113732 words/s. 154 words are rendered.
2023-09-26 21:30:34.679 [trace] ChatListDelegate#getHeight: response, height=474
2023-09-26 21:30:34.680 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:34.681 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:34.688 [trace] ChatModel#acceptNewSessionState
2023-09-26 21:30:34.689 [trace] ChatResponseViewModel#onDidChange: Update- got 249 words over 4759ms = 52.32191636898508 words/s. 154 words are rendered.
2023-09-26 21:30:34.691 [trace] ChatListDelegate#getHeight: response, height=474
2023-09-26 21:30:34.692 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:34.693 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:34.698 [trace] ChatService#sendRequest: Provider returned response for session 087c1a9e-cd69-477c-a144-37074d389637
2023-09-26 21:30:35.129 [trace] Layout#layout, height: 907, width: 1586
2023-09-26 21:30:35.204 [trace] Layout#layout, height: 907, width: 1592
2023-09-26 21:30:35.282 [trace] Layout#layout, height: 907, width: 1612
2023-09-26 21:30:35.341 [trace] ChatResponseViewModel#onDidChange: Update- got 249 words over 5407ms = 46.051414832624374 words/s. 194 words are rendered.
2023-09-26 21:30:35.343 [trace] ChatListDelegate#getHeight: response, height=595
2023-09-26 21:30:35.344 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:35.344 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:35.352 [trace] ChatResponseViewModel#onDidChange: Done- got 249 words over 5420ms = 45.94095940959409 words/s. 199 words are rendered.
2023-09-26 21:30:35.352 [trace] ChatListDelegate#getHeight: response, height=595
2023-09-26 21:30:35.357 [trace] ChatListItemRenderer#renderElement: response, index=6
2023-09-26 21:30:35.358 [trace] ChatListItemRenderer#renderElement: start progressive render response, index=6
2023-09-26 21:30:35.358 [trace] ChatListItemRenderer#runProgressiveRender: end progressive render, index=6 and clearing renderData, response is complete, index=6
2023-09-26 21:30:35.392 [trace] Layout#layout, height: 907, width: 1622
2023-09-26 21:30:35.449 [trace] Layout#layout, height: 907, width: 1640
2023-09-26 21:30:35.517 [trace] Layout#layout, height: 907, width: 1653
2023-09-26 21:30:35.565 [trace] Layout#layout, height: 907, width: 1655
2023-09-26 21:30:35.632 [trace] Layout#layout, height: 907, width: 1656
2023-09-26 21:30:44.344 [trace] [History stack global-default]: notifyNavigation() (editor: untitled:Untitled-1, event: user)
2023-09-26 21:30:44.344 [trace] [History stack global-default]: notifyNavigation() not ignoring (editor: untitled:Untitled-1, event: user)
2023-09-26 21:30:44.344 [trace] [History stack global-default]: onSelectionAwareEditorNavigation() (editor: untitled:Untitled-1, event: user)
2023-09-26 21:30:44.344 [trace] [History stack global-default]: replace() (editor: untitled:Untitled-1, event: <none>)
2023-09-26 21:30:44.345 [trace] [History stack global-default]: index: 0, navigating: false
- group: 0, editor: untitled:Untitled-1, selection: line: 5-5, col:  2-2
			
2023-09-26 21:30:44.739 [trace] CommandService#executeCommand _setContext
2023-09-26 21:30:50.584 [trace] ChatService#onWillSaveState: Persisting 1 sessions
2023-09-26 21:30:50.585 [trace] ChatService#onWillSaveState: Persisting 12877 chars
2023-09-26 21:31:29.925 [trace] KeybindingService#dispatch Ctrl+Shift+P [ Will dispatch command workbench.action.showCommands ]
2023-09-26 21:31:29.925 [trace] CommandService#executeCommand workbench.action.showCommands
2023-09-26 21:31:30.889 [trace] KeybindingService#dispatch R [ No matching keybinding ]
2023-09-26 21:31:30.935 [trace] KeybindingService#dispatch E [ No matching keybinding ]
2023-09-26 21:31:31.282 [trace] KeybindingService#dispatch L [ No matching keybinding ]
2023-09-26 21:31:31.406 [trace] KeybindingService#dispatch O [ No matching keybinding ]
2023-09-26 21:31:31.518 [trace] KeybindingService#dispatch A [ No matching keybinding ]
2023-09-26 21:31:31.660 [trace] KeybindingService#dispatch D [ No matching keybinding ]
2023-09-26 21:31:31.850 [trace] [AiRelatedInformationService]: getRelatedInformation took 694.8999999761581ms
2023-09-26 21:31:32.292 [trace] [AiRelatedInformationService]: getRelatedInformation took 390.5ms
2023-09-26 21:31:33.817 [trace] CommandService#executeCommand workbench.action.reloadWindow
2023-09-26 21:31:33.823 [trace] [lifecycle] onBeforeUnload (reason: 3)
2023-09-26 21:31:33.827 [trace] [lifecycle] onBeforeUnload continues without veto
2023-09-26 21:31:33.828 [trace] [lifecycle] onWillUnload (reason: 3)
2023-09-26 21:31:33.830 [trace] ChatService#onWillSaveState: Persisting 1 sessions
2023-09-26 21:31:33.830 [trace] ChatService#onWillSaveState: Persisting 12877 chars
2023-09-26 21:31:33.880 [trace] ChatService#registerProvider: Disposing chat provider
2023-09-26 21:31:34.261 [trace] workbench#open(): with configuration {"_":[],"diff":false,"merge":false,"add":false,"goto":false,"new-window":false,"reuse-window":false,"wait":false,
``` 
The rest of the log, removing those _large pieces of ext/config output_. I see some _errors_ about loading VS Code config files and references to Profiles, which btw, I tested in a _no profile_ config, trying to minimize variables.

```log
2023-09-26 21:31:34.272 [trace] PolicyConfiguration#update ["update.mode"]
2023-09-26 21:31:34.280 [trace] [lifecycle] starting up (startup kind: 3)
2023-09-26 21:31:34.280 [trace] lifecycle: phase changed (value: 2)
2023-09-26 21:31:34.282 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-09-26 21:31:34.282 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-09-26 21:31:34.341 [trace] PolicyConfiguration#updatePolicyDefinitions ["security.allowedUNCHosts","security.restrictUNCAccess"]
2023-09-26 21:31:34.347 [trace] TimelineService#registerTimelineProvider: id=timeline.localHistory
2023-09-26 21:31:34.382 [debug] [DEBOUNCE: Folding] is disabled in developed mode
2023-09-26 21:31:34.383 [trace] [IE] (editor:vs.editor.ICodeEditor:1)NEW controller
2023-09-26 21:31:34.388 [trace] [History stack global-default]: notifyNavigation() (editor: untitled:Untitled-1, event: <none>)
2023-09-26 21:31:34.388 [trace] [History stack global-default]: notifyNavigation() not ignoring (editor: untitled:Untitled-1, event: <none>)
2023-09-26 21:31:34.388 [trace] [History stack global-default]: onSelectionAwareEditorNavigation() (editor: untitled:Untitled-1, event: <none>)
2023-09-26 21:31:34.388 [trace] [History stack global-default]: add() (editor: untitled:Untitled-1, event: <none>)
2023-09-26 21:31:34.389 [trace] [History stack global-default]: index: 0, navigating: false
- group: 0, editor: untitled:Untitled-1, selection: <none>
			
2023-09-26 21:31:34.397 [trace] Layout#layout, height: 907, width: 1656
2023-09-26 21:31:34.411 [trace] PolicyConfiguration#update []
2023-09-26 21:31:34.426 [trace] [IE] (editor:vs.editor.ICodeEditor:2)NEW controller
2023-09-26 21:31:34.485 [trace] Started scanning system extensions
2023-09-26 21:31:34.485 [trace] Started scanning user extensions {"$mid":1,"path":"/c:/Users/Alessandro/.vscode-insiders/extensions/extensions.json","scheme":"vscode-userdata"}
2023-09-26 21:31:34.521 [debug] Error while reading the extension cache file: /C:/Users/Alessandro/AppData/Roaming/Code - Insiders/CachedProfilesData/__default__profile__/extensions.user.cache Unable to read file 'vscode-userdata:/c:/Users/Alessandro/AppData/Roaming/Code - Insiders/CachedProfilesData/__default__profile__/extensions.user.cache' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/Alessandro/AppData/Roaming/Code - Insiders/CachedProfilesData/__default__profile__/extensions.user.cache')
2023-09-26 21:31:34.555 [debug] Using cached extensions scan result file:///c%3A/Users/Alessandro/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions
2023-09-26 21:31:34.556 [trace] Scanned system extensions: 90
2023-09-26 21:31:34.556 [debug] ComputeTargetPlatform: win32-x64
2023-09-26 21:31:34.627 [trace] [backup tracker] scheduling backup untitled:Untitled-1 
2023-09-26 21:31:34.634 [trace] [backup tracker] clearing pending backup creation untitled:Untitled-1 
2023-09-26 21:31:34.635 [trace] [backup tracker] scheduling backup untitled:Untitled-1 
2023-09-26 21:31:34.653 [trace] [History stack global-default]: notifyNavigation() (editor: untitled:Untitled-1, event: user)
2023-09-26 21:31:34.653 [trace] [History stack global-default]: notifyNavigation() not ignoring (editor: untitled:Untitled-1, event: user)
2023-09-26 21:31:34.654 [trace] [History stack global-default]: onSelectionAwareEditorNavigation() (editor: untitled:Untitled-1, event: user)
2023-09-26 21:31:34.654 [trace] [History stack global-default]: replace() (editor: untitled:Untitled-1, event: <none>)
2023-09-26 21:31:34.654 [trace] [History stack global-default]: index: 0, navigating: false
- group: 0, editor: untitled:Untitled-1, selection: line: 5-5, col:  2-2
			
2023-09-26 21:31:34.658 [trace] lifecycle: phase changed (value: 3)
2023-09-26 21:31:34.659 [trace] Renderer->SharedProcess#connect: before acquirePort
2023-09-26 21:31:34.746 [debug] [DEBOUNCE: DocumentRangeSemanticTokens] is disabled in developed mode
2023-09-26 21:31:34.747 [debug] [DEBOUNCE: Document Colors] is disabled in developed mode
2023-09-26 21:31:34.747 [debug] [DEBOUNCE: Linked Editing] is disabled in developed mode
2023-09-26 21:31:34.748 [debug] [DEBOUNCE: Links] is disabled in developed mode
2023-09-26 21:31:34.748 [debug] [DEBOUNCE: CodeLensProvide] is disabled in developed mode
2023-09-26 21:31:34.749 [debug] [DEBOUNCE: InlayHint] is disabled in developed mode
2023-09-26 21:31:34.772 [trace] Renderer->SharedProcess#connect: connection established
2023-09-26 21:31:34.773 [trace] Renderer->UtilityProcess#createWorkerChannel: connection established
2023-09-26 21:31:34.878 [trace] Error while resolving configuration file 'vscode-userdata:/c%3A/Users/Alessandro/AppData/Roaming/Code%20-%20Insiders/User/tasks.json': Unable to read file 'vscode-userdata:/c:/Users/Alessandro/AppData/Roaming/Code - Insiders/User/tasks.json' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/Alessandro/AppData/Roaming/Code - Insiders/User/tasks.json')
2023-09-26 21:31:34.898 [debug] Could not get workspace hash for forwarded ports storage key.
2023-09-26 21:31:34.901 [trace] Scanned user extensions: 27
2023-09-26 21:31:34.904 [warning] Skipping extension /c:/Users/Alessandro/.vscode-insiders/extensions/ms-vscode.js-debug-1.72.1 in favour of the builtin extension /c:/Users/Alessandro/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug.
2023-09-26 21:31:34.908 [trace] pickRunningLocation for vscode.bat, extension kinds: [ui, workspace, web], isInstalledLocally: true, isInstalledRemotely: false, preference: None => LocalProcess
2023-09-26 21:31:34.908 [trace] pickRunningLocation for vscode.clojure, extension kinds: [ui, workspace, web], isInstalledLocally: true, isInstalledRemotely: false, preference: None => LocalProcess
```

If you need more logs or info, feel free to ask. 

Hope this helps

**Comment by roblourens** [comment] 2023-09-27 01:22
Thanks @alefragnani. That shows that the sessions were saved, that happens after the reload command is issued, but it doesn't show them being restored. Was there any log after that?

If the stored data was lost somehow, there may not be a lot statement for it, but if it was retrieved but ended up malformed, there might be an error in the log for that.

**Comment by roblourens** [comment] 2023-09-27 01:39
> `2023-09-26 21:31:36.000 [trace] ChatService#constructor: Restored 1 persisted sessions`

This shows it finding the session. Is this about what you see in the "show history" view or just what you see in the chat view after reloading?

**Comment by alefragnani** [comment] 2023-09-27 01:42
I would say both. The chat window only displays the welcome message (not the previous _conversation_) and the `Show History` command is empty, with no chat to restore.

**Comment by roblourens** [comment] 2023-09-27 22:47
I can repro the issue you describe, @alefragnani. It was introduced recently, and is a little different from the one described in the OP. I will close this one to avoid confusion and open a new issue. Thanks for bringing it up.

**Closed by roblourens** 2023-09-27 22:47 UTC
Labels: bug, panel-chat

**Comment by alefragnani** [comment] 2023-09-27 23:19
That's great to hear you could reproduce the issue @roblourens . Glad to know the log was helpful.

Thank you
