### ISSUE TITLE
Code chat context of vs code window + relevant documentation web crawled for additional context.

### ISSUE THREAD

**Issue by FelixMildon** [microsoft/vscode-copilot-release#348] opened 2023-08-02 08:38 UTC
Title says it all

**Comment by lramos15** [comment] 2023-08-02 13:48
There are two issues here both of which are already mentioned in this repro.
Marking as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/200

**Closed as not planned by lramos15** 2023-08-02 13:48 UTC
Labels: duplicate

**Comment by FelixMildon** [comment] 2023-08-09 20:41
My issue is nothing like #200.

Im saying vs code copilot chat should use the vs code "open editors" as context.
