### ISSUE TITLE
Invalid progress type: {"responseId":"9f0e2baf-4359-4a32-b460-64643ffe6478"}

### ISSUE THREAD

**Issue by Nilobagotjr** [microsoft/vscode-copilot-release#587] opened 2023-11-20 15:30 UTC
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by digitarald** [comment] 2023-11-20 18:22
Duplicate of #585

**Closed by digitarald** 2023-11-20 18:22 UTC
Labels: triage-needed
