### ISSUE TITLE
chat with my pdf file 

### ISSUE THREAD

**Issue by uset82** [microsoft/vscode-copilot-release#950] opened 2024-02-24 19:02 UTC
It would be beneficial to have the capability to upload PDF files containing data requirements, previous code, instructions, and configurations similar to GPT settings

**Comment by piggyy** [comment] 2024-03-21 02:50
+1

**Comment by TylerLeonhardt** [comment] 2024-03-22 03:43
To do this, we really need custom instructions. I'm going to mark this as a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/563 once we have that, then we can talk about providing instructions in other forms.

**Closed by TylerLeonhardt** 2024-03-22 03:43 UTC
Labels: triage-needed
