### ISSUE TITLE
Cannot read properties of undefined (reading 'split') when asked for to write a function in JS

### ISSUE THREAD

**Issue by hbinraees** [microsoft/vscode-copilot-release#824] opened 2024-02-02 11:52 UTC
- VS Code Version: Version: 1.86.0 (Universal)
- OS Version: 13.6.3 (22G436)
- Logs:

Steps to Reproduce:

1. Asked co-pilot to write a function for time comparison (It wrote in Python)
2. Then asked co-pilot to convert the code in JS

**Comment by jose-gray** [comment] 2024-02-02 12:12
I'm getting this same error in the chat box in vscode when trying to ask it anything whilst code is highlighted

**Comment by GaganNarula** [comment] 2024-02-02 12:39
same issue but reverse order, original answer from copilot was in JS, asked it to convert to python and it resulted in this error

**Comment by mielpl** [comment] 2024-02-02 12:50
![image](https://github.com/microsoft/vscode-copilot-release/assets/71864316/75a83af8-3cc6-4d3a-9a28-17949f2feb23)

**Comment by Cohors1316** [comment] 2024-02-02 12:54
Adding to this. Any prompt would result in this message, regardless of selected text or not, regardless of language. Full restart, now copilot does not appear to reference files at all.

**Comment by discoursedigital** [comment] 2024-02-02 13:19
I am having the issue in Python and Javascript code analysis when inputting into the chat window.

**Comment by sam-dude** [comment] 2024-02-02 13:27
I'm experiencing the same issue too. The copilot chat only respond to the first request in a chat and subsequent resquests returns the error.

**Comment by Cohors1316** [comment] 2024-02-02 13:56
I think this is a duplicate of #821.

**Comment by digitarald** [comment] 2024-02-03 17:54
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/796#issuecomment-1925413610

**Closed by digitarald** 2024-02-03 17:54 UTC
