### ISSUE TITLE
Support grounding conversations in the whole codebase

### ISSUE THREAD

**Issue by william-kerr** [microsoft/vscode-copilot-release#87] opened 2023-05-22 21:42 UTC
Cody by Sourcegraph, is using embeddings from my private repository to return better responses than Copilot.

I just:
1. Created a Sourcegraph instance in AWS.
2. Connected it to my private GitHub repo.
3. Added my OpenAI API key so that my instance of Sourcegraph could send embeddings and chat requests to the OpenAI API.
4. Scheduled embeddings for my repo in my instance of Sourcegraph.
5. Installed Cody in VS Code and configured it to point to the URL of my instance of Sourcegraph.
6. Asked Cody to explain an obscure function that was in my private repo.

Wow, Cody gave me a detailed response about that function!  If I repeat the question in Copilot, it says, "...is not a built-in function in JavaScript or any of the mentioned technologies. Can you provide more context or information about where you encountered this function?"

**I want GitHub to generate embeddings for my entire private code repository and use those when querying GPT-4 so that Copilot responses also appear to know about all of my code.**

**Comment by tmy2017** [comment] 2023-05-23 07:44
hi @william-kerr thx for sharing your experience, just curious when you say `Created a Sourcegraph instance in AWS.` - do you also need an Enterprise license from sourcegraph? or you have it as trial license?

**Comment by william-kerr** [comment] 2023-05-23 13:36
No license needed; just launch the AWS CloudFormation stack by clicking the **Launch Stack** button on this page:
https://docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick

After it loads in around 5 minutes, visit the instance URL and create the initial user.  Then, configure the `embeddings` and `completions` as mentioned in:
https://docs.sourcegraph.com/admin/config/site_config

I also set `externalURL` to my instance URL.

There's a tab in the admin panel for hooking up the GitHub repo, and a tab for scheduling embeddings.  The embeddings job runs pretty fast.  Then, you're ready to configure the VS Code settings with your instance URL.  If you don't use GPT-4 in the API, it might throw an error some of the time when you ask Cody questions, because they sometimes send messages with more tokens than GPT-3 can handle.

**Comment by slimsag** [comment] 2023-06-01 03:45
> Created a Sourcegraph instance in AWS.

Just thought I'd mention for anyone wanting to compare (including Microsoft folks), you don't actually have to deploy on AWS like that - I work at Sourcegraph & my team has been working on a desktop Cody app. Still experimental; but [you can try it here](https://github.com/sourcegraph/sourcegraph/releases/tag/app-v2023.5.30%2B1306.85e549168c) - just note that steps 3 and 4 in this issue (adding an OpenAI key/scheduling embeddings) are still required right now to get embeddings, we're making that nicer soon.

**Comment by darshil** [comment] 2023-06-02 09:55
@slimsag Where in the Cody desktop app can I add the OpenAI Key?

**Comment by vibin** [comment] 2023-06-03 08:21
Hi @slimsag, I have cloned a repo in Sourcegraph app and created a Configuration policy under repo > embeddings. The app currently shows that indexing is in progress - is this the right way to do it?

**Comment by digitarald** [comment] 2023-06-09 22:53
Duplicate of #14

**Closed by digitarald** 2023-06-09 22:53 UTC
Labels: github-team, context-increase
