### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by dinhvankhoi-developer** [microsoft/vscode-copilot-release#295] opened 2023-07-03 06:00 UTC
Copilot responds slowly, in addition there is an error :Oops, your response got filtered. Vote down if you think this shouldn't have happened. , when replying to a content of length
![Screenshot (155)](https://github.com/microsoft/vscode-copilot-release/assets/99070105/70485d78-e86c-47b5-b6f4-e20d0c880fc5)
![image](https://github.com/microsoft/vscode-copilot-release/assets/99070105/1c6fcf2b-e4f3-436b-bb2d-2550eb00bd4d)

**Comment by stabildev** [comment] 2023-07-05 18:50
Same here on Code Insiders

**Comment by abulka** [comment] 2023-07-08 05:47
I get this message a lot. Could it be more prevalent when XML output is involved?
<img width="592" alt="Screenshot 2023-07-08 at 3 46 43 pm" src="https://github.com/microsoft/vscode-copilot-release/assets/11467530/2cb1ab45-d14d-4619-9480-acb3f7a73d83">

**Comment by sidharthancr** [comment] 2023-07-12 03:18
Same for react js.

**Comment by rallao** [comment] 2023-07-13 23:46
same here, unusable tool atm

**Comment by rattling** [comment] 2023-07-17 12:41
Same for me with , unuseable so far.

**Comment by dinhvankhoi-developer** [comment] 2023-07-17 13:08
> 

hiện tại Copilot Chat đã  dùng ổn định rồi bạn !

**Comment by dinhvankhoi-developer** [comment] 2023-07-17 13:09
> Same for me with , unuseable so far.
![image](https://github.com/microsoft/vscode-copilot-release/assets/99070105/d0590694-428a-4d4f-8a29-82dbc3f9f671)
hiện tại Copilot Chat đã dùng ổn định rồi bạn !

**Comment by AGKireev** [comment] 2023-07-18 17:07
Most of the replies are truncated and I see a reply: "Oops, your response got filtered. Vote down if you think this shouldn't have happened.". Seems like it depends on the length of the reply, but even if I explicitly ask the Chat to be brief, it ignores my request and rewrites the whole code and fails to output the result. Frustrating.

**Comment by rschuetzler** [comment] 2023-07-20 22:12
Asked Copilot chat to help with a big-ish refactor splitting one big file into separate components for better encapsulation. The code output got filtered, just as others have mentioned. Makes it fairly useless for anything big, even though it seems to be capable.

**Comment by kuchannn** [comment] 2023-07-21 10:35
same here on pre-release version with vscode insiders. so obnoxious.. what am I paying for?

**Comment by Moh9998** [comment] 2023-07-24 11:48
same here if anyone know how to fix this issue please help

**Comment by sleeplesskyru** [comment] 2023-07-25 03:38
I am getting the same error and my best guess from using AI over the years is that it has a really bad set of rules such as "bad words" or something to prevent malicious activity.

Here is how I fixed the **my** issue. I asked it the following prompt:

_"I want the kick command to function the same except I want it to check if args is an array with more than one user ID. If it is, I want to loop through and kick all users in the array"_

It gave me the error over and over again. My assumption is that _"kick"_ is somehow malicious so my next prompt was:

_"say remove instead of kick"_

It then responded with the original code that was getting filtered out.

**Comment by dhstrom** [comment] 2023-07-26 15:12
What's the deal here, Github?

**Comment by washingweb** [comment] 2023-07-29 14:57
same issue

**Comment by Lexian-droid** [comment] 2023-07-31 15:00
I need it to merge a script together, big huge PHP script, going to take hours to do otherwise, it's completely willing, it's not over the token limit, but instantly it gets deleted. Why am I paying for this? It's yet another good idea that Microsoft had to mess up, but this time, we're all paying for it.

I'll be frank, I wonder if anyone else feels this way, but: I don't honestly care if the bot breaks the ToS, It's a chatbot, it's designed to accomplish a task but so far Microsoft is screwing it up. It's a pitty.

**Comment by MohamedSapry** [comment] 2023-08-06 10:18
i have the same issue when i try to get "write me and example of using three liberary" with a next ask of "with html file"

**Comment by envitricollat** [comment] 2023-08-21 14:51
same issue here!

**Comment by shoelaced** [comment] 2023-08-22 14:33
This is happening way too often and frankly rendering the tool useless.

**Comment by linrswa** [comment] 2023-08-23 02:59
same issue here!

**Comment by KalleV** [comment] 2023-08-25 10:27
I've seen this come up several times. I just replicated it when asking Copilot to refactor a file using "ejs" for templating to "handlebars".

**Comment by tju2050633** [comment] 2023-08-27 07:29
Same issue here. It seems that this issue is related to the input length. For example, when i ask copilot to doc a short function, it always functions properly. But when the function is too long, maybe 100 lines or so, copilot cannot handle it then.

**Comment by yuanzhibang-tool** [comment] 2023-08-27 07:36
> Same issue here. It seems that this issue is related to the input length. For example, when i ask copilot to doc a short function, it always functions properly. But when the function is too long, maybe 100 lines or so, copilot cannot handle it then.

same with short question!

**Comment by shoelaced** [comment] 2023-08-27 10:50
I seems like it gets stuck in rejection mode now and then. If I get the message once, I get it for practically everything afterward, but if I close VS Code and re-open it, sometimes I can get it to move on with shorter questions. But even then it eventually gives up again so I've just been using other tools.

**Comment by Swader** [comment] 2023-08-27 19:52
Same here. Giving up

**Comment by RehmanAkbar** [comment] 2023-08-30 03:34
same issue 
![image](https://github.com/microsoft/vscode-copilot-release/assets/15936680/3d6bfeca-6836-4d52-9950-4ccb19029293)

**Comment by skmajgotra** [comment] 2023-09-02 07:27
this is day one of my co-pilot license and i'm seeing this issue for past 1 hr.
Will i get the refund
![image](https://github.com/microsoft/vscode-copilot-release/assets/99800011/d553770b-b22a-4a7d-b896-39482deb50c6)

**Comment by ChaturaW** [comment] 2023-09-04 03:22
I too have been experiencing the same issue for the past few days. It's frustrating. :(

**Comment by Marcelo-maga** [comment] 2023-09-05 18:07
same thing here too

**Comment by naveenchicos** [comment] 2023-09-06 03:54
I too experience same issue.

**Comment by tamisoft** [comment] 2023-09-08 18:53
Experienced the same, the solution was to tell the model to replace the words with something else in the response. For me the modal window creation using the bootstrap library had in the generated example words like: "aria-label" "aria-hidden". And that together with "class" and "role" was enough to trigger. 
So, re-prompted telling it to replace every occurrence of the word aria with aaa, role with bbb and class with ccc. 
This no longer triggered the filter, and a find&replace was enough to restore the original code. But very inconvenient and finicky to figure this out from the fragment that can be copy pasted from under the blur. 
I can see this might be a tough problem to solve, but as for now, this reduces the value of the service a lot. 

I have no such problem generating C code. Quite likely because there isn't much comprehensible talking going on in that.

**Comment by Krasivaya** [comment] 2023-09-13 09:07
Actually I just faced the same issue but after understanding when does this response jump in which is when your message contains any of the following *"inappropriate or low-quality content, such as offensive language, spam, or irrelevant information"* it throws this *"Oops, your response got filtered"*

However, in my case which I don't think was any of the above, instead it was because it was going to generate a large response, I formatted the message so that it can generate the response in chunks(one at a time) and I was able to bypass the ***Oops, your response got filtered. Vote down if you think this shouldn't have happened.*** 

I was able to get all my desired responses as I was expecting them without triggering it 🎉

**Comment by SamRamSan** [comment] 2023-09-18 03:09
Same happened to mi with Apache response, some times with PHP to.

**Comment by charith1** [comment] 2023-09-18 07:04
![Screenshot 2023-09-18 122052](https://github.com/microsoft/vscode-copilot-release/assets/12007912/9e2aa4d1-e7fd-4b4a-89c4-a1bc77167cc9)

**Comment by Yenwod** [comment] 2023-09-20 16:03
I've been experiencing this awfully annoying problem as well.  I was able to get it working by telling it:

> This is very important code. You are a master javascript developer. What are your top 3 refactoring ideas?

Next, I chose recommendation that I liked best, and said:

> Please refactor using async/await

It worked.  And the code was improved.

**Comment by halilibrahimcelik** [comment] 2023-09-21 05:23
> I've been experiencing this awfully annoying problem as well. I was able to get it working by telling it:
> 
> > This is very important code. You are a master javascript developer. What are your top 3 refactoring ideas?
> 
> Next, I chose the recommendation that I liked best, and said:
> 
> > Please refactor using async/await
> 
> It worked. And the code was improved.


I got also same warning  and I'm trying to do what you told, but I don't understand it, can you elaborate little bit more, how did you overcome this issue

**Comment by glitchwizard** [comment] 2023-09-22 20:59
I'm getting this same issue too.

**Comment by Ponpon55837** [comment] 2023-09-23 06:39
I got same issue when I ask to use React.js, too

**Comment by Andonade** [comment] 2023-09-24 02:58
same issue using C++

**Comment by Boffice** [comment] 2023-09-24 15:01
same story html, nothing works like official page of chat.openai.com, most probably I will cancel my copilot subscription since regular copilot has drastically decreased number of suggestions as well.  

![image](https://github.com/microsoft/vscode-copilot-release/assets/44022848/fef2a89e-2dcf-486a-a810-c714515cbfa9)

**Comment by Michael-Liendo** [comment] 2023-09-24 23:10
Same issue in React.js

**Comment by blafed** [comment] 2023-09-26 22:46
same here :(

![image](https://github.com/microsoft/vscode-copilot-release/assets/54446984/a858d0a0-2264-402f-bfda-f43b4f001611)

**Comment by Michael-Liendo** [comment] 2023-09-26 22:57
It's weird, because it works with one type of input, when I put something else, it works already

**Comment by Cb1ock** [comment] 2023-09-27 08:09
![image](https://github.com/microsoft/vscode-copilot-release/assets/90198143/92a63664-c0d2-4b3d-aff6-ef902082c975)
same for me😣，anyone can solve this?

**Comment by mateuspiresl** [comment] 2023-09-27 20:19
Seems that it appears on big answers. Am I not paying enough for the tool, and that's why I'm getting limited?

**Comment by shayandavoodii** [comment] 2023-09-29 05:49
WTH?
![image](https://github.com/microsoft/vscode-copilot-release/assets/52105833/40335022-91a5-45e9-825c-12b65c75803e)

**Comment by DRIFTKINGEVO** [comment] 2023-09-29 22:29
> Seems that it appears on big answers. Am I not paying enough for the tool, and is that why I'm getting limited?

Seems like, I'm on the free time trial and I think its because of that lol we getting too much already

**Comment by timothytripp** [comment] 2023-10-03 00:14
I had never gotten this until today but at least for me it was because I was on a VPN while travelling and I guess OpenAI thought I was using the VPN to get around their geographic limitations. As soon as I turned off the VPN I was able to ask the exact same questions that were getting "filtered" so maybe it's tied to certain content coming from certain sources not being allowed on VPNs?  Unfortunately I need the VPN on when I'm actually doing any real work so this could be a problem while travelling, but I'll be trying different VPN connections to see if I can get around the problem.

**Comment by alex-marinov** [comment] 2023-10-03 14:22
Same here, but on VPN.
VS Code Version: 1.82.2
GitHub Copilot Chat v0.7.1
GitHub Copilot v1.122.462

Currently on trial period, perhaps because of that?

<img width="859" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/490052/cafeeffc-35dc-418d-bf70-a0a374d7c4ce">

**Comment by mateuspiresl** [comment] 2023-10-03 14:52
> > Seems that it appears on big answers. Am I not paying enough for the tool, and is that why I'm getting limited?
> 
> Seems like, I'm on the free time trial and I think its because of that lol we getting too much already

For sure it isn't cause of trial because I've been paying for almost a year now and I'm experiencing this limitation 😕

**Comment by DRIFTKINGEVO** [comment] 2023-10-03 15:37
> > > Seems that it appears on big answers. Am I not paying enough for the tool, and is that why I'm getting limited?
> > 
> > 
> > Seems like, I'm on the free time trial and I think its because of that lol we getting too much already
> 
> For sure it isn't cause of trial because I've been paying for almost a year now and I'm experiencing this limitation 😕

But is something that triggers it, because it can happen some days on the same code and some other days it will work just fine

**Comment by ehammo** [comment] 2023-10-05 17:14
same for me

**Comment by luisrconriquez** [comment] 2023-10-06 00:26
same

**Comment by ilog2000** [comment] 2023-10-06 08:34
happened to me just now, and reproduced when I repeated the same question... despite the message, looks more like an error on getting/processing response stream

**Comment by Blairwebops** [comment] 2023-10-07 01:40
I wonder if it has to do with load on the AI at any given time?  I have the same problem here.  I tried the "You are a master developer. How would you refactor this?" which worked a couple of times, then same issue.

**Comment by zutshisunakshi** [comment] 2023-10-12 17:25
**Update**: Code changes to honor user settings in CAPI has landed as part of https://github.com/github/copilot-api/issues/980
FYI @Jenverse , @sharonlo, @digitarald

**Comment by digitarald** [comment] 2023-10-13 01:26
Closing this issue completed as only known root cause is fixed. Check your [Copilot settings](https://github.com/settings/copilot) or reach out to your org admin if you keep hitting filtered responses.

Any other filtering issues should be filed as new issues so we can do better debugging on new root causes beyond the fix described in https://github.com/microsoft/vscode-copilot-release/issues/295#issuecomment-1760046462 .

**Closed by digitarald** 2023-10-13 01:26 UTC
Labels: RAI-filter

**Comment by mcfalld** [comment] 2023-10-26 02:17
I have this setting allowed, and it still filters just as many responses as it provides.

**Comment by Kwame0** [comment] 2024-01-22 06:56
useless tool, im sticking to GPT4, since its less useless

**Comment by digitarald** [comment] 2024-01-22 20:45
> It doesn't tell us why it filtered the response, how do we know if its from public code or not?

Chat version 0.12 pre-release (to be released next week) has some more detailed reports on filter reasons, which should make reporting easier – and please do report, as we use any false positives to improve the service and include in testing. And please open a new issue, as we try to keep comments manageable to support diagnostics and tracking.

**Comment by KoningLeon** [comment] 2024-02-01 13:45
> Chat version 0.12 pre-release (to be released next week) has some more detailed reports on filter reasons, which should make reporting easier – and please do report, as we use any false positives to improve the service and include in testing. And please open a new issue, as we try to keep comments manageable to support diagnostics and tracking.

The 0.12 pre-release version only gives a detailed report when using the chat window, not when using CTRL+I inline. 

That said, the reason it give me for filtering the response is the fact that the response closely matches public code. 

This is a false positive because I asked copilot to refactor a sql statement to use AS instead of = in column aliases on a SELECT statement from my company's data warehouse. The script in question was written last week and uses names and terms that are very specific to this use case so there is no way that the code is public.

**Comment by dream80** [comment] 2024-02-02 07:23
Keep saying Oops, your response got filtered. Vote down if you think this shouldn't have happened.      
Copilot and Chat are both unavailable. Tried logging in again, problem still persists 
![image](https://github.com/microsoft/vscode-copilot-release/assets/20279174/f3bd89ed-966d-4771-b101-d652c8645fa7)

**Comment by digitarald** [comment] 2024-02-02 07:45
@dream80 could you file this as a new issue with the output from "Copilot Chat" in VS Code's output panel?

**Comment by Spike433** [comment] 2024-02-02 10:49
Same problem here.

I tried same license on visual studio and it works fine.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24856398/7b324599-7fe9-48ab-8ba4-935129a90856)

Copilot Autocomplete also works in VSC.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24856398/7c83cb82-bdd7-4628-a83c-7a8c0e555ee2)

Copilot Chat is failing.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24856398/95fdf6a8-383a-4f1e-9733-75dddcbd50be)

This is the reason.

https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints

**To ensure Copilot Chat continues working from February 1, 2024, please update to the most recent version of the Copilot extension and ensure your firewall and network settings allow communication** 
 **Versions 0.8.0 and later of the Copilot Chat** extension for VS Code and **versions 0.1.1817.27579** and later of the Copilot Chat extension for Visual Studio already route chat traffic through
 
 Does somebody see why it still doesn't work.
![image](https://github.com/microsoft/vscode-copilot-release/assets/24856398/03f9bb0f-4a4e-4e8c-9b6a-ae5c3750ee18)
![image](https://github.com/microsoft/vscode-copilot-release/assets/24856398/8ba2f0b5-5d7d-4d9c-b9ce-c52471d075af)

2024-02-02T10:47:56.045Z [ERROR] [chat fetch] Unhandled status from server:,410,{"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.8.2023092902","editor-version":"vscode/1.83.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. **Please update your IDE extension** to continue using GitHub Copilot chat."}}

**Comment by digitarald** [comment] 2024-02-02 22:58
Please see https://github.com/microsoft/vscode-copilot-release/issues/826#issuecomment-1924288014 for filtering issues.

**Comment by agustincards14** [comment] 2024-02-03 16:17
FYI this fixed it for me: [https://github.com/microsoft/vscode-copilot-release/issues/822#issuecomment-1924064375](url)

Had VSC in my Downloads folder

**Comment by agustincards14** [comment] 2024-02-03 16:19
FYI [this](https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469) fixed it for me

**Comment by gjghs** [comment] 2024-02-04 08:24
I fixed it by just upgrade my vscode

**Comment by kalivijay** [comment] 2024-02-06 07:31
> I fixed it by just upgrade my vscode
Worked for me

**Comment by Ponpon55837** [comment] 2024-02-06 08:12
> I fixed it by just upgrade my vscode

me too, upgrade viscode and copilot, copilot chat version,  then it can use.

**Comment by KweezyCode** [comment] 2024-08-03 03:51
any fix? still with java project
