### ISSUE TITLE
Sorry, no response was returned.

### ISSUE THREAD

**Issue by conorhearn1** [microsoft/vscode-copilot-release#3352] opened 2024-12-18 13:25 UTC
Type: <b>Bug</b>

Sorry, no response was returned.

Extension version: 0.23.1
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 24.2.0
Modes:

**Comment by isidorn** [comment] 2024-12-18 13:32
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If you can reproduce, can you please provide reproducible steps?
Thank you

**Comment by MichaelRyom** [comment] 2024-12-19 07:33
Have this issue right now after working on a project a few hours.

Extension version: 1.253.0
Version: 1.95.3 (system setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

upgraded copoilot ( not status is restart extensions - so maybe not ?) and was asked to restart vscode. after that copoilt chats again

**Comment by isidorn** [comment] 2024-12-19 10:03
What are the reproducible steps? Can you also provide a screenshot?

**Comment by MichaelRyom** [comment] 2024-12-19 10:26
Not after the reboot... but before everytime ask a q it would say, sorry
cant. It started out of the blue while working on the code maybe a 1 or 2
since last q. No obvious reason

tors. 19. dec. 2024 11.04 skrev Isidor Nikolic ***@***.***>:

**Comment by isidorn** [comment] 2024-12-19 11:39
Ok. For now I will go ahead and close this. If you find reproducible steps I am happy to reopen this issue

**Closed as completed by isidorn** 2024-12-19 11:39 UTC
Labels: info-needed

**Comment by MichaelRyom** [comment] 2024-12-19 19:16
I just hit it again now, after being AFK for four hours. But has it just
happens when asking a Q it is hard to come by a way to reproduce. changed
model from Claude to o1-mini and it started working again...

Den tors. 19. dec. 2024 kl. 12.40 skrev Isidor Nikolic <
***@***.***>:

**Comment by MichaelRyom** [comment] 2024-12-20 09:54
again I had the issue with Claude. Selected "Done" this time and startede a
new copilot session. There has to be a timeout or session breaking

Den tors. 19. dec. 2024 kl. 20.50 skrev Michael Ryom ***@***.***

**Comment by isidorn** [comment] 2024-12-20 09:55
Thank you for your feedback. There is a service side issue that we are aware of with Claude. I know the team is investigating, and I expect a fix to land soon.
