### ISSUE TITLE
Chat  interrupted in middle

### ISSUE THREAD

**Issue by Mrt009** [microsoft/vscode-copilot-release#415] opened 2023-09-23 09:18 UTC
While  I was using the copilot chat feature and i was telling it to update my code with the latest version of dependencies in my json files it was doing it while, but in middle the code got fade out , and i see the msg at the bottom telling Oops, your response got filtered. Vote down if you think this shouldn't have happened.

**Comment by GroovinChip** [comment] 2023-09-24 18:45
This is happening a lot for me, too.

**Comment by digitarald** [comment] 2023-09-25 03:46
Duplicate of #89

**Closed by digitarald** 2023-09-25 03:46 UTC
Labels: triage-needed
