### ISSUE TITLE
New update results in response disappearing.

### ISSUE THREAD

**Issue by ReedGraff** [microsoft/vscode-copilot-release#1723] opened 2024-10-05 20:32 UTC
- GitHub Copilot: v1.235.0
- GitHub Copilot Chat v0.22.2024100401 (pre-release)
- VS Code Version: 1.94.0
- OS Version: Windows 11
- Logs: See images below

Steps to Reproduce:
1. Request anything in the chat box
```bash
Please help me solve this bug. The info is attached.
  File "C:\Users\range\CodingProjects\RGBZ\Aeri4l\AllofPermitFly\CentralizedAppraiser\src\cleaner.py", line 36, in <module>
    if data["properties"] is not None and "unStructured" in data["properties"].keys() and "kwargs" in data["properties"]["unStructured"].keys():
                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'
```

2. Wait for it to generate (it will start streaming text)
![image](https://github.com/user-attachments/assets/5854be4e-7c1b-4b8f-b184-a5e0b97aa5f1)

3. Wait for it to finish, and the text will disappear. 
![image](https://github.com/user-attachments/assets/d28f23df-a137-40a4-b0ba-859131074020)

**Comment by nanotecheg** [comment] 2024-10-05 20:43
same issue with me

**Comment by maitreverge** [comment] 2024-10-06 09:12
Same issue here, Copilot chat doesn't seems to answer any of my question...

**Comment by DylanDevelops** [comment] 2024-10-06 20:46
I'm having this same issue!

**Comment by sitelicon** [comment] 2024-10-07 08:56
Same problem

**Comment by psiete** [comment] 2024-10-07 08:57
Same problem

**Comment by MaxOstrowski** [comment] 2024-10-07 15:07
Same problem, probably duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1742

> Version: 1.94.0
> Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
> Date: 2024-10-02T13:08:12.626Z
> Electron: 30.5.1
> ElectronBuildId: 10262041
> Chromium: 124.0.6367.243
> Node.js: 20.16.0
> V8: 12.4.254.20-electron.0
> OS: Linux x64 6.8.0-45-generic snap

**Comment by roblourens** [comment] 2024-10-07 16:21
Is everyone seeing this using the pre-release version of the Copilot Chat extension? Does it help to switch to the Release version? (Copilot Chat extension, not Copilot)

**Comment by celynw** [comment] 2024-10-07 16:32
Yes and yes for me.
(I also first made the mistake of downgrading the Copilot extension, not the Copilot Chat extension)

**Comment by roblourens** [comment] 2024-10-07 16:44
To fix this, you can switch to the Release version of the Copilot Chat extension, and also click + to start a new chat session.

In general, there's no advantage to using the pre-release version of Copilot Chat with VS Code Stable. This time, a change went out that should have only gone to Insiders. Sorry for the churn!

**Comment by roblourens** [comment] 2024-10-07 17:00
To recover your chat session which is now broken due to having responses with bad data, if the newer chat request rows load, you can click the X in the top right corner of the request. Delete all the recent requests that have bad data, and you may have to reload the window, but then you should be able to load the older requests in that chat session normally.

**Comment by ReedGraff** [comment] 2024-10-07 19:27
One related issue I've seen, which is likely related, is not being able to create new chats.
![newChats](https://github.com/user-attachments/assets/ba54e302-54d1-4379-9e57-4c8c41e4019b)

* The dropdown is also greyed-out

Solution rn is just to revert to an older release.

**Comment by roblourens** [comment] 2024-10-07 19:53
@ReedGraff that would be a different issue, maybe the extension/extension host process is not starting. You can open a new issue for that.

We've published an update to the pre-release to fix this, so I'm closing this issue, but I'd still recommend not using the pre-release extension if you're using VS Code Stable.

**Closed by roblourens** 2024-10-07 19:53 UTC
Labels: info-needed

**Comment by rzhao271** [comment] 2024-10-23 21:41
@roblourens what are some verification steps for this issue?

**Comment by mjbvz** [comment] 2024-10-23 21:51
@rzhao271 Try asking any question that includes a file/symbol link in the response and make sure the full answer is rendered
