### ISSUE TITLE
"Generate Commit Message with Copilot" not displayed when in workspace context

### ISSUE THREAD

**Issue by anthonypillot** [microsoft/vscode-copilot-release#666] opened 2023-12-11 17:14 UTC
It seems that the "sparkles" ✨ button to "Generate Commit Message with Copilot" is not displayed when I'm in a workspace context.

Using folder, everything is working as expected:
<img width="400" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/51130139/e57e1392-0775-4c75-a9f3-6aee1e2530b7">

Using workspace:
<img width="543" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/51130139/950a3acb-d313-4fd9-a140-a575aefe2f32">

- VS Code Version: 1.85.0 (ARM64)
- OS Version: macOS 14.1.2 (23B92)

Note that I've tried to fully clean install Visual Studio Code and delete his cache and all extensions.

**Comment by Pixelao** [comment] 2023-12-12 09:00
Same error here, not showing when in a workspace.

![image](https://github.com/microsoft/vscode-copilot-release/assets/8830376/2bdd3ba1-3334-498a-a6de-3f32dd7fc98e)


![image](https://github.com/microsoft/vscode-copilot-release/assets/8830376/01bb6d89-23d4-41fd-ba9a-adb725a4db86)

**Comment by corang** [comment] 2023-12-12 23:32
Same here, it was working and broke today after gitlens added the same feature and enabled it by default

**Comment by crehds** [comment] 2023-12-13 01:33
Same here. Git Lens asked to me to enter a ChatGPT API KEY in order to generate the commit message.

**Comment by lszomoru** [comment] 2023-12-13 08:28
This issue has already been fixed in VS Code Insiders, and will be included in the first VS Code recovery release. Closing this as duplicate of https://github.com/microsoft/vscode/issues/200375

**Closed by lszomoru** 2023-12-13 08:28 UTC
Labels: triage-needed
