### ISSUE TITLE
Authentication not working - sign in with Github

### ISSUE THREAD

**Issue by toddsayersshell** [microsoft/vscode-copilot-release#1449] opened 2024-08-05 22:51 UTC
Type: <b>Bug</b>

Restarted vscode, machine, etc. Github CoPilot chat has been working. Today, it asks me to "Sign in with Github to use Copilot..."  The authentication succeeds. When redirected to app, the extension's behavior is unchanged.

This stinks -- and cannot raise support request to GH. #lame #microsoft

Extension version: 0.18.1
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.67GB (45.53GB free)|
|Process Argv|--crash-reporter-id 352253ef-2c18-447b-a5a3-f26d2abf89f6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: EARL_DB_API  @ docker-01|
|OS|Linux x64 5.15.0-117-generic|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (4 x 0)|
|Memory (System)|15.61GB (13.11GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccplti:31103428
pythonrstrctxt:31103193

```

</details>

**Comment by toddsayersshell** [comment] 2024-08-05 22:53
N.b. that I have also disabled/enabled the extension. There are "instructions," online, that suggest signing-out of my github.com account. I'm not able to find this in vscode.  I'm not offered this through the bottom-right "tray" icon -- nor through vscode's Command Palate.

**Comment by toddsayersshell** [comment] 2024-08-05 22:56
I finally found the sign-out of Github.com option. I've done this and subsequently re-attempted the sign-in. My browser (used by the process) is able to view my repository. The process claims to be successful. However, the plugin still demands that I authenticate.

**Comment by toddsayersshell** [comment] 2024-08-05 23:00
We have a corporate subscription. In general, GH Copilot Chat is fairly helpful. Er, it's often helpful. However, I frequently experience issues. Currently, while I'm able to successfully authenticate using my browser (which is opened by vscode for the authentication piece) is able to view my repos.  GH CpChat remains unable to authenticate.

The utility is kinda cool when it works. However, I find that it often fails. I believe that they're being a bit overzealous with the authentication/authorization "bit." I use this on precisely ONE machine and ONE non-shared corporate account. This stinks.

**Comment by toddsayersshell** [comment] 2024-08-05 23:02
I'm trying to leave a negative review of the extension... but even THAT fails. Classic.

**Comment by chaysen-heycircle** [comment] 2024-08-06 07:23
Having the same issue. Copilot chat won't authenticate.
Here is the output from the co-pilot chat extension

```bash
2024-08-06 08:17:50.473 [info] [ContextKeysContribution] You are not signed in to GitHub. Please sign in to use Copilot.
2024-08-06 08:17:50.473 [info] [auth] GitHub login failed
2024-08-06 08:17:50.474 [info] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-08-06 08:17:50.474 [info] [LanguageModelAccess] Error: GitHubLoginFailed
```

**Comment by chaysen-heycircle** [comment] 2024-08-06 08:11
@toddsayersshell So my solution was to downgrade the copilot chat extension 0.17.1
<img width="844" alt="Screenshot 2024-08-06 at 09 10 39" src="https://github.com/user-attachments/assets/043a86c5-2d30-406e-94ab-7761e08c5ac2">
<img width="1025" alt="Screenshot 2024-08-06 at 09 10 44" src="https://github.com/user-attachments/assets/6bbae14b-4e4f-4f4a-9722-3f63acd07ddf">

**Comment by chaysen-heycircle** [comment] 2024-08-06 09:43
duplicate https://github.com/microsoft/vscode-copilot-release/issues/1444

**Comment by angushhz** [comment] 2024-08-06 15:37
Same issue which i have meet in 2 day. Need some support from copilot

**Comment by angushhz** [comment] 2024-08-06 15:42
> @toddsayersshell So my solution was to downgrade the copilot chat extension 0.17.1 <img alt="Screenshot 2024-08-06 at 09 10 39" width="844" src="https://private-user-images.githubusercontent.com/155954825/355367545-043a86c5-2d30-406e-94ab-7761e08c5ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTkxOTcsIm5iZiI6MTcyMjk1ODg5NywicGF0aCI6Ii8xNTU5NTQ4MjUvMzU1MzY3NTQ1LTA0M2E4NmM1LTJkMzAtNDA2ZS05NGFiLTc3NjFlMDhjNWFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNTQxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWQ0MDAyNWU0YmVlMzY4NzA2NGRmNzEyMDU5YTgzZTgxZTVkNTBmNTQ3YTM2NjFmMWI3M2VkZjJiYTkzMDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZDBaxAg60-LZ9PvdHDAsftcVa6XdCSGCQmty0b2VDU4"> <img alt="Screenshot 2024-08-06 at 09 10 44" width="1025" src="https://private-user-images.githubusercontent.com/155954825/355367536-6bbae14b-4e4f-4f4a-9722-3f63acd07ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTkxOTcsIm5iZiI6MTcyMjk1ODg5NywicGF0aCI6Ii8xNTU5NTQ4MjUvMzU1MzY3NTM2LTZiYmFlMTRiLTRlNGYtNGY0YS05NzIyLTNmNjNhY2QwN2RkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNTQxMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDIzNzZhNjlkMTI5MjczNzdlOGZkNmUxZGFlMWU3YmM4NWFmYmUyYWNhODE5MTU4NWIwNTE4OGUyYzQwNmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fGRNlbgfdEurec8mWtF2aZsxwnk0fOvyxwx01eCjHPI">
> 
> This will allow you to use the chat feature but inline chat seems to be broken `[extension] Inline chat request is missing context information, undefined, undefined, undefined`

It is helpful for me when downgrade to this version and it work again. Thank you. Hope copilot chat fix above issue soon

**Comment by toddsayersshell** [comment] 2024-08-06 15:44
Downgrading to v0.17.1 reenabled Copilot Chat. The two subsequent releases do NOT work. I'll need to disable auto-updates... which is quite unfortunate.

**Comment by TylerLeonhardt** [comment] 2024-08-06 16:12
Can you tell me if you have the [github.copilot.preferredAccount](vscode://settings/github.copilot.preferredAccount) (or if you're on [VS Code insiders the link is this](vscode-insiders://settings/github.copilot.preferredAccount)) set? What it's set to? And what happens if you delete it?

**Comment by toddsayersshell** [comment] 2024-08-06 16:20
@TylerLeonhardt I am using a corporate subscription. We are quite conservative and not using anything that has not been fully-vetted (no beta or pre-release code allowed). I work for a very large multi-national organization.

**Comment by toddsayersshell** [comment] 2024-08-06 16:48
I reset this setting (preferredAccount) to the default value (empty) and subsequently upgraded to v1.220.0. The extension now works with the latest release. Thank you.

**Comment by toddsayersshell** [comment] 2024-08-06 16:49
FWIW, I do not recall explicitly setting the values of preferredAccount.

**Comment by TylerLeonhardt** [comment] 2024-08-06 17:05
@toddsayersshell what was the setting set to?

**Comment by toddsayersshell** [comment] 2024-08-06 17:11
Hmmm... I THINK that it was set to my corporate email address (not toddsayersshell -- my github.com ID). I've been in meetings and coding all morning, multitasking. It works, now.

**Comment by swalcoff** [comment] 2024-08-06 18:45
Same issue here. Chat stopped working for me yesterday but code completion was unaffected. 

Switching to v0.17.1 fixed the chat issue. I also removed the preferred account and now I can used the most recent version again. Same as @toddsayersshell, I do not recall adding my email to preferred account setting.

**Comment by TylerLeonhardt** [comment] 2024-08-10 00:13
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2278793021

**Closed by TylerLeonhardt** 2024-08-10 00:13 UTC

**Comment by ohofherr** [comment] 2024-08-11 14:01
> I reset this setting (preferredAccount) to the default value (empty) and subsequently upgraded to v1.220.0. The extension now works with the latest release. Thank you.

after I did this, copilot didn't demand to login anymore

**Comment by samyokesh** [comment] 2024-09-01 18:26
> Can you tell me if you have the [github.copilot.preferredAccount](https://vscode.dev/redirect?url=vscode://settings/github.copilot.preferredAccount) (or if you're on [VS Code insiders the link is this](https://vscode.dev/redirect?url=vscode-insiders://settings/github.copilot.preferredAccount)) set in user settings? What it's set to? And what happens if you delete it?

This worked for me Thanks 👍
