### ISSUE TITLE
Start Inline Chat no longer available in the command palette

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-copilot-release#609] opened 2023-11-27 19:11 UTC
1. Open an editor
2. Open the command palette
3. Search for `Start Inline Chat`
4. :bug: no match

Maybe related to https://github.com/microsoft/vscode/commit/edc4698236d31fa84088b58e6f216d11acd8794b since the editor indeed does not have focus when the command palette is open

**Comment by aiday-mar** [comment] 2023-11-28 08:37
Hi @joyceerhl thank you for the catch, it is likely as you mentioned related to that change. I will look into the code.

**Comment by aeschli** [comment] 2023-11-30 13:37
Duplicate of https://github.com/microsoft/vscode/issues/199371

**Closed by aeschli** 2023-11-30 13:37 UTC
Labels: bug
