### ISSUE TITLE
Chat window not displaying in Ubuntu

### ISSUE THREAD

**Issue by mattjreid** [microsoft/vscode-copilot-release#77] opened 2023-05-22 12:40 UTC
- VS Code Version: 1.78.2
- OS Version: Ubuntu 22.04.2 LTS
- Logs: N/A

Steps to Reproduce:

1. Download and install GitHub Copilot Nightly
2. Sign in to GitHub
3. Uninstall GitHub Copilot
4. Restart VS Code
5. There is no new icon in the activity bar

**Comment by nlindroos** [comment] 2023-05-22 13:46
The official guides don't seem to contain the required steps. I got it working on macos by installing [VS Code Insiders](https://code.visualstudio.com/insiders/) and installing the [GitHub Copilot Chat](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat) extension.

**Comment by c42alyst** [comment] 2023-05-22 15:41
Also I realised that I had accidentally unchecked the 'Github Copilot' on the side bar, just check that it is enabled (after of course installing the nightly build, chat and aurhorising github)
<img width="219" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/6627044/8e40c772-0ba2-4b8d-a916-08b10fce2bc6">

**Comment by digitarald** [comment] 2023-09-29 03:16
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/316#issuecomment-1739722874

**Closed by digitarald** 2023-09-29 03:16 UTC
