### ISSUE TITLE
Chat shows Sign In even though I'm signed in to GitHub

### ISSUE THREAD

**Issue by viktordd** [microsoft/vscode-copilot-release#1357] opened 2024-07-01 18:06 UTC
Type: <b>Bug</b>

Recently started seeing Copilot Chat window showing `Sign In` button even though I'm signed in
![image](https://github.com/microsoft/vscode-copilot-release/assets/4382305/2e0d29e4-086b-4e6f-aa0f-dde299e07676)
![image](https://github.com/microsoft/vscode-copilot-release/assets/4382305/441e3349-0080-4f56-9de6-cce569b962e0)

The Output shows `GitHub login failed`
![image](https://github.com/microsoft/vscode-copilot-release/assets/4382305/5ae37041-1940-4974-acd5-0f7b156141fb)

Extension version: 0.16.1
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (18.86GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/viktordikov/OneDrive%20-%20Microsoft/Documents/Docs --crash-reporter-id 20eadb33-7708-475b-ab95-b7740165afae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31082723

```

</details>

**Comment by barnobarno666** [comment] 2024-07-01 20:39
It may have something to do with  multiple github accounts ,mine worked after i set a preferred account under extension settings

**Comment by yadinbk** [comment] 2024-07-02 08:38
I have the same issue but nothing is helping.
![image](https://github.com/microsoft/vscode-copilot-release/assets/58659025/718dc519-1081-45c8-9517-7da1e2dce0f0)
![image](https://github.com/microsoft/vscode-copilot-release/assets/58659025/1e54660c-ef82-4192-a468-0b63ef21328e)
I signed in but yet is keep failing with this outpot
I keep having this issue.
`2024-07-02 11:27:24.272 [error] [auth] Retrying auth
2024-07-02 11:27:57.618 [error] [auth] The operation was aborted.`

**Comment by yadinbk** [comment] 2024-07-02 08:41
![image](https://github.com/microsoft/vscode-copilot-release/assets/58659025/025c126c-6152-4eb8-bc08-c59001260f22)

2024-07-02 11:35:32.376 [error] [default] Error sending telemetry AbortError: The operation was aborted.
    at fetch (/home/yadinbk/.vscode-server/extensions/github.copilot-1.208.963/node_modules/@adobe/helix-fetch/src/fetch/index.js:96:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/yadinbk/.vscode-server/extensions/github.copilot-1.208.963/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Dq.fetch (/home/yadinbk/.vscode-server/extensions/github.copilot-1.208.963/lib/src/network/helix.ts:88:22) {
  type: 'aborted',
  _name: 'AbortError'
}
2024-07-02 11:35:46.017 [error] [auth] The operation was aborted.
2024-07-02 11:35:47.714 [error] [auth] Retrying auth
2024-07-02 11:36:43.297 [error] [auth] The operation was aborted.
2024-07-02 11:38:11.617 [error] [auth] Retrying auth
2024-07-02 11:38:45.398 [error] [auth] The operation was aborted.
2024-07-02 11:38:53.789 [error] [auth] Retrying auth
2024-07-02 11:40:29.488 [error] [auth] The operation was aborted.

**Comment by viktordd** [comment] 2024-07-02 20:51
> It may have something to do with multiple github accounts ,mine worked after i set a preferred account under extension settings

Ah yep that worked once I set the `github.copilot.preferredAccount` to the one that has the Copilot subscription it worked.

**Comment by gijsbeijer** [comment] 2024-08-21 11:24
mine even shows Im loggedin:
```
2024-08-21 13:18:38.603 [info] [certificates] Removed 3 expired certificates
2024-08-21 13:18:40.053 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-08-21 13:18:40.053 [info] [code-referencing] Public code references are enabled.
2024-08-21 13:18:40.170 [info] [auth] Sucessfully authenticated
2024-08-21 13:19:59.903 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-08-21 13:19:59.903 [info] [code-referencing] Public code references are enabled.
2024-08-21 13:19:59.910 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-08-21 13:19:59.910 [info] [code-referencing] Public code references are enabled.
```

But still shows me a sign in button

**Comment by TylerLeonhardt** [comment] 2024-08-21 15:30
This is a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2299464817

It's a bug and I have a fix for this Insiders & Pre-release of Copilot Chat.

**Closed by TylerLeonhardt** 2024-08-21 15:30 UTC
