### ISSUE TITLE
MacOS M1 VScode Github copilot chat icon no show

### ISSUE THREAD

**Issue by ck0099** [microsoft/vscode-copilot-release#381] opened 2023-08-27 07:09 UTC
Issue moved from vscode:
https://github.com/microsoft/vscode/issues/190474

Does this issue occur when all extensions are disabled?: Yes/No

    VS Code Version:
    OS Version:

Steps to Reproduce:

1. After installed "Github copilot chat" and reloaded vscode, no extension on side bar

<img width="1335" alt="260640231-8d9d9b89-bcc8-4998-9ecb-0960facd9852" src="https://github.com/microsoft/vscode-copilot-release/assets/132270603/2b7dfd22-8df9-48a0-8394-413000dac33f">

Versions:
macoOS: 12.6.8

vscode:

Version: 1.81.1
Commit: https://github.com/microsoft/vscode/commit/6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z (5 days ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

Copilot Chat: Both of below version do not work:
v0.7.2023081101 (Pre-Release)
v0.6.0

**Comment by pm-root-passwds** [comment] 2023-08-29 01:06
I'm having the same issue.

```
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by meiqiunh** [comment] 2023-08-30 03:39
I'm having the same issue.

**Comment by madsstoumann** [comment] 2023-09-22 05:28
Me as well

**Comment by digitarald** [comment] 2023-09-25 03:45
We are not aware of any issues on M1 chips apart from this issue. Can you please share the logs from `Show Output` > `GitHub Copilot Chat`.

**Comment by digitarald** [comment] 2023-09-27 00:48
@Ludek-Navratil thanks for checking. We are looking into making this more obvious, also on the org settings side.

**Comment by digitarald** [comment] 2023-09-29 04:47
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/436

**Closed by digitarald** 2023-09-29 04:47 UTC
Labels: info-needed
