### ISSUE TITLE
It takes a few minutes to respond after updating to version 0.10.0 and later. 

### ISSUE THREAD

**Issue by lc82111** [microsoft/vscode-copilot-release#611] opened 2023-11-28 00:31 UTC
I tried the GitHub Copilot Chat version 0.8.0. It also takes minutes to respond for the first question, but it responds quickly after that.

- VS Code Version: Version: 1.84.2 (Universal)
- OS Version: OS: Darwin arm64 23.0.0
- Logs: 

Steps to Reproduce:

1.
2.

**Comment by jmeviler** [comment] 2023-11-28 11:41
I also encountered the same problem. Here is my log. The problem can be reproduced stably, with an interval of 5 minutes.

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0

GitHub Copilot :v1.138.570
GitHub Copilot Chat: v0.10.2


Logs:
```
2023-11-28T11:29:08.074Z [INFO] [auth] Logged in as jm
2023-11-28T11:29:08.966Z [INFO] [chat] copilot token chat_enabled: true
2023-11-28T11:29:08.969Z [INFO] [auth] Got Copilot token for jm
2023-11-28T11:29:09.023Z [INFO] [auth] Logged in as jm
2023-11-28T11:29:09.031Z [INFO] [chat] copilot token chat_enabled: true
2023-11-28T11:29:09.032Z [INFO] [auth] Got Copilot token for jm
2023-11-28T11:34:07.338Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-11-28T11:34:07.338Z [INFO] [chat fetch] modelMaxTokenWindow 4096
```

**Comment by lramos15** [comment] 2023-11-28 13:31
Interesting so you just see thinking for awhile?

**Comment by lc82111** [comment] 2023-11-29 03:37
> Interesting so you just see thinking for awhile?

Yes, I see "thinking" for minutes.

**Comment by lramos15** [comment] 2023-11-29 14:11
@lc82111 Can you include your Copilot Chat output channel as well? Via `CMD / CTRL + SHIFT + U -> GitHub Copilot Chat`

**Comment by lramos15** [comment] 2023-12-20 14:29
Closing as a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/637

**Closed by lramos15** 2023-12-20 14:29 UTC
