### ISSUE TITLE
Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. Learn more.

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#1209] opened 2024-05-13 19:49 UTC
This has been happening routinely on a wide range of requests.  If I repeat the question enough times it will eventually give an answer.  Just with up-arrow enter. This problem is rendering the tool useless. 

- VS Code Version:  VS Code Version: 1.90.0-insider (Universal)
-    Commit: 3028408922e78cc9ca15ee761372a7c0603fa375
- OS Version: OS Sonoma 14.4.1

- Logs:
![Screenshot 2024-05-13 at 3 35 54 PM](https://github.com/microsoft/vscode-copilot-release/assets/40220684/9a41f6e5-4991-4e1c-b3e7-f003a8476321)
![Screenshot 2024-05-13 at 3 39 25 PM](https://github.com/microsoft/vscode-copilot-release/assets/40220684/396c670c-79c3-4135-bded-f406f55c0a8c)

Steps to Reproduce:

1.Ask a question 
2.

**Comment by salientknight** [comment] 2024-05-13 19:51
To resolve this problem, I have updated and started a new chat

**Comment by salientknight** [comment] 2024-05-13 20:17
Since reporting this problem, I am not getting the same error on nearly every request. It's very frustrating

**Comment by fisforfaheem** [comment] 2024-05-14 23:25
i get this everyday

**Comment by zbeaver4** [comment] 2024-05-22 22:34
This just started cropping up for me. it's making chat unusable.

**Comment by fisforfaheem** [comment] 2024-05-23 22:08
where is the COpilot teams??? instead of making new features kindly UPDATE us here on issues, also no changelog and daily updates.

**Comment by ricbwood** [comment] 2024-05-25 15:51
Same here, it's the answer to every question I post.  I used the 'send to new chat' option to start a new session. That seems to have cleared it for now.

**Comment by digitarald** [comment] 2024-05-30 16:46
@salientknight and others who keep getting these often; which kind of stacks/languages are you working on when this happens? We are working to update the RAI filters and knowing the specific areas better would massively help.

For others, please post _GitHub Copilot Chat_ logs when this happened, so we can get more details on what happened from diagnostics.

**Comment by salientknight** [comment] 2024-06-07 13:31
This tool is becoming unusable. I get Sorry, the response was filtered by the Responsible AI Service. Or some other lame error all the time and have to ask my questions over and over. It also cannot keep context at all. I ask a workspace question and in the follow ups it can't keep track of the workspace. If I ask a question on highlighted code the minute it's not highlighted it loses context... and this problem has been here for quite a while with no traction

**Comment by fisforfaheem** [comment] 2024-06-07 13:59
cuz they are still using chatgpt 3.5 which is old

**Comment by digitarald** [comment] 2024-06-07 18:07
@salientknight please confirm which dev stacks you are working on when you hit the content filter.

**Comment by Silloky** [comment] 2024-06-11 06:33
Same problem here

**Comment by PierreLambert3** [comment] 2024-06-15 16:57
Same, shameful coming from a payed service. I'm starting to experiment with alternatives to github copilot because of this BS

**Comment by fisforfaheem** [comment] 2024-06-16 09:05
They are not improving it and its been months also wrong and old suggestions

**Comment by csidirop** [comment] 2024-06-17 12:37
Same here with a really easy CSS question. After responding about two paragraphs it stoped with this message.

VSC version: 1.90.1

**Comment by virtuallyunknown** [comment] 2024-06-23 19:33
I'm starting to get this error almost every day, and the "Learn more" button leads to [this particular page](https://docs.github.com/en/copilot/managing-copilot/managing-copilot-as-an-individual-subscriber/managing-copilot-policies-as-an-individual-subscriber#enabling-or-disabling-duplication-detection) but if you pay attention to the URL, you will see a location hash (`#enabling-or-disabling-duplication-detection`) which does not exist on said page.

So really, I have no idea why Copilot chat will just randomly refuse to respond to certain messages.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24871108/e151827d-394b-48f3-bed1-09f814316e75)

**Comment by virtuallyunknown** [comment] 2024-06-24 14:34
Nice finds @Silloky

> According to [this](https://docs.github.com/en/copilot/using-github-copilot/finding-public-code-that-matches-github-copilot-suggestions) page, step 3, if you head into the Copilot output in the terminal, you should see the link to the repo Copilot was about to copy and paste.

This works and I can reproduce the example, but only for in-editor code completions (or whatever the correct term is), but the issue we have is with Copilot chat. With Copilot chat the log stays completely empty.

> All this documentation applies to the inline Copilot suggestions, but there's no reason it'd be different for Copilot Chat.

Exactly.

> We can also try disabling 'Public code suggestions' on [this](https://github.com/settings/copilot) page, maybe it'll help, I don't know...

The prompt from the screenshot always gets for some reason (meaning I can reproduce on demand) and I tried it with that option disabled, but it makes no difference.

Maybe it takes a while for the changes to apply, but honestly if we're paying $120/year, we shouldn't be going down rabbit holes and more importantly getting ghosted by Microsoft. Between this issue and #1175, the problems keep on piling and I'm yet to hear any official response.

**Comment by virtuallyunknown** [comment] 2024-06-24 14:38
Also, it looks like the issue has been going on [at least since February](https://github.com/orgs/community/discussions/107059).

**Comment by Silloky** [comment] 2024-06-24 15:11
Thanks @virtuallyunknown !
This was like cool low-level OSINT 🙃 ! (sort of)

Yes, I understand the problem is with Chat, not inline code-completions.

As I understand it, this is only the consequences of GitHub's legal problems concerning public-code use for training.
**GitHub should integrate the same flow for Chat as for the inline, that is, to show the public code snippets that it's using.**

> (meaning I can reproduce on demand)

Yes, I can't reproduce it either.
I guess as it's AI and probabilistic, the outcome is never exactly the same, and so it's not always flagged.

> The prompt from my screenshot above always gets for some reason (meaning I can reproduce on demand) and I tried it with that option disabled, but it makes no difference.

Well that was to be expected really.
Turning this off probably flags for inline completions too, if you think about what it means.

As for the 120$/year, well, I can't really complain, as I got Copilot and GitHub Pro for free as a student 😄 .

It would be nice if we had *any* feedback on this though.
Just to know if they're working on it...

**Comment by Silloky** [comment] 2024-06-24 15:13
I was going to add, if anyone feels like contributing to the project and solving this nagging problem, but I just realised it wasn't open-source.

Or is it ?

It should be, and they should just keep the cloud service paid.
That would be logical for a dev community...

**Comment by salientknight** [comment] 2024-06-24 18:23
I want to add that if you use up arrow two or three time to resubmit the
question the problem eventually goes away

**Comment by Silloky** [comment] 2024-08-03 09:25
With the VSCode release 1.92.0, it seems this issue might have been solved, as `public code matches` are mentioned as an improvement/fix.

> Public code matching in chat 
> You can allow GitHub Copilot to return code that could match publicly available code on GitHub.com. When this functionality is enabled for your [organization subscription](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/setting-policies-for-copilot-in-your-organization/managing-policies-for-copilot-in-your-organization#policies-for-suggestion-matching) or [personal subscription](https://docs.github.com/en/copilot/managing-copilot/managing-copilot-as-an-individual-subscriber/managing-copilot-policies-as-an-individual-subscriber#enabling-or-disabling-suggestions-matching-public-code), Copilot code completions already provide you with details about the matches that were detected.  We are working on enabling showing you these matches for public code in Copilot Chat as well.
 We are rolling this out gradually for Copilot Chat users. Once it's enabled for your machine, you might see a message at the end of the response with a View matches link. If you select the link, an editor opens that shows you the details of the matching code references with more details.

We'll see if it is indeed fixed...

**Comment by eminbayrak** [comment] 2024-08-19 11:27
I am using the latest version of VS Code, 1.92.2 atm but still having the same issue.
![image](https://github.com/user-attachments/assets/9da5ab7c-ddb1-4041-b940-12bb99c82f39)

**Comment by digitarald** [comment] 2024-08-19 20:38
Clarification on the release notes: If your org/account has public code setting set to Block, the new annotation feature will not apply. Either make sure you change this in Copilot settings or reach out to your org admin.

The annotation support is also still partially rolled out to some accounts, as the release notes mention, so don't be worried if you don't see annotations yet.

**Comment by BrettMoan** [comment] 2024-08-23 20:00
I'm getting this when just trying to ask copilot to look through a readme file. I was only asking it to fix typos and capitalization.

if i don't select the whole file, and only ask with the currently displayed context, it will fix parts of the file, but whenever i try the whole file (73 lines of markdown, 6910 total character) the reply is blocked.

**Comment by BrettMoan** [comment] 2024-08-23 20:25
interestingly, i found an seemly innocuous sentence that the chat can handle as long as there is not leading `-`
![image](https://github.com/user-attachments/assets/405d3681-d7a3-43c1-b8e3-4ac678d6163f)

**Comment by fisforfaheem** [comment] 2024-08-23 22:27
isnt this issue fixed? why people still commenting?

**Comment by eiddor** [comment] 2024-08-25 03:46
> if i don't select the whole file, and only ask with the currently displayed context, it will fix parts of the file, but whenever i try the whole file (73 lines of markdown, 6910 total character) the reply is blocked.

My experience with this is similar - I am asking it to list a bunch of stuff from a 700 line HTML file (too lazy to grep.)  If I select somewhere around 100 lines at a time, it will work, otherwise I get that message.  The only thing in the chat log is:

```
2024-08-24 22:40:06.753 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1064 ms
2024-08-24 22:40:10.051 [info] [streamMessages] message 0 returned. finish reason: [content_filter]
2024-08-24 22:40:10.052 [info] [streamChoices] request done: requestId: [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] model deployment ID: []
```

**Comment by joaoalber** [comment] 2024-08-31 18:57
I'm having the same issue even with the "Suggestions matching public code (duplication detection filter)" set as "Allowed" (tried to set block as well and didn't work)

![image](https://github.com/user-attachments/assets/bed48748-4132-4b38-b017-d14a18717396)

![image](https://github.com/user-attachments/assets/0733ca21-b377-452f-92b9-d896ddbebfb2)

PS: This does not happen only with me, but with all members accross the org

**Comment by congvmit** [comment] 2024-09-02 10:13
OMG. I am facing this problem everyday. Is it really a "feature"?

**Comment by hendrathings** [comment] 2024-09-02 13:44
it frustation , I pay for this feature? what are you doing with my money?

**Comment by tadams95** [comment] 2024-09-06 00:10
![Screenshot 2024-09-05 at 5 09 31 PM (2)](https://github.com/user-attachments/assets/222ddb1c-74a3-4d3b-85b5-8973418e7ddd)
This tool is unusable.

**Comment by digitarald** [comment] 2024-09-06 08:02
@joaoalber @tadams95 if it happens, can you copy and post the logs from the Copilot Chat Output, please?

**Comment by fisforfaheem** [comment] 2024-09-09 12:08
I have moved to using Cody extension its fast and more reliable and same
price. with 10x better context, I really wish the team fixes the issues

**Comment by farisadlin** [comment] 2024-09-26 08:08
It occurred to me as well. I'm frustrated. Can I refund this??? The last time that I used this feature was in May 2024. It was working perfectly fine. I just subscribed to this two hours ago, and this is what happened.
![SCR-20240926-nevc](https://github.com/user-attachments/assets/e8438a30-cb50-4bed-ac8d-2565ae5f0d7e)

**Comment by thewoosh1** [comment] 2024-10-01 14:17
Am currently getting this almost ll the time - its making CoPilot alm0st totally unusable - I try restarting VSCode and it works maybe once and then hits the same error... Does anyone know a solution?

**Comment by fisforfaheem** [comment] 2024-10-01 16:31
All AI assistants are not working....their focus is on o1 from open AI and
they are not working as they should maybe we need atleast 3 more months

**Comment by mattbedford** [comment] 2024-10-02 15:08
Am getting this literally every time I ask it a question. Am not using public code, am not asking anything weird. For instance `Please convert this snippet from html to a php echo statement` just seems to break it. 
I'll give it a few more days then I'm canceling.

**Comment by morgan-hone** [comment] 2024-10-03 08:08
I'm also getting this with every response now. Even for simple explanations. It's now unusable. Has anyone found a solution yet?

**Comment by jeromeOlivier** [comment] 2024-10-06 19:18
got this as well. very annoying

**Comment by tomnar** [comment] 2024-10-08 09:57
You need to tell us what is happening. I am getting this very often, even for simple tasks. I asked it to format a react button and *boom* blocked. What can possibly need blocking here? It is literally a "press me" button. It feels like all of the errors I get are false positives...

**Comment by theandrelima** [comment] 2024-10-08 11:14
Truly annoying... It's happening pretty much for any request.

**Comment by fisforfaheem** [comment] 2024-10-08 20:38
it happens to me when the context gets a little long and chat words are more, which it shouldn't if we are already paying 20$ for it.

**Comment by fisforfaheem** [comment] 2024-10-08 20:39
> I'm also getting this with every response now. Even for simple explanations. It's now unusable. Has anyone found a solution yet?

pay MSFT and ask people to find solutions!

**Comment by GitHunter0** [comment] 2024-10-10 05:28
This is a big problem. So, folks, upvote the issue, otherwise they will not pay attention to this.

**Comment by pootow** [comment] 2024-10-16 14:24
I'm truly very sorry that I subscribed to Copilot. It is useless now. It sensitive to EVERYTHING.

**Comment by theandrelima** [comment] 2024-10-16 16:06
> I'm truly very sorry that I subscribed to Copilot. It is useless now. It sensitive to EVERYTHING.

It's called 'living after <you know what happened> in a hyper sensitive society' and it sucks.

**Comment by jslmariano** [comment] 2024-10-18 14:34
Tomorrow it's Saturday, I don't have work and don't have any errands to run.
It's the day I'm going to pull out my subscription and learn to configure and setup OLLAMA. I recommend you guys try the same :)
Moreover, it's FREE and OFFLINE

**Comment by LokiMidgard** [comment] 2024-10-19 16:37
I tried to use it with some texts I write, some of them are rpg fantasy stuff. Mostly because it has good integration in vscode and can be payed with paypal. And it works quite well for a code specific tool, in the rare cases where it dose not get triggered. The good thing is since it writes word for word, I can roughly guess what part of the text is offending.

E.g. `angestrengtes und müdes stöhnen ihm entfuhr.` is a problem. I assume because of `stöhnen` wich can be translated to `moan` and can be used in an sexual context. However it is also used in many other contexts like Exhaustion, the context I used. For an AI system that seems to at least somehow understand context, I would assume to have a better solution then a *bad word* filter for words that are totally fine to use in day to day speach. This is almost as bad as the Mii-Verse filter that did not allow me to use `after` in English texts because of its German meaning 🤬

**Comment by fisforfaheem** [comment] 2024-10-23 00:11
Moved to Cody by sourcegragh, mich happier now. with 100x more context.

**Comment by tesar27** [comment] 2024-11-07 13:51
I keep getting the same error and seems that github team has not fixed it. Sadly, have to unsubscribe...

**Comment by digitarald** [comment] 2024-11-15 20:12
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/2625

**Closed by digitarald** 2024-11-15 20:12 UTC
Labels: info-needed, rai-content-filters

**Comment by Kamilake** [comment] 2024-12-05 00:28
🤣
![Image](https://github.com/user-attachments/assets/940fc47b-f132-4d67-9bde-ff6ceaa3d78b)
