### ISSUE TITLE
Co pilot chat stopped working (does not recognize paid subscription) - offers 30 days trial  

### ISSUE THREAD

**Issue by foxingreen** [microsoft/vscode-copilot-release#857] opened 2024-02-07 13:12 UTC
vs code:
Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z (6 days ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.1.0

co-pilot:
GitHub Copilot Chat v0.12.0

I have a paid subscription and all worked fine for months but now it says start your 30 days free trial.
When I click the button it takes me to github where it says I already have
a paid subscription.
How can I get it back to work

Mac os Sonoma 14.1.2

Steps to Reproduce:

1. Click on chat extension on the toolbar
2. Prompts to start a 30 day trial

**Comment by foxingreen** [comment] 2024-02-07 13:13
Also stopped working on my visual code studio insiders - there is says login when I try and access the chat but the button does not do anything.

**Comment by AnthonyNave-M3** [comment] 2024-02-07 21:13
I'm also running into this issue. VS Code says the extension has access to the correct GitHub account in Manage Trusted Extensions.
![image](https://github.com/microsoft/vscode-copilot-release/assets/141074230/2bf7e518-3825-4f04-a653-402395303ae2)

But based on the extension Output, chat seems to be using the authentication I use for Git, which is a different account that does not have a Copilot subscription. I use multiple GitHub accounts, Copilot chat is using the wrong account, and I can't seem to change it. Suggestions still work, however.

**Comment by lramos15** [comment] 2024-02-07 21:13
Can you include your logs from `CMD / CTRL + SHIFT + U ` -> `Copilot Chat`

**Comment by AnthonyNave-M3** [comment] 2024-02-07 21:15
@lramos15 Here's what I have.
```
2024-02-07 14:51:32.846 [info] [FetcherService] Using Helix fetcher
2024-02-07 14:51:32.846 [info] [gitExtensionService] Initializing Git extension service.
2024-02-07 14:51:32.846 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-02-07 14:51:32.846 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-02-07 14:51:32.846 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-02-07 14:51:33.125 [info] [auth] Logged in as AnthonyNave-M3
2024-02-07 14:51:33.471 [info] [auth] Invalid copilot token: missing token: 403 
2024-02-07 14:51:33.474 [info] [extension] GitHub Copilot could not connect to server. Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as AnthonyNave-M3."
```

But my Copilot subscription is on another account, which is what GitHub Copilot (but not chat?) correctly shows up under in the Manage Trusted Extensions screenshot. Thanks!

**Comment by lramos15** [comment] 2024-02-07 21:25
Have you tried signing out of the other account and just using the one with access? Multi account can be finnicky

**Comment by AnthonyNave-M3** [comment] 2024-02-07 21:33
Looks like GitHub Copilot Chat does appear in the list of things that used this account, even though it's not in Manage Trusted Extensions.
![image](https://github.com/microsoft/vscode-copilot-release/assets/141074230/a77b3d56-c356-4892-96b8-2ac2934a155d)

If I sign out, the extension does correct to the account that has the subscription. But now I can't use my other Git extensions like Source Control and Pull Requests and Issues until I sign back in with the correct account. Once I do that via the prompts that appear for reauthentication and then I reload the VS Code window, GitHub Copilot Chat goes back to using this account instead of the one that has the subscription, and fails to find it.

**Comment by adamdWalkMe** [comment] 2024-02-07 22:38
I have the same issue, which started happening ~12 hours ago. I discovered I was signed in with two GitHub accounts, and clearly it was using the one without the copilot extension. I also tried to remove access to the account via manage trusted extensions, but **GitHub Copilot Chat** wasn't an option to deselect, even though when I went to later sign out, it was showin as an extension that had been using the account (same experience as @AnthonyNave-M3).

Anyway, the workaround was to sign out of the other account, which I don't need access to via VS Code anyway. 

There should really be an option to configure Copilot to use a specific account, but also, why has this suddently changed for some users?

**Comment by paul-pauliskolan** [comment] 2024-02-08 11:31
Same problem here
I'm also two accounts. One with paid subscription

I'm depended on using both accounts

![Screenshot 2024-02-08 at 12 21 13](https://github.com/microsoft/vscode-copilot-release/assets/9336467/cfc7b9a0-6001-4a50-9f63-7516bf4234cd)
![Screenshot 2024-02-08 at 12 21 13](https://github.com/microsoft/vscode-copilot-release/assets/30831777/5d5bf8a9-ecd7-4e1c-8bb9-ced8416d2cd0)

**Comment by umerfarok** [comment] 2024-02-09 06:38
Resolved by this : =========>
I resolved the issue by logging out all other accounts from VS Code. Those accounts use HTTPS for GitHub authentication. I am utilizing SSH for thjose removed accounts cloning or pushing my code to GitHub, with only one account logged in via HTTPS. This particular account has the Copilot subscription.

**Comment by yllekz** [comment] 2024-02-10 14:51
I get this error a lot and it's really annoying. The extension needs to be aware that folks may be signed into multiple accounts to do work, and realize that it cannot just de-authorize for no explainable reason when the licensed account remains signed in.

**Comment by muneebsajjad** [comment] 2024-02-11 09:33
Facing the same issue is there any solution to it, I am using MacOS (sonoma 14.1.1)
and this is what I get in the "Output" Logs, although I have the active subscription right now!

![Screenshot 2024-02-11 at 2 31 53 PM](https://github.com/microsoft/vscode-copilot-release/assets/2223557/f09783f0-004e-4754-8e2c-33274984f952)

```
[info] [code-referencing] Public code references are enabled.
```

**Comment by geirearnesen** [comment] 2024-02-11 15:10
Facing same issue here .....

**Comment by lramos15** [comment] 2024-02-12 13:28
This issue is caused by VS Code not properly supporting multiple auth sessions. Not much can be done on the extension side until VS Code fixes this. It was a bug that this worked before

Ref:
https://github.com/microsoft/vscode/issues/203850
https://github.com/microsoft/vscode/issues/152399

**Comment by TylerLeonhardt** [comment] 2024-02-13 00:42
Closing as a duplicate of upstream issues called out by @lramos15

**Closed** 2024-02-13 00:42 UTC
Labels: *duplicate

**Comment by WarpedPixel** [comment] 2024-02-23 18:25
On MacOS the solution is to install [VS Code 1.85](https://code.visualstudio.com/updates/v1_85) and pin the copilot extension 1.161.0. Disable all updates in VSCode Settings. Keep this until this bug and/or https://github.com/microsoft/vscode/issues/127967 are fixed for real. With the pinned versions both GitHub Issues and PRs, as well as CoPilot work just fine with a different account for each.
