### ISSUE TITLE
Code references not readable when using Dark mode high contrast

### ISSUE THREAD

**Issue by tabit01** [microsoft/vscode-copilot-release#1300] opened 2024-06-11 13:10 UTC
Type: <b>Bug</b>

Enable Dark mode with high contrast. Ask code related question using Copilot Chat.

Screenshot:

![image](https://github.com/microsoft/vscode-copilot-release/assets/106818948/6925f5cb-34e8-4b03-9a9b-691ee02ddc20)
 

Extension version: 0.16.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

**Comment by ahmedesmail07** [comment] 2024-06-11 13:22
The same issue here, I've tried multiple times to solve this issue after thinking the issue is from my software etc.. but i found that it's mainly bug the Dark High Contrast, any updated please mention me, thanks

**Comment by chipcastillegbi** [comment] 2024-06-11 22:35
Same issue

**Comment by KaylaMLe** [comment] 2024-06-11 23:48
I just encountered the same issue today. I wonder what happened. Copilot was fine previously.

**Comment by daviddossett** [comment] 2024-06-14 15:51
Could you try updating to the latest version? This was fixed in `1.90.1`.

**Comment by KaylaMLe** [comment] 2024-06-14 20:14
Thank you. Yeah, everything is fine with 1.90.1.

**Comment by milescb** [comment] 2024-08-29 17:20
This is not fixed for me with VS code version 1.92.2. Anyone else still encountering this issue?

**Comment by mjbvz** [comment] 2024-12-13 17:04
Tested with inline code and file/symbol links in our builtin high contrast dark theme. I believe this has been fixed:

<img width="1188" alt="Image" src="https://github.com/user-attachments/assets/603403d2-3501-456c-9539-514bd9a68043" />

It's possible that the colors are still off in some themes from the marketplace. If that's the case, please file an issue against that theme

**Closed by mjbvz** 2024-12-13 17:04 UTC
