### ISSUE TITLE
Disable command bar triggering copilot questions

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode-copilot-release#844] opened 2024-02-05 08:32 UTC
When you type something in the command bar you get a useful fuzzy search of similar ones:

![image](https://github.com/microsoft/vscode-copilot-release/assets/26868611/08f5f425-c844-4530-ae24-9b0a9c7aa6d2)

But right now, after a brief momment when you stop typing the list is replaced with a single command to ask it to copilot:

![image](https://github.com/microsoft/vscode-copilot-release/assets/26868611/504b8219-18a3-44e0-b614-214064577db9)

With all the input methods available to ask questions to copilot, I feel like I dont need another one. Furthermore, IMO this one interferes with the command bar in an intrusive way. The response time can be very fast and hide the command list if you stop typing. ATM you can delete a character to cancel it and restore the list, but continuing typing does not.

> I could not find a way to disable this and I would love to. Overall loving the extension tho :)

**Comment by TylerLeonhardt** [comment] 2024-02-05 17:08
duplicate of https://github.com/microsoft/vscode/issues/195023

**Closed by TylerLeonhardt** 2024-02-05 17:08 UTC
Labels: triage-needed
