### ISSUE TITLE
Revert chat to old location in primary sidebar

### ISSUE THREAD

**Issue by vickitaylor** [microsoft/vscode-copilot-release#2099] opened 2024-10-30 01:35 UTC
Type: <b>Bug</b>

how can i make  copilot back the way it was. the new version is horrible and now it doesnt know how to do anything

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (2.94GB free)|
|Process Argv|. --crash-reporter-id 14a3fd05-70cc-4409-853a-8f651bf73bfe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by kieferrm** [comment] 2024-10-30 01:56
> the new version is horrible and now it doesnt know how to do anything
Can you give us some more details?

You can install a specific version of the Copilot extension(s) like this:
![Image](https://github.com/user-attachments/assets/37131fa4-6306-422c-b9ed-704f726db235)

**Comment by vickitaylor** [comment] 2024-10-30 02:23
I want to go back to the old version. I want to know how i can restore the old location. I want the chat button in the left hand tool bar back. I had the pop up (snip is from your documentation) but it immediately went away. I dont like the new version and want the old one back. How can i restore to the prior version before this crap. I asked co pilot and it did not know the answer to that
[cid:082a53d9-ca2a-46a6-857f-868502db6912]

________________________________

**Comment by HojinCho** [comment] 2024-10-30 16:21
I was prompted once without knowing what I was signing up for when clicking "Got it". I wish there was an option to revert this change.

**Comment by HojinCho** [comment] 2024-10-30 16:28
> > the new version is horrible and now it doesnt know how to do anything
> > Can you give us some more details?
> 
> You can install a specific version of the Copilot extension(s) like this: ![Image](https://github.com/user-attachments/assets/37131fa4-6306-422c-b9ed-704f726db235)

This did not revert the location of the copilot chat button.

**Comment by kingrichard2005** [comment] 2024-10-30 17:01
@HojinCho , @kieferrm , and to save the trouble for anyone else coming across this, uninstalling and reinstalling to an earlier copilot extension version had no effect for me and the chat is still stuck at that new location

**Comment by kingrichard2005** [comment] 2024-10-30 17:10
@HojinCho , @vickitaylor , taking a hint from this separate, but related, [issue](https://github.com/microsoft/vscode-copilot-release/issues/2111).  I was able to customize the location dynamically by dragging around the chat icon like below.  Hope this helps you and/or anyone else.  Other similar issues hinted at the same workaround/fix, but what threw me off was I initially thought the icon they were referring to was the copilot robo icon ![Image](https://github.com/user-attachments/assets/3b91175f-cb91-4737-ad0f-13c03cea9356)

 ![Image](https://github.com/user-attachments/assets/712ecbef-e12a-47b2-9f2a-3bc127503370)

**Comment by marcoaurelioguerrap** [comment] 2024-10-30 19:51
Yeah, the new position is not good. It gets in the way of my setup, I think probably anyone who uses double canvas view

**Comment by roblourens** [comment] 2024-10-30 23:21
You can drag the chat view wherever you want it

**Comment by sbatten** [comment] 2024-10-30 23:46
https://github.com/user-attachments/assets/eadb8493-cec8-4848-81d2-4f980e1bae54

**Comment by bpasero** [comment] 2024-10-31 08:23
Marking as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/2111 that asks for a quick way to move the views to primary sidebar.

**Closed by bpasero** 2024-10-31 08:23 UTC

**Comment by 19317362** [comment] 2024-11-02 01:32
this is a BAD change! 
We don't want too many splited windows!

**Comment by warethis-dev** [comment] 2024-11-05 14:59
This is awful and I do not want this. I will cancel copilot if I can't get the chat in the original left-hand location

**Comment by kusiroll** [comment] 2024-11-21 17:26
what is the benefit of moving the chat pane location, there is no perceived benefit to the end user directly there might be implicit benefits for but this would cause serious clutter managing a left and a right pane. What designer/product PM approved this.... ridiculous!
