### ISSUE TITLE
Please prevent Copilot Chat code blocks from appearing in "Problems" tab of VS Code if not yet included in project.

### ISSUE THREAD

**Issue by mattq-ds** [microsoft/vscode-copilot-release#1037] opened 2024-03-14 20:56 UTC
![image](https://github.com/microsoft/vscode-copilot-release/assets/139506803/c398b1c4-ab07-4b47-9f53-acb6014ca792)
- VS Code Version: 1.87.2
- OS Version: Windows 10
- Logs:

Steps to Reproduce:

1.  Prompt for "python library to find longest running tests"

**Comment by jpshackelford** [comment] 2024-03-15 21:09
Confirmed and reported in https://github.com/orgs/community/discussions/112621

**Comment by jpshackelford** [comment] 2024-03-19 12:59
A comment in https://github.com/microsoft/vscode/issues/206644 suggests that this will be fixed in an upcoming release of VSCode 1.88 due to drop in April. I have verified that this is fixed in [VS Code insiders](https://code.visualstudio.com/insiders/) have been using it successfully for the last few days.

**Comment by virtuallyunknown** [comment] 2024-03-23 03:06
I'm having the same issue.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24871108/98ba4201-5d06-4c42-a48d-8cc7e0ce891c)

**Comment by alexdima** [comment] 2024-03-27 21:36
This is possible with a setting. Could you please try `"inlineChat.mode": "preview"`?

**Comment by virtuallyunknown** [comment] 2024-03-28 12:30
> This is possible with a setting. Could you please try `"inlineChat.mode": "preview"`?

I am not 100% sure if you were suggesting this as a fix or workaround, but for me it has no effect, the bug is still there:

![image](https://github.com/microsoft/vscode-copilot-release/assets/24871108/02afc15a-14d0-4e03-a2b3-95dfc268ad96)

**Comment by mjbvz** [comment] 2024-09-26 19:03
This has been fixed in VS Code core for a while. Just forgot to close it

**Closed by mjbvz** 2024-09-26 19:03 UTC
Labels: duplicate
