### ISSUE TITLE
knowledge isn't up to dated 

### ISSUE THREAD

**Issue by jacobjiangwei** [microsoft/vscode-copilot-release#1266] opened 2024-05-30 08:40 UTC
- VS Code Version: 1.89.1
- OS Version: macOS Sonoma 14.5
- Logs:

Steps to Reproduce:

1. 现在我要把NavigationView改为NavigationSplitview
2. Copilot responds: 在 SwiftUI 中，没有直接名为 NavigationSplitView 的组件。但是，你可以通过组合 NavigationView 和 List 来创建一个类似的效果。以下是一个可能的实现：

That is obviously not true. the knowledge was there 1 years ago https://developer.apple.com/documentation/swiftui/navigationsplitview

Isn't Copilot using GPT4 with latest online search capabilities?

**Comment by digitarald** [comment] 2024-05-30 16:49
Duplicate of #560

**Closed by digitarald** 2024-05-30 16:49 UTC

**Comment by jacobjiangwei** [comment] 2024-06-01 15:13
what's the model used here? are we saying gpt4 does not have 1 years knowledge ?
