### ISSUE TITLE
cant use fix bug feature in copilot chat

### ISSUE THREAD

**Issue by noramirulnordin** [microsoft/vscode-copilot-release#472] opened 2023-10-11 04:44 UTC
- VS Code Version:  Latest
- OS Version: window 11
- Logs:  unrecognize language blade

Steps to Reproduce:

1. Open .blade page using vs code
2. right click and choose fix bug
3. it will show unrecognize language blade

**Comment by noramirulnordin** [comment] 2023-10-17 06:40
![image](https://github.com/microsoft/vscode-copilot-release/assets/93645686/d33f7bba-2683-4abb-8aca-ed4d28ffde30)

all php and blade page cant use github copilot chat.

**Comment by aiday-mar** [comment] 2023-10-19 07:41
Hi yes thank you for posting this issue, this is a duplicate of the issue: https://github.com/microsoft/vscode-copilot-release/issues/469. This issue will be closed, you may comment on the other one.

**Closed by aiday-mar** 2023-10-19 07:41 UTC
Labels: bug, inline-chat
