### ISSUE TITLE
生成长代码有问题Problems with generating long code

### ISSUE THREAD

**Issue by Davidasx** [microsoft/vscode-copilot-release#2017] opened 2024-10-24 12:07 UTC
Type: <b>Bug</b>

生成400行长代码有很大的困难。如果代码较长（例如[flask-gpt](https://github.com/Davidasx/flask-gpt)），AI将会在写完大约200-300行代码后反复从头开始写并将开头的代码附加到输出中。随后，显示结果被负责任的AI过滤。
The AI has great difficulty generating long code. If the code is long(400 lines of HTML, for example, see [flask-gpt](https://github.com/Davidasx/flask-gpt)), the AI will hallucinate and generate the code from the beginning after writing 200-300 lines. It will append the code from the beginning into the output and writing repeated code. After that, it will report that the result has been filtered by responsible AI.

Extension version: 0.22.2024100702
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.11.5-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.47GB (10.97GB free)|
|Process Argv|/home/davidx/Desktop/flask-gpt/index.html --crash-reporter-id f57196ed-b524-4dc4-b52b-b1f389703c45|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by Davidasx** [comment] 2024-10-24 12:25
Hi, admins. I've translated into English myself. I know English, just too lazy to translate it at first...
Sorry for the inconvenience.

**Comment by digitarald** [comment] 2024-12-10 00:34
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/2628

**Closed by digitarald** 2024-12-10 00:34 UTC
Labels: info-needed, translation-required-chinese-simplified
