### ISSUE TITLE
Unable to use github copilot

### ISSUE THREAD

**Issue by anay-208** [microsoft/vscode-copilot-release#3410] opened 2024-12-19 17:41 UTC
Type: <b>Bug</b>

I'm unable to use github copilot.
when I click use copilot on the right sidebar, It just loads for a moment and nothing happens.

Extension version: 0.23.2
VS Code version: Code 1.96.1 (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-1025-azure

<details><summary>Prompt Details</summary>
<pre>
Info: Can't use the Electron fetcher in this environment.
Info: Using the Node fetch fetcher.
Info: Initializing Git extension service.
Debug: [context keys] Updating context keys.
</pre>
</details><details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.35GB (10.40GB free)|
|Process Argv|--crash-reporter-id dd091d7f-fecd-471f-bb1d-6fb4f6825888|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|Codespaces: sturdy space barnacle|
|OS|Linux x64 6.5.0-1025-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (2 x 0)|
|Memory (System)|7.74GB (4.95GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by rebornix** [comment] 2024-12-19 17:46
This is a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/3375, we are working on a fix and will release a recovery build soon.

**Closed** 2024-12-19 17:46 UTC
Labels: duplicate, triage-needed
