### ISSUE TITLE
Inline chat widget breaks if I cancel it immediately after pressing enter

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#783] opened 2024-01-24 19:17 UTC
- Open inline chat widget
- Press enter to submit a query, press escape immediately
- Open inline chat again, now it's broken
- I can't get rid of it, it shows in every editor until I reload the window

```
2024-01-24 16:15:22.046 [error] Session already stored for vs.editor.ICodeEditor:1@file:///Users/roblou/code/vscode/src/vs/workbench/api/browser/mainThreadChatAgents2.ts: Error: Session already stored for vs.editor.ICodeEditor:1@file:///Users/roblou/code/vscode/src/vs/workbench/api/browser/mainThreadChatAgents2.ts
    at u.createSession (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1911:72922)
    at async K.CREATE_SESSION (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33692)
    at async K.R (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33226)
    at async K.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33046)
2024-01-24 16:15:22.047 [error] Unexpected type: Error: Unexpected type
    at b (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:93:10132)
    at K.PAUSE (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:42819)
    at K.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2387:33125)
```

![Recording 2024-01-24 at 16 16 43](https://github.com/microsoft/vscode-copilot-release/assets/323878/8552c665-e007-410b-b1b3-44f23e0304a7)

**Comment by jrieken** [comment] 2024-01-25 08:21
/duplicate of [https://github.com/microsoft/vscode-copilot/issues/3719](vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

**Closed** 2024-01-25 08:21 UTC
