### ISSUE TITLE
Remote extension host crashing

### ISSUE THREAD

**Issue by mvobbi** [microsoft/vscode-copilot-release#871] opened 2024-02-09 12:00 UTC
This is the same bug as 574 again (it has never stopped happening)

Version: 1.86.1 (Universal)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:09:01.236Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.1.0

Steps to reproduce:
1. Enable the Github co-pilot extension

Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.

The same thing happens in both the release and the pre-release version.

**Comment by mvobbi** [comment] 2024-02-09 12:12
Might be worth saying I'm using php8.2-apache co-pilot v1.159.0 now as the base container image as opposed to php7.4-apache in bug 574

**Comment by mvobbi** [comment] 2024-02-09 12:13
Also, running against a remote real ubuntu OS works perfectly with either version of php.

**Comment by rebornix** [comment] 2024-03-27 15:04
/duplicate of https://github.com/microsoft/vscode/issues/194458

**Closed by rebornix** 2024-03-27 15:04 UTC
Labels: triage-needed

**Comment by mvobbi** [comment] 2024-04-18 15:20
In case it helps someone else, it looks like when using GitHub CoPilot on an Intel Mac with a Docker  Container started from a .devcontainer configuration in Visual Studio Code, you may need to change the docker virtualisation as indicated in the thread referenced above.

https://github.com/microsoft/vscode/issues/194458#issuecomment-1912849373

This seems to be a big enough problem that it really should be called out by GitHub CoPilot, especially when paying for it.
