### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't havehappened.

### ISSUE THREAD

**Issue by Lind-pro** [microsoft/vscode-copilot-release#931] opened 2024-02-22 06:08 UTC
- VS Code Version:1.86.2 (Universal)
- OS Version: Mac 14.2.1 (23C71)
- Logs:
Oops, your response got filtered. Vote down if you think this shouldn't havehappened.

Steps to Reproduce:
No matter what you ask, the answer is 
Oops, your response got filtered. Vote down if you think this shouldn't havehappened.

**Comment by dewes** [comment] 2024-02-23 13:38
Same problem, even asking for it to create a Hello World in python gets filtered. 

The copilot code sugestions seems to work fine, while chat does not.

**Comment by joyceerhl** [comment] 2024-02-23 16:44
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/934

**Closed by joyceerhl** 2024-02-23 16:44 UTC
