### ISSUE TITLE
When refactoring code give the ability to create new files and folders from the suggested code

### ISSUE THREAD

**Issue by kevmoens** [microsoft/vscode-copilot-release#41] opened 2023-05-19 02:45 UTC
Given I am refactoring code.
When the suggestion is to create new classes
And the user approves the suggestions.
Then the new classes are created in an appropriate folder, namespace and file.

**Comment by digitarald** [comment] 2023-06-07 19:21
Duplicate of #45

**Closed by digitarald** 2023-06-07 19:21 UTC
