### ISSUE TITLE
Undstand the context of the project that is opened

### ISSUE THREAD

**Issue by MCKevmeister** [microsoft/vscode-copilot-release#62] opened 2023-05-20 23:13 UTC
If I ask a simple request in copilot chat for example adjusting the css of the project and there is only one css file in the project, and I click the button to insert the code block, then context of the project should be enough to insert it directly. If its not enough context, then could copilot ask me where I want to insert a block of code? Can it please not just inset wherever the cursor is in the current file.

If this isn't possible, then I'll just keep coding by comment which seems like the copilot chat feature should be somewhat replacing to provide more context for the overall project?

**Comment by sairajchouhan** [comment] 2023-05-21 14:46
This is absolutely useless

<img width="437" alt="Screenshot 2023-05-21 at 8 15 05 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/57995897/676f290e-1f94-47d4-be06-d0fa00408029">

**Comment by digitarald** [comment] 2023-06-09 22:52
Duplicate of #14

**Closed by digitarald** 2023-06-09 22:52 UTC
Labels: chat-context
