### ISSUE TITLE
Inline chat freezes and doesn't offer accept/reject

### ISSUE THREAD

**Issue by dusski** [microsoft/vscode-copilot-release#2139] opened 2024-10-31 10:20 UTC
Type: <b>Bug</b>

The inline chat is frozen, persists through tab closes and re-opens, no accept button is present, only the cancel button is visible. Nothing happens when cancel is clicked. Typing something again into the chat box yelds no results either. It happens when I trigger inline chat and I ask copilot to generate some code for me.

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|14.56GB (3.81GB free)|
|Process Argv|. --crash-reporter-id 513d9452-581d-4971-8a0a-1f8baaaa5d84|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by jrieken** [comment] 2024-11-01 16:19
@dusski Please try this with 1.95.x which has this likely fixed

**Comment by jrieken** [comment] 2024-12-09 14:27
/duplicate of https://github.com/microsoft/vscode-copilot-release/issues/1625

**Closed** 2024-12-09 15:30 UTC
Labels: inline-chat
