### ISSUE TITLE
getting an error: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by shanun11** [microsoft/vscode-copilot-release#863] opened 2024-02-07 18:26 UTC
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Upon asking a complicated question i get Cannot read properties of undefined (reading 'split')
2.

**Comment by shanun11** [comment] 2024-02-07 18:27
vscode version 1.86.0 
OS: Windows_NT x64 10.0.19945
![image](https://github.com/microsoft/vscode-copilot-release/assets/30770037/fe321f89-7a8f-4af2-8e01-8a16f9f4f704)

**Comment by davidjray** [comment] 2024-02-07 18:35
@shanun11 I was seeing this same error and was able to clear it by loading the extensions panel, and clicking "Reload Required" on any of the extensions. I think this happened because I update VSC.

**Comment by digitarald** [comment] 2024-02-07 21:41
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/838

**Closed by digitarald** 2024-02-07 21:41 UTC
Labels: triage-needed
