### ISSUE TITLE
Copilot Edit very slow to apply changes

### ISSUE THREAD

**Issue by Federicocervelli** [microsoft/vscode-copilot-release#3397] opened 2024-12-19 13:28 UTC
Type: <b>Performance Issue</b>

using sonnet 3.5, the auto apply feature is way too slow. 
i think this might be an issue for what model is used to actually check what to apply and where.
it seems to freeze for a long time at some point and then randomly keeps going, just to then freeze again.
it took 5 minutes to apply 27 lines of code in a 400 lines total file.

Extension version: 0.23.2
VS Code version: Code 1.96.1 (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-14700 (28 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.68GB (14.62GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/fcervelli/blueprint --remote=wsl+Ubuntu --crash-reporter-id 5b755f08-8962-42bc-9884-142214737bde|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-14700 (28 x 0)|
|Memory (System)|15.46GB (9.22GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   129	 26896	code main
    0	   139	  1808	extensionHost [1]
    0	     8	  6204	     C:\windows\system32\wsl.exe -d Ubuntu -e /bin/sh -c "cd '/home/fcervelli/blueprint' && /bin/sh"
    0	     8	 19056	       C:\windows\system32\conhost.exe 0x4
    0	    10	 29080	       C:\windows\system32\wsl.exe -d Ubuntu -e /bin/sh -c "cd '/home/fcervelli/blueprint' && /bin/sh"
    0	    10	  6064	          --distro-id {5a17a8ff-330f-435d-84fb-60022b07f371} --vm-id {4beb0c9d-ab9a-438e-b0ab-103488a1da02} --handle 976 --event 1000 --parent 1004
    0	     9	  2424	           C:\windows\system32\conhost.exe 0x4
    0	    94	  9264	     electron-nodejs (serverMain.js )
    0	    86	 13796	     electron-nodejs (wslDaemon.js )
    0	    50	  3472	   utility-network-service
    0	    52	  7912	   utility-process
    0	    31	 18124	   crashpad-handler
    0	   111	 23092	ptyHost
    0	   132	 30904	shared-process
    0	   617	 30916	window [1] (● specter-chart.component.ts - blueprint [WSL: Ubuntu] - Visual Studio Code)
    0	    88	 31396	fileWatcher [1]
    0	   112	 31696	   gpu-process

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	 32814	remote agent
    0	     0	 65205	   extension-host
    0	     0	 65281	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/prisma.prisma-6.1.0/node_modules/@prisma/language-server/dist/bin.js --node-ipc --clientProcessId=65205
    0	     0	 65568	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.9/dist/server/server.js --node-ipc --clientProcessId=65205
    0	     0	 65627	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/angular.ng-template-19.0.3/server --logToConsole --ngProbeLocations /home/fcervelli/.vscode-server/extensions/angular.ng-template-19.0.3,/home/fcervelli/blueprint --includeAutomaticOptionalChainCompletions --includeCompletionsWithSnippetText --angularCoreVersion 19.0.5 --tsdk node_modules/typescript/lib --tsProbeLocations /home/fcervelli/.vscode-server/extensions/angular.ng-template-19.0.3,/home/fcervelli/blueprint --node-ipc --clientProcessId=65205
    0	     0	 65684	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js --node-ipc --clientProcessId=65205
    0	     0	 65707	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/nrwl.angular-console-18.34.0/nxls/main.js --node-ipc --clientProcessId=65205
    0	     0	 65813	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.12.16/dist/tailwindServer.js --node-ipc --clientProcessId=65205
    0	     0	 66022	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=65205
    0	     0	 70044	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=65205
    0	     0	 74224	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/ms-azuretools.vscode-docker-1.29.3/dist/dockerfile-language-server-nodejs/lib/server.js --node-ipc --node-ipc --clientProcessId=65205
    0	     0	 74230	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/extensions/ms-azuretools.vscode-docker-1.29.3/dist/compose-language-service/lib/server.js --node-ipc --node-ipc --clientProcessId=65205
    0	     0	 81455	     /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/node /home/fcervelli/.vscode-server/bin/42b266171e51a016313f47d0c48aca9295b9cbb2/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=65205
    0	     0	 65216	   fileWatcher
    0	     0	 75299	   ptyHost
    0	     0	111099	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	111100	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu|    Folder (blueprint): 542 files|      File types: js(157) map(145) ts(67) json(38) lock(6) md(5) hash(5)
|                  sql(5) gitkeep(3) html(3)
|      Conf files: package.json(13) project.json(3) tsconfig.json(3)
|                  settings.json(1) webpack.config.js(1) dockerfile(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by aeschli** [comment] 2024-12-19 15:39
similar: https://github.com/microsoft/vscode-copilot-release/issues/3085

**Comment by aeschli** [comment] 2024-12-20 13:36
Marking as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/3403.
Not exactly the same report, but the same underlying issue.

**Closed by aeschli** 2024-12-20 13:36 UTC
Labels: triage-needed
