### ISSUE TITLE
Getting Language Model unavailable

### ISSUE THREAD

**Issue by Asai1211** [microsoft/vscode-copilot-release#2365] opened 2024-11-07 05:43 UTC
Type: Bug

Language model unavailable (In Github Business) in Visual Studio Code and Visual Studio

- Copilot Chat Extension Version: 0.22.1
- VS Code Version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
- OS Version: Windows 10 Enterprise - 22H2 (OS build: 19045.5011)
- Logs:

Steps to Reproduce:

1. whenever trying to do anything in chat window or inline chat

**Comment by Asai1211** [comment] 2024-11-07 05:46
![Image](https://github.com/user-attachments/assets/47b97a65-2bf4-442d-9abd-b83c389f2d7c)

**Comment by digitarald** [comment] 2024-11-07 22:53
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/2116

**Closed by digitarald** 2024-11-07 22:53 UTC

**Comment by roblourens** [comment] 2024-11-07 22:54
Hi, could you please see the first comment of https://github.com/microsoft/vscode-copilot-release/issues/2116#issue-2624506695 to grab some logs to help us diagnose the issue? Thanks!
