### ISSUE TITLE
Public code response block even when allowed

### ISSUE THREAD

**Issue by bulawow** [microsoft/vscode-copilot-release#654] opened 2023-12-08 06:49 UTC
- VS Code Version: 1.85.0 - insiders
- OS Version: Windows_NT x64 10.0.19045
- Logs:

2023-12-08 07:44:07.574 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-08 07:44:07.574 [info] [chat fetch] modelMaxTokenWindow 4096
2023-12-08 07:44:07.574 [info] [chat fetch] chat model gpt-4
2023-12-08 07:44:12.074 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 4499 ms
2023-12-08 07:44:14.027 [info] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-08 07:44:14.028 [info] [streamChoices] request done: requestId: [78497fd2-9bfe-4d42-9574-ade6ec106318] responseId: [4c85e147-0243-47ea-a342-1ed288fbe65f] model deployment ID: [x3b0892d9e5fc]
2023-12-08 07:44:15.546 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-08 07:44:15.546 [info] [chat fetch] modelMaxTokenWindow 4096
2023-12-08 07:44:15.546 [info] [chat fetch] chat model gpt-4
2023-12-08 07:44:18.900 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 3354 ms
2023-12-08 07:44:25.889 [info] [streamMessages] message 0 returned. finish reason: [content_filter]
2023-12-08 07:44:25.889 [info] [streamChoices] request done: requestId: [faa9f8c7-25e3-44ce-981a-bd2528f33faa] responseId: [9e1111e5-eb43-4f77-b7a5-50e6afc04297] model deployment ID: [x3b0892d9e5fc]

![1](https://github.com/microsoft/vscode-copilot-release/assets/11963752/4f52ad95-249c-4d58-a6c9-10189f83876a)
![2](https://github.com/microsoft/vscode-copilot-release/assets/11963752/4b88a908-4dc1-4695-b7ce-463f35ad77c0)

Steps to Reproduce:

Just ask about code in a repo of a community, also were just copying and pasting the same prompt over and over results were sometimes it gives full answer and sometime the error pops up

**Comment by bj97301** [comment] 2023-12-11 19:33
Same for me.  I have it enabled in my org but keeps cock blocking me when I type it in vscode.

**Comment by Fot3k** [comment] 2023-12-12 23:50
Having same issue.

**Comment by lramos15** [comment] 2023-12-13 14:27
There is a violence filter and a few others that cannot be turned off. Based on what I see filtered above my guess is maybe `getCorpse` and `lastHitCreature` is triggering those. We're working on trying to surface better to the user which filter is at play here

**Comment by bulawow** [comment] 2023-12-13 15:42
> Same for me. I have it enabled in my org but keeps cock blocking me when I type it in vscode.

Based on Iramos replay i would recommend giving screens on when the filter is wrongly applied so they could possibly tune it in a faster peace

**Comment by bulawow** [comment] 2023-12-13 15:45
> There is a violence filter and a few others that cannot be turned off. Based on what I see filtered above my guess is maybe `getCorpse` and `lastHitCreature` is triggering those. We're working on trying to surface better to the user which filter is at play here

Also since its a different filter i would recommend changing the block message to inform the user that it was the violence filter so it could be easier identified and possibly reported to improve such filter by reported example and remove the confusion.

**Comment by lramos15** [comment] 2023-12-13 18:14
Consolidating as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/583

**Closed by lramos15** 2023-12-13 18:14 UTC
