### ISSUE TITLE
code-insiders slow and consuming vast amounts off CPU and memory

### ISSUE THREAD

**Issue by SanderElias** [microsoft/vscode-copilot-release#779] opened 2024-01-24 09:40 UTC
Type: <b>Bug</b>

start code-insiders. and watch how it consumes an enourmous ammount of CPU cycles and memory.

![image](https://github.com/microsoft/vscode-copilot-release/assets/1249083/54f9341a-8780-4c98-a607-b3849e2d2561)

Extension version: 0.12.2024012301
VS Code version: Code - Insiders 1.86.0-insider (800e60abdfb1675a59520bac6a9473bc380d49ea, 2024-01-23T06:11:42.114Z)
OS version: Linux x64 6.1.0-17-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 2689)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|94.00GB (80.20GB free)|
|Process Argv|./ --crash-reporter-id 9798ed61-5ab4-4fff-86e0-34c42b858535|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b5d27386:30943795
fegfb526:30945144
bg6jg535:30946824

```

</details>

**Comment by Kitt3120** [comment] 2024-01-24 12:05
Can you install Copilot pre-release and Copilot Chat release version? For me, the problem is Copilot Chat pre-release version, which consumes a lot of CPU with ripgrep processes during startup.

**Comment by roblourens** [comment] 2024-01-24 17:26
Can you grab the full command line arguments of those `rg` processes?

Maybe this is yours @TylerLeonhardt

**Comment by Kitt3120** [comment] 2024-01-24 17:37
Here you go

`/opt/visual-studio-code-insiders/resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --hidden --no-require-git --ignore-case -g **/* -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/Thumbs.db -g !**/node_modules -g !**/bower_components -g !**/*.code-search --no-ignore-parent --follow --crlf --engine auto --regexp (?:[\S\s]|\r?\n)+ --no-config --no-ignore-global --json --multiline -- .`

**Comment by TylerLeonhardt** [comment] 2024-01-25 02:48
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/784#issuecomment-1909254671

**Closed** 2024-01-25 02:48 UTC
Labels: triage-needed

**Comment by lopugit** [comment] 2024-08-05 02:48
I'm still getting this issue I think 👀

![Screenshot 2024-08-05 at 12 45 44 PM - Activity Monitor - Activity Monitor](https://github.com/user-attachments/assets/9506d5b7-c79f-42f3-8e8e-be71c4975fe5)

**Comment by lopugit** [comment] 2024-08-05 02:51
After closing vscode no issues.. 

![Screenshot 2024-08-05 at 12 51 09 PM - Activity Monitor - Activity Monitor](https://github.com/user-attachments/assets/7def2a23-6804-44e9-8e55-8370866914f5)
