### ISSUE TITLE
Longer Outputs In Copilot Chat

### ISSUE THREAD

**Issue by BeamoINT** [microsoft/vscode-copilot-release#641] opened 2023-12-06 20:29 UTC
Copilot chat is great when it comes to smaller outputs. Currently though, copilot will say that it's response is too long and then not output the rest of the code like it is supposed to. Copilot should have the ability to output longer code snippets than the ones that it currently does. This would make it a lot more helpful and more of a useful tool in development. This is one of the things that ChatGPT is currently better at than Copilot is.

**Comment by lramos15** [comment] 2023-12-19 16:22
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/534

**Closed by lramos15** 2023-12-19 16:22 UTC
Labels: duplicate
