### ISSUE TITLE
Arrow up/down keys shouldn't delete chat message

### ISSUE THREAD

**Issue by CanRau** [microsoft/vscode-copilot-release#661] opened 2023-12-09 17:03 UTC
- VS Code Version: 1.85.0
- OS Version: macOS Big Sur 11.7.10
- Logs:

Steps to Reproduce:

1. Type something in chat
2. arrow up or down multiple times until message disappears
3. message lost

This happens due to [prompt history](https://github.com/microsoft/vscode-copilot-release/issues/82#issuecomment-1568962111) which I appreciate, though it shouldn't just forget what I'm writing right now, this was very unexpected as I didn't even knew about prompt history until now. I use arrow up/down a lot to move around what I'm writing but never had it delete everything 😬

**Comment by zjeffer** [comment] 2023-12-09 18:00
I just created the same issue and only saw your issue afterwards, it wasn't there yet when I started typing :)

More info and a video of how it looks can be found in #662

**Comment by CanRau** [comment] 2023-12-09 20:43
Haha, was about to say let's close mine as you've got a video but I think now that everything's cross linked shouldn't matter too much.

Hopefully there's a solution soon, happened again right after posting this 😅

**Comment by roblourens** [comment] 2023-12-12 19:41
Sorry, I made some improvements to history navigation but this situation should not happen.

Might be able to get this out in an update in January.

**Comment by rhcarvalho** [comment] 2023-12-14 09:33
I lost a few prompts in the past days by accidentally typing arrow up one-too-many times when editing the prompt, and it is always super frustrating to lose the prompt. Specially that it tends to happen to longer prompts in which I invested effort crafting it.

I've had it happen both in the sidebar chat & the inline chat.

**Comment by NidusUmbra** [comment] 2023-12-15 14:15
I second this, it can actually become quite time consuming if you are writing a verbose prompt that you navigate through as you edit it, and accidentally press the down-key one time too. Once, twice or even on monday. It's become a habit to write the prompt in a separate window or application, but only when losing that post once or twice of course.

**Comment by WayneLauze** [comment] 2023-12-15 15:53
this needs to be fixed asap.

**Comment by jaredstokes** [comment] 2023-12-15 16:41
Please at least make it a setting so we can turn this off!

**Comment by coder0xff** [comment] 2023-12-27 17:31
If there's a label to prioritize issues, please prioritize this one. It's very inflammatory to users experiencing it.

**Comment by synthmusic** [comment] 2023-12-28 06:55
+1

**Comment by vinnyreid** [comment] 2024-01-03 04:46
Ugh, this happens to me multiple times in a short time span. I'm sure I will eventually learn, but I might lose my mind before that happens.

**Comment by aiwilliamson** [comment] 2024-01-08 13:53
Came here to report this same thing, can be (has been) very frustrating. Good to see the issue is closed, I don't have any update yet but definitely look forward to it 😄

**Comment by karlkablisk** [comment] 2024-01-10 02:13
having the same issue, if they kept what you last wrote and perssing UP would restore what you lost this would be resolved. or.. just not have down delete everything, does anyone need this?

**Comment by Jacek-Kapral** [comment] 2024-01-13 21:36
Same issue, i'm writing a massive prompt and want to edit it, i press arrow up, it goes up one time too many, the whole prompt dissapears and i can't come back to it. :< sadpanda.jpg

**Comment by roblourens** [comment] 2024-01-14 17:27
Sorry it took a bit, but watch for the fix in the next Insiders build.

I went back to the previous model where you actually can't navigate history at all while typing your prompt. If you start typing and need to navigate history, you can delete the contents of the chat input, then press up.

**Comment by kbigdelysh** [comment] 2024-01-27 15:04
This is still happening to me. Spec:

GitHub Copilot Chat v0.11.1

VS Code:
Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by binaryfire** [comment] 2024-01-27 15:06
Same. It's quite frustrating.

**Comment by TheGU** [comment] 2024-01-30 09:59
Any text that has already been typed should be saved to the history before displaying previous entries. This would allow users to utilize the down arrow key to retrieve their current input if needed

**Comment by binaryfire** [comment] 2024-02-04 16:59
Hi @roblourens, could you please re-open the issue? It's still not fixed.

**Comment by ianbruton** [comment] 2024-02-05 12:58
copying my comment from issue 701 to here for visibility because this issues, while close, seems to have more people finding it

comment:

I am on the prerelease of copilot and copilot chat and this is still broken.

To be honest, I do not want this feature at all.

If I ever need text from an old prompt for anything, it's never to send the exact same prompt again. I usually only need a small part from it, but rarely, if ever, the entire thing. So for me at least it is actually easier to just highlight the part I need with my mouse, since it's right there in the chatlog anyway.

Also, when I do copy some text to the chat textbox, I am 99 times out of 100 going to need to move about that text to make edits or add context/modifications, and if in doing so I accidentally press up or down one to many times while at at the top or bottom of the textbox, boom, all my work is gone.

This has happened to me on a pretty much daily basis*, and when it does, I stop using the chat in my editor and go back to chatGPT, simply because the text box functions how I expect it to, and I don't need to remember to craft my prompt in a blank editor tab in my IDE before copying it to the copilot chat box.

I have been burned too many times, and each time it's a loss of a substantial amount of time, but also the thought process to creating the prompt, and now I need to mentally step through the issue again. For lack of a better description, it is INFURIATING.

Please just let me turn it off in the settings of my IDE, because even when it is working as intended, I don't want it.

*I think the reason that it frequently happens to me is because I, like I am sure many others also do, will just hold the up and down arrow to get to the top and bottom of a textbox. Because that is how they have basically always worked. This feature, while super useful if you are used to it, is very jarring is you are not used to it. So again, please just add the option to turn it off.

**Comment by roblourens** [comment] 2024-02-05 13:12
This should be fixed in 1.86. Could you check that you're on that release and if it's still an issue, tell me more? Thanks

**Comment by binaryfire** [comment] 2024-02-05 13:39
Same, can confirm this is fixed in 1.86. Thank you!

**Comment by binaryfire** [comment] 2024-02-11 18:55
@roblourens This issue is still there for me on 1.86.1. I'm on WSL2.  Was it re-introduced the latest update?

**Comment by ianbruton** [comment] 2024-02-12 17:06
I can also confirm that this has indeed broken again in 1.86.1

It seemed to be fixed when I updated last week, but it is broken again.

**Comment by binaryfire** [comment] 2024-02-12 19:14
@roblourens Here's a screen recording. It's intermittent - sometimes it happens, sometimes it doesn't: 

https://www.youtube.com/watch?v=vKFvWYfogng

Would it be possible to re-open the issue until it gets fixed?

**Comment by binaryfire** [comment] 2024-02-15 21:53
It seems there's some reluctance to re-open this issue, so I've created a new one here: https://github.com/microsoft/vscode-copilot-release/issues/661

**Comment by roblourens** [comment] 2024-02-16 18:09
Thanks for the recording. That's weird, but I was about to rewrite the input history management yet again so hoping I can squash it this time. Sorry for the churn

**Comment by roblourens** [comment] 2024-02-22 12:42
I see that this can happen when you press up to navigate history, then clear the input box and start typing. Now when you do this, it should correctly prevent you from navigating history and lose what you typed. History navigation should only be allowed when the input box is cleared.

I still want to do some refactoring so that you can navigate history and come back _without_ losing what you typed but it needs more refactoring, a couple things make this more complicated here than in other places.

**Closed** 2024-02-22 14:03 UTC
Labels: bug, panel-chat
