### ISSUE TITLE
Github Copilot breaking in DevContainer

### ISSUE THREAD

**Issue by mvobbi** [microsoft/vscode-copilot-release#574] opened 2023-11-15 12:43 UTC
Type: <b>Bug</b>

Start a DevContainer in docker running PHP7.4 apache and GitHub Copilot Chat bombs out and I get the message Remote Extension Host Crashed

Extension version: 0.10.1
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 22.6.0
Modes:
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6d76696e63656e742f4f6262692f4f626269576562417070222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6d76696e63656e742f4f6262692f4f6262695765624170702f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6d76696e63656e742f4f6262692f4f6262695765624170702f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6d76696e63656e742f4f6262692f4f6262695765624170702f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|32.00GB (6.87GB free)|
|Process Argv|--crash-reporter-id 1af933b1-e523-4a11-9314-284bd9e9592e|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f6d76696e63656e742f4f6262692f4f626269576562417070222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f6d76696e63656e742f4f6262692f4f6262695765624170702f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f6d76696e63656e742f4f6262692f4f6262695765624170702f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f6d76696e63656e742f4f6262692f4f6262695765624170702f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by chrmarti** [comment] 2023-11-21 10:15
What are the resource limits set in Docker Desktop settings?

**Comment by mvobbi** [comment] 2023-11-22 15:51
CPU limit : 8
Memory limit : 7.9GB
Swap 1 GB
Virtual Disk Limit 64 GB

**Comment by jrieken** [comment] 2023-12-06 11:02
duplicate of https://github.com/microsoft/vscode/issues/194458

**Closed by jrieken** 2023-12-06 11:02 UTC
